### ISSUE TITLE
BWS v2.1 does not recognize APCMini v5 script in /extensions (linux)

### ISSUE THREAD

**Issue by ElectronicBattle** [git-moss/DrivenByMoss#1]
Bitwig v2.1 
linux Mint 18.1

using the new v5 script installed into ~/Bitwig Studio/Extensions my Akai APCmini worked first time but then refused to work at all no matter what I tried. $ lsusb identifies the device and dmesg|tail shows it enumerate, and I can read data from it (e.g. using midisnoop).

[edit 22/5/17 - it is possible that this "first" detection was due to BW seeing the device via the earlier v4 script which I had installed in readiness, and subsequent removal of the v4 script has resulted in not being able to detect the controller]

Installing the older v4 script  in ~/Bitwig Studio/Controller Scripts and deleting the v5 "DrivenByMoss.bwextension" ... restarting BW  immediately autodetected the APCmini and it worked well. 

Trying the v5 script again, back in its correct location, and BW couldn't identify the device. Manually installing the device from the dropdown list shows the "DrivenByMoss" version to be available, but when I install it and configure it, the controller doesn't work. No lights, no onscreen response.

There seems to be some conflict between Alsa and Jack and APCMini - Alsa as the driver model allows v4 APCMini to be autodetected. Jack as the driver model does not allow BW to autodetect. Using v5 i(n either case) fails to be detected

**Comment by git-moss** [comment]
Hmm, I wanted to test my scripts as well with Linux last weekend but could not make anything work. Maybe you are right with your ALSA conflict assumption. Will need some more time to test this.

**Comment by git-moss** [comment]
I upgraded my Linux installation to Ubuntu 17.04 and everything works fine with ALSA.
However, the autolookup of the APCmini was broken. Should be fixed in the next version.

**Comment by git-moss** [comment]
I upgraded my Linux installation to Ubuntu 17.04 and everything works fine with ALSA.
However, the autolookup of the APCmini was broken. Should be fixed in the next version.

**Comment by ElectronicBattle** [comment]
Today's  release ahs solved the problem, Brill! Thanks very much.
