### ISSUE TITLE
Launchpad Pro Record Arm issue

### ISSUE THREAD

**Issue by cmtec** [git-moss/DrivenByMoss#100]
While in horizontal session mode and record arm selected the pad selection is offset one pad to the right. 
  *ie: to select clip one I need to press pad number two (the pad right to the expected pad)*  

The same function in vertical session mode work correctly.  

Using Launchpad Pro in Bitwig v2.4.2 for Linux and DrivenByMoss-4.00.zip

**Comment by git-moss** [comment]
Thanks, will be fixed in the next update.
