### ISSUE TITLE
OSC aftertouch howto?

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#101]
Hi,

Pitchbend and velocity seems to work.
But how to I consume inside of the polysynth the OSC messages send to Bitwig for aftertouch e.g.: 
Receiving: /vkb_midi/0/aftertouch [ 114.79 ]

**Comment by git-moss** [comment]
You need to insert an "Expressions" modulator in the Polysynths Modulation section. Than you can map the "PRES" to any parameter you like.

**Comment by kdejaeger** [comment]
In that case it does not work anymore.
I tried modulating polysynth pitch with expressions->press. Without any effect when OSC plugin receiving following messages:
Receiving: /vkb_midi/0/aftertouch [ 97.51 ]
Receiving: /vkb_midi/0/aftertouch [ 98.08 ]
Receiving: /vkb_midi/0/aftertouch [ 98.66 ]

**Comment by git-moss** [comment]
Aftertouch needs a note played first and is also realted to a note (this is poly pressure). E.g.:
/vkb_midi/1/note/64 70
/vkb_midi/1/aftertouch/64 127
/vkb_midi/1/note/64 0

This plays note 64 with velocity 70, then aftertouch is set to 127 for note 64 and finally the note is stopped.

**Comment by kdejaeger** [comment]
Ok interesting. I don't know yet how to do poly aftertouch in _http://osc.ammd.net/_. I need to consume the keyboard widget's output into another widgets address, I'll ask the dev.

But what about the channel aftertouch then. I'm having these messages now:
Receiving: /vkb_midi/1/note/52 [ 127.0 ]
Receiving: /vkb_midi/1/aftertouch [ 64.16 ]
Receiving: /vkb_midi/1/note/52 [ 0.0 ]

Is this supposed to work with polysynth as well?

**Comment by git-moss** [comment]
I just tested that and the data is sent correctly but I have no idea how to make this work with Polysynth. Maybe ask Bitwig support if this is supported.

BTW By looking at the code I noticed that the midi channel range is actually 0-15 but I changed it now to 1-16 to be consitent with all other 1 based numbers in the protocol. Will be in the next update.

**Comment by kdejaeger** [comment]
Good. Interesting. With polysynthetic, I ment polysynth + expressions->press modulator. Does this modulator work for you or not. Just to be clear...

**Comment by git-moss** [comment]
It works fine for Poly Pressure (0xE0) but not for Channel Aftertouch (0xD0).

**Comment by kdejaeger** [comment]
I've got it working for polypressure now. What I notice is that despit the aftertouch value being dynamic between 1-127, when you couple the pressure modulator to let's say polysynth->pitch. The applied modulation is always 100%.

**Comment by kdejaeger** [comment]
I have send the following to support@bitwig.com

I am using the mossgrabers bitwig extension and sending OSC messages to it.

There's the poly pressure aftertouch (0xE0) which seems to work. For example:
/vkb_midi/1/note/64 70
/vkb_midi/1/aftertouch/64 127
/vkb_midi/1/note/64 0  
However the modulation applied by the modulator expressions->pressure acts like an on/off switch. If I send  '/vkb_midi/1/aftertouch/64 63. I would have expected half of the modulation being applied, not fully 100% . 

Channel aftertouch is also part of this extension but does not work (0xD0). For example:
/vkb_midi/1/note/52 [ 127.0 ]
/vkb_midi/1/aftertouch [ 64.16 ]
/vkb_midi/1/note/52 [ 0.0 ] 
Is this supported in any way? Channel pitchbend for instance just works and is similar.

**Comment by kdejaeger** [comment]
Hello, I have not gotten more info from Bitwig support. They say both method should work and you need to talk to the developers. Can I have your email address so I can forward you the mails?

**Comment by git-moss** [comment]
juergen dot mossgraber at googlemail dot com
