### ISSUE TITLE
Launchpad Pro add full support for Track Control

### ISSUE THREAD

**Issue by cmtec** [git-moss/DrivenByMoss#102]
**Feature request:**   
Please add track controll support for all three modes.

**Comment by git-moss** [comment]
What 3 modes you mean?

**Comment by cmtec** [comment]
Session, Note and Device.

Right now only "Volume", "Pan" and "Sends" return to previous mode. "Record Arm", "Track Select", "Mute", "Solo" and "Stop Clip" force switching to Session mode (as you described in the instructions)

**Comment by git-moss** [comment]
Ah, I see. Will be fixed in the next update.

**Comment by git-moss** [comment]
As I wrote above I already changed that and it will be in the next update (hopefully today).

**Comment by cmtec** [comment]
I got the impression that my initial request was solved in version 3.44. My bad.
Thanks for your time and effort on this request!

**Comment by git-moss** [comment]
Yes, it was. Sorry, for the confusion just trying to wrap my head around what has changed.

**Comment by cmtec** [comment]
Clarification:
My suggenstion above was based on the v3.44 release (that only implemented the "case UP")
