### ISSUE TITLE
Native crash in cairo graphics library

### ISSUE THREAD

**Issue by emilm** [git-moss/DrivenByMoss#103]
A friend of mine has your plugin in Bitwig, and he had several crashes supposedly involving it. That's what the Bitwig staff said, at least.

The problem is that when dealing with graphics and fonts via Bitwig, it accesses the graphics context of the cairo library that Bitwig uses, and that is **not** thread safe. The problem happens very rarely, so it's an edge case. but when it happens, it takes entire Bitwig with it, since the crash is in native / unsafe space.

I could make a PR with an assumed fix (adding syncronized in the graphicscontext accessing Bitwig's)

[Dump3.txt](https://github.com/git-moss/DrivenByMoss/files/2605929/Dump3.txt)
[Dump2.txt](https://github.com/git-moss/DrivenByMoss/files/2605930/Dump2.txt)
[Dump1.txt](https://github.com/git-moss/DrivenByMoss/files/2605931/Dump1.txt)

**Comment by git-moss** [comment]
I talked to the Bitwig devs. It seems to be a Mac specific issue and they will look into this for the next update.

**Comment by emilm** [comment]
Did they fix it?

**Comment by git-moss** [comment]
No, yet since it is very hard to reproduce. Up to my knowledge they want to look into it after the 3.0 release. Better contact them directly.

**Comment by emilm** [comment]
Ok thanks. It's most likely a race condition due to the graphics library not being thread safe
