### ISSUE TITLE
Can only launch clips 1-8 from any track using OSC

### ISSUE THREAD

**Issue by pierrep** [git-moss/DrivenByMoss#104]
I'm on Ubuntu Linux. I'm using OSC to trigger clips, but this extension crashes if I try and trigger a clip greater than 8. e.g. if I send an OSC message such as
`/track/1/clip/9/launch`

Everything else works fine. The docs suggest the osc message should be
`/track/{1-8}/clip/{1-N}/launch`

I'm on Bitwig version 2.3.3, so I'm using version 2.0 of the extension.

**Comment by git-moss** [comment]
Yes, seems that is broken. It made me wonder if it would make more sense to have this pageable as well. What do you think?

**Comment by git-moss** [comment]
It means you can scroll by pages of 8 (like with tracks). I do not do any backports.

**Comment by pierrep** [comment]
Ah ok I see. I'm controlling BW without caring for the GUI, so it's not useful for me, but I can imagine it would be for someone else.

Yeah I thought a backport would be optimistic. I guess I'm going to have to renew mysubscription then ;)

**Comment by git-moss** [comment]
I checked the code: It is already paged by 8 but you scroll it with the following commands:
/scene/{+,-} Step by 1
/scene/bank/{+,-} Step by 8

**Comment by computersarecool** [comment]
As I question: Why do you use the paginated paradigm? Why not just set the clip numbers to what they really are? 

Pagination has the (to me) undesirable effect of making something like `/track/1/clip/8` not actually being `/track/1/clip/8` if I have scrolled at all.

**Comment by git-moss** [comment]
I used pagination since the main application of this OSC protocol is for OSC clients which do not give you any programming capabilities (TouchOSC, Lemur, etc.).

Note: The Bitwig API always gives you pagination, you can work around that if you create one very big page (e.g. 1000 tracks).

**Comment by jarmitage** [comment]
Hi @git-moss, has anything changed regarding pagination?

I am controlling Bitwig from tidalcycles.org and am also suffering from pagination limitations...

Would it be possible (and not too difficult) to either
1. Support values >8 and have the extension handle pagination state updating internally?
2. Have separate additional OSC paths for non-paginated values?

If the answer to one or both is yes, but you wouldn't want to spend your own time on this, would you accept PR(s)?

**Comment by git-moss** [comment]
Since version 8.97 you can set the pagination up to 200.

**Comment by jarmitage** [comment]
The issue isn't the number of pages available, it's that I can't do:
```
"/track/{>8}/volume"
```
Instead I have to do two separate commands:
```
"/track/bank/{bank}"
"/track/{track}/volume"
```
Which is not impossible to make user friendly for live coding.

**Comment by git-moss** [comment]
That's what it does. If you set the page e.g. to 16 you can then write /track/12/...

**Comment by jarmitage** [comment]
OH I see! I'm sorry I didn't grok that. That is excellent. Thanks very much for explaining.
