### ISSUE TITLE
Launchpad: Octave change in Piano Mode is broken

### ISSUE THREAD

**Issue by dgmulf** [git-moss/DrivenByMoss#106]
Piano mode works correctly in Launchpad Pro until an octave change, at which point the pads no longer correspond to the correct notes.

**Comment by git-moss** [comment]
Thanks for reporting! Took me some time to fix this but it was actually a pretty simple bug :-) Will be in the next update.

**Comment by dgmulf** [comment]
Thank you for the excellent script!
