### ISSUE TITLE
Reset colors to default in settings doesn't reset to default

### ISSUE THREAD

**Issue by jlvandenhout** [git-moss/DrivenByMoss#107]
I tried to change some colors in the Display Colors section. As soon as I press Reset colors to default, it fills the boxes with 0's and 1's (instead of RGB values, I suppose?), causing everything on the Push 2 display to go black and make it unusable.

I'm on a fresh install of Windows 10, Bitwig Studio 2.4 and extension script version 11.02.

**Comment by jlvandenhout** [comment]
Looking at the code I think it may be a naming issue? I see constants with and without DEFAULT_ prefix

**Comment by git-moss** [comment]
Thanks, will be fixed in the next update.
