### ISSUE TITLE
MIDI modulator does not receive signals other than CC1

### ISSUE THREAD

**Issue by psytechno604** [git-moss/DrivenByMoss#109]
Bitwig Studio 2.4.3, Build date 2018-11-21
Controller: Akai LPD8
Script version: 23.12.2018 | DrivenByMoss-4.03.zip (from your site)

What I have done:
1) Installed extension, restarted Bitwig.
2) Settings -> Controllers -> Add -> Generic -> Flexi ...
3) Selected LPD8 in both in and out dropdowns.
4) Touched knob 1, clicked Add, Slot 1 expanded - here I set Function: Device: Set Parameter 1, then touched knob 2, pressed Add, set Function: Device: Set Parameter 2 and so on.

After than my remote controls and Bitwig devices began to work automatically, but MIDI modulators stopped to catch signals from knobs 2-8, only knob 1 is working (CC1).

**Comment by git-moss** [comment]
I am not sure what you mean with "MIDI modulator". If you try to map a knob to a script and the same knob to a direct MIDI mapping this will naturally give you a conflict.

**Comment by psytechno604** [comment]
https://www.bitwig.com/en/bitwig-studio/devices/modulators.html -> MIDI

Why conflict? It is legal to control more than one parameter in DAW using one knob, even simple "map to controller or key" option allows it. But when I use your script to map controller to Bitwig's specific commands (CH2 CC X -> Device: Set Parameter X), all CC's became muted, except the first one..

http://prntscr.com/m6b5rh - I turn both knobs, but only the first is accepted by correcponding modulator..

**Comment by git-moss** [comment]
Sure, you can control multiple values but stick to remote controls for doing so by using Macros.
I hope this video helps:
https://www.youtube.com/watch?v=UeK9cGfNDeo
