### ISSUE TITLE
OSC /vkb_midi/... messages not preserving the midi channel #

### ISSUE THREAD

**Issue by nsystemssoftware** [git-moss/DrivenByMoss#111]
When sending vkb_midi messages to Bitwig 2.4.3 (linux) the midi channel number is being ignored -- all of the note/cc messages are being received on midi channel 1

**Comment by git-moss** [comment]
Yes, you are right. It seems that the function NoteInput.sendRawMidiData was not updated to support this in Bitwig 2.4. I will report this.

**Comment by git-moss** [comment]
Fixed in Bitwig 2.5.
