### ISSUE TITLE
Utilities: Auto Color Yellow is missing (DBM v5.2)

### ISSUE THREAD

**Issue by cyanit** [git-moss/DrivenByMoss#112]
Seems like the colors yellow & light yellow are missing in the autocolor utility.

Have a nice day!

**Comment by git-moss** [comment]
I am afraid there is no yellow in the Bitwig color list.

**Comment by cyanit** [comment]
Well that's strange, what color palette are we talking about? 
The Bitwig one does have yellow and light yellow.
![bwcolor](https://user-images.githubusercontent.com/26248671/53112198-04b9ad80-353f-11e9-8c2b-16e33299c478.PNG)

However, as far as I can see, not all of them are in the [DAWColors.java](https://github.com/git-moss/DrivenByMoss/blob/master/src/main/java/de/mossgrabers/framework/daw/DAWColors.java) or [NamedColor.java](https://github.com/git-moss/DrivenByMoss/blob/master/src/main/java/de/mossgrabers/controller/autocolor/NamedColor.java) file.

**Comment by git-moss** [comment]
The one you highlighted is called "Light Orange" in the Auto Color extension. I am not sure are there any "official names" of these colors? I think I took those names when first implementing the APC40mkII.
