### ISSUE TITLE
push sequencer: change Octave Up/Down behaviour in Chromatic mode

### ISSUE THREAD

**Issue by luroc** [git-moss/DrivenByMoss#113]
I hope I didn't just overlook a feature, but when playing in chromatic mode the notes g to h become inaccessible as octave up/down always jumps to the next c.
This is kind of the expected behaviour regarding the label of the button, but I think it would be better to change the behaviour so that octave up/down scrolls to the next seven half tones above or below the currently viewed half tones. Or maybe this could be implemented using Arrow up/down?

(I would actually prefer to be able to use the tempo poti to scroll through sequencer views one half tone per "click" as I rarely change the tempo but scroll through the "piano roll" a lot and I think that actually being able to scroll instead of jumping octaves would be much nicer in terms of orientation, but I guess that wouldn't be easily implementable)

**Comment by git-moss** [comment]
Sorry, I will not change that.
