### ISSUE TITLE
Crash caused by possible font issue on 2.5 betas

### ISSUE THREAD

**Issue by andrewshand** [git-moss/DrivenByMoss#114]
Hi,

I sent a bug report over to the Bitwig team a little while ago and they said the crash I was experiencing may be down to the Push 2 controller/script. Ever since I stopped using the Push 2 I am no longer experiencing this issue.

Hard to say exactly what triggers it within Bitwig as it appears to happen randomly, the assertion that fails each time is 
`Assertion failed: (! scaled_font->cache_frozen), function cairo_scaled_font_destroy, file cairo-scaled-font.c, line 1326.`

I've attached the entire macOS crash log which may be of use. If you don't think it's anything to do with you, of course feel free to close. But from narrowing down the cause it seems to have something to do with this controller.

I'm aware of course that this is occurring on the 2.5 betas, but as 2.5 is nearing release now I thought this may be more pertinent.

Let me know if there's any more information I can provide. This controller script makes my life so much easier and I can't thank you enough for it, so it would be really nice if I could use it without any issue.

[Bitwig crash log.txt](https://github.com/git-moss/DrivenByMoss/files/2906059/Bitwig.crash.log.txt)

**Comment by git-moss** [comment]
These are known issues with the Cairo framework on macOS. That's why the graphics API is still marked as Beta. I forwarded your crash log to Bitwig.

**Comment by git-moss** [comment]
Fixed in Bitwig 3 (Cairo library was updated).
