### ISSUE TITLE
freeze sequencer function bitwig studio

### ISSUE THREAD

**Issue by erwanito12** [git-moss/DrivenByMoss#115]
Hello,
thank you for your excellent work.
on DrivenByMoss-5.6.zip for bitwig studio
Launchpad Pro / MkII
we have many to have the function: note, which freezes in sequencer version, no matter the firmware version of the launchpad pro.
it will be very nice if you could find a solution.
we do not have this problem with LaunchpadPro4BitwigV1.zip.

thanks again for your fantastic work

**Comment by git-moss** [comment]
Fixed.
