### ISSUE TITLE
Remote Control Page Display Error on Push 1

### ISSUE THREAD

**Issue by unity2k** [git-moss/DrivenByMoss#117]
I just updated to Driven By Moss 5.9 (though I cannot right now tell you which version last functioned correctly) and the display of values on the Push 1 are not being updated for all Remote Control Page associations. Typically 1 knob will work consistently and a couple of others might work momentarily but they very quickly stop functioning and only one random knob will continue to display changing values.

When the knobs are not displaying their changing values on the Push 1, they still function in Bitwig to change values there. 

I'm on Bitwig 2.5 Windows.

**Comment by git-moss** [comment]
That's a regression bug in 2.5. I already reported it.
