### ISSUE TITLE
[Issue] OSC: Some /device/page functions are mis-documented

### ISSUE THREAD

**Issue by super-frais** [git-moss/DrivenByMoss#118]
On the Send side (coming _from_ Bitwig), the docs list the following address:

`/device/page/selected {1-8}`

This address doesn't contain data. However, `/device/page/{1-8}/selected` _does_ contain data (notice the subtle reverse in the last 2 terms in the address).

The docs also list:

`/device/page/{1-8}/ {name}`

I assume this to mean (for example) `/device/page/1` would return the name of remote control page 1 - but no stream is showing up on this address. I also tried `/device/page/1/name` in case it was a typo. As above, I assume there is a way to poll the name of a page at a particular index, and that the syntax in the docs is just wrong.

The remaining page address - `/device/page/selected/name` - functions as intended.

**Comment by git-moss** [comment]
I fixed the "selected" documentation, thanks for the info.

"/device/page/{1-8}/ {name}" is correct. I guess you need to add the last slash, e.g. "/device/page/1/".
As an example you can take a look at the Open Stage Control template included in the download.
