### ISSUE TITLE
OSC /vkb_midi/1/cc/ issues

### ISSUE THREAD

**Issue by geslotencirkel** [git-moss/DrivenByMoss#119]
using BW 2.5 and v5.9 of scripts - failing to assign midi CC to mappings in BW via 
/vkb_midi/1/cc/1 127 for example.

bug or is this not compatible with BW mappings?

**Comment by git-moss** [comment]
As it is it is intentional. To make this work I would need to add UserControl-parameters but then the CC-data would not be routed directly to VST plugins anymore. Therefore, I decided to not do that. To create mappings use remote parameter mappings instead.

**Comment by geslotencirkel** [comment]
thanks for the info.
fyi to others - all of these can be remapped to anything in bw. 
/device/param/{1-8}/value {0-127}
/device/layer/{1-8}/volume {0-127}
/device/layer/{1-8}/pan {0-127}
/device/layer/{1-8}/send/{1-8}/volume {0-127}
