### ISSUE TITLE
Support beat repeat button

### ISSUE THREAD

**Issue by git-moss** [git-moss/DrivenByMoss#12]
Requires: https://github.com/teotigraphix/Framework4Bitwig/issues/20

**Comment by aarongeorge** [comment]
@git-moss any updates on this?

**Comment by git-moss** [comment]
Just a little bit more patience...

**Comment by aarongeorge** [comment]
Haha okay, I'll wait for the next release 🤐

**Comment by git-moss** [comment]
Will be available in DrivenByMoss 8.50.
