### ISSUE TITLE
Push 1: arrow buttons not working

### ISSUE THREAD

**Issue by luroc** [git-moss/DrivenByMoss#120]
I have issues with the navigation arrow keys and the layer down/up keys.
The up and down arrows of the navigation arrows (bottom right) don't work at all in any mode.
The layer up/down keys (above mute/solo) can be used to navigate through the parts of the clips in sequencer or drum mode, but can't be used to enter or exit instruments.

I can Assign the up and down arrows of the navigation arrows via midi mapping so they seem to be functional somehow.

Platform: Win 7
Bitwig Version: 2.4
tested drivenbymoss versions: 5.2; 6.0

Honestly I'm clueless about how to debug this on Windows as I usually use Linux and would appreciate any help. Let me know if I can provide any more Information.

**Comment by git-moss** [comment]
Cursor up/down should select the previous/next clip. That is not working?

Layers are now navigated differently: Press the first row button of the selected layer again to enter it. To move out of it again, either long press any of the select buttons or press the eigth button of the 2nd row.

**Comment by luroc** [comment]
No, the up/down Cursors never light up and don't do anything. (I tried clip selection again explicitly)

Already found the different layer navigation but thought it was just an alternative. I was referring to your youtube tutorials and thought this could be a related issue.

**Comment by luroc** [comment]
Just did a quick test on Linux (fedora 29). Same behaviour.

**Comment by git-moss** [comment]
OK, will check but can't before the weekend.

**Comment by git-moss** [comment]
I cannot see a problem. Are you sure you have more than 8 scenes? Otherwise you will see no effect (and lights will be off). Also you only see the "selection square" when Session/clip view is active.
