### ISSUE TITLE
What does "indicate" do?

### ISSUE THREAD

**Issue by computersarecool** [git-moss/DrivenByMoss#121]
In your wiki you have: `/track/{1-8}/volume/indicate {0,1}`  What does the "indicate" part mean?  I have noticed slightly inconsistent behavior with the GUI slider moving up and down, and I see the tip of the slider goes red when I set `indicate` to `1`.

Is there some extra code you need to do to update the GUI?

**Comment by git-moss** [comment]
Indicate means that you get color notifications of the elements you control in Bitwig. In that case the volume faders. It gets confusing if you have multiple devices/scripts connected since they all look the same.
You do not call any other command.
