### ISSUE TITLE
Is there a way to get all the clips on a track?

### ISSUE THREAD

**Issue by computersarecool** [git-moss/DrivenByMoss#122]
If I wanted to create a list of all the clips on a track, how would I loop through all of the clip slots?
It seems I would want to start my trackBank at 0 and move through 1 "page" at a time (8 clips) but I am not sure what the correct way to make sure I visit all clips would be. Can you help me with this?

**Comment by git-moss** [comment]
I guess you can do that but I would not recommand that. If you have an application where you want to have all of the data at once it would be better to implement your own OSC protocol (see my API tutorials on Youtube): https://www.youtube.com/watch?v=1eoNBkXgOJk
