### ISSUE TITLE
Push not appearing in possible controllers

### ISSUE THREAD

**Issue by drewLo** [git-moss/DrivenByMoss#123]
technically not directly related but encountering some difficulty installing dbm this on new machine. 
  placed the .bwextention file in `%USERPROFILE%\Documents\Bitwig Studio\Extensions\` as instructed but the push ins't coming up in possible controller additions:
https://imgur.com/JlCjm0S 

adding a generic keyboard mapping allows the push to be used as midi, but no light up / display action. the wiki doesn't explain where to go from there. any ideas what might be amiss?

**Comment by git-moss** [comment]
There are mainly 2 reasons for that:
1) The file is in the wrong location (also check that there is no additional sub-folder)
2) The file is corrupted
Check the Bitwig log file and the script console for errors.

**Comment by drewLo** [comment]
verified that both the console and file location are standard and without problems. 
see:
![file location default](https://imgur.com/DZndGyj)
![no issues in console](https://imgur.com/vLmJ9Ar)

**Comment by git-moss** [comment]
Did you check the Bitwig logfile in C:\Users\<USER>\AppData\Local\Bitwig Studio ?

**Comment by drewLo** [comment]
Using version 2.5
Checked the log file, but outside of a bunch of metadata errors for izotope vsts, the only thing that looked out of place was:
```
[2019-04-21 13:02:27 base-usb-libusb error] :
	bwg: Could not get configuration descriptor: Entity not found
	at bxu.haV(SourceFile:54)
	at bxu.<init>(SourceFile:36)
	at bxA.zbq(SourceFile:241)
	at java.lang.Thread.run(Thread.java:745)

[2019-04-21 13:02:27 base-usb-libusb error] :
	bwg: Could not get configuration descriptor: Entity not found
	at bxu.haV(SourceFile:54)
	at bxu.<init>(SourceFile:36)
	at bxA.zbq(SourceFile:241)
	at java.lang.Thread.run(Thread.java:745)
```
at the very top. Since the push is a usb device, I suppose it could be related, but not sure what to make of it.
[rest of the log](https://pastebin.com/WeHcbs7M)

**Comment by git-moss** [comment]
I am starting to run out of ideas. Two things you can try:
1) Move the "Bitwig Studio" folder from your Documents folder somewhere else. Start Bitwig, see if the folder gets recretaed. If not, there is something totally mixed up.
2) Try again with the new folder. If still no success, try another extension, e.g.: http://www.mossgrabers.de/Software/Bitwig/MultisampleGenerator.html

**Comment by drewLo** [comment]
Something is "totally mixed up": Tried your first suggestion and it seems bitwig is not recreating the extension folder (and some others).

![no extension folder](https://imgur.com/a/cdBUZ1s)
only initializing `Library` and `Projects`.
Couldn't find anywhere in bws settings to specify a location for an extention location, so this is likely related. A reinstall didn't fix things. maybe it's a bws bug.

**Comment by git-moss** [comment]
You should contact Bitwig.

Drew Lough <notifications@github.com> schrieb am Mo., 22. Apr. 2019, 18:21:

**Comment by drewLo** [comment]
Follow - up:

- When setting up the new computer, OneDrive "subtly" asked to get set up. It then placed the contents of my "Documents" folder into a /OneDrive/ sub-directory.
- Seems to set some registry keys (unfortunately don't know what they are) that bitwig relies on to determine the location of /Documents  ... and therefore ./Bitwig Studio/Extensions.
- Since those permissions weren't easy to track down, remade a new windows local-user, w/o onedrive enabled during install, then migrated my stuff over. it was not a painless process, but at least I can use my hardware again.

cheers.

**Comment by git-moss** [comment]
Oh, wow. OneDrive is a nightmare... Great you found the cause!

Please also forward to Bitwig, in case anyone else comes up with that issue.
