### ISSUE TITLE
OSC: Does "Host to send to" work?

### ISSUE THREAD

**Issue by computersarecool** [git-moss/DrivenByMoss#124]
Hi,

I have been testing this script.  When I set `Host to send to` to an external devices IP address, it still just keeps sending to my local machine.

I tested this by running a node.js OSC listening script and saw that the messages just kept coming to my local machine instead of the machine at the address specified.

I started and stopped the script a few time and saw no changes.

![Screenshot from 2019-04-30 01-28-51](https://user-images.githubusercontent.com/5414692/56949723-720e2f80-6ae8-11e9-8fde-c7c564d31825.png)

**Comment by git-moss** [comment]
Yes, that is a combination of several bugs/problems with Bitwig:
https://github.com/teotigraphix/Framework4Bitwig/issues/208
https://github.com/teotigraphix/Framework4Bitwig/issues/73 (#1)

**Comment by computersarecool** [comment]
@git-moss you reported these bugs to Bitwig 3+ years ago and they have not fixed them?
