### ISSUE TITLE
Footswitch doesn't seem to work in new release 

### ISSUE THREAD

**Issue by elvisfurcic** [git-moss/DrivenByMoss#125]
With the latest release the footswitch doesn't trigger anything anymore for me on the push 1 in bitwig.

**Comment by git-moss** [comment]
Wroks fine here. Could it be that you connected your footswitch accidently to the 1st input instead of the 2nd? The 1st always sends damper pedal CC.

**Comment by elvisfurcic** [comment]
Oops yes, you're totally right. Sorry my mistake ...
