### ISSUE TITLE
Native Instruments Komplete Kontrol Mk II Setup - MIDI - ONLY ONE ENTRY

### ISSUE THREAD

**Issue by mikelo303** [git-moss/DrivenByMoss#127]
**Native Instruments Komplete Kontrol Mk II
Setup**
Select the MIDI input and output ending with "DAW" as the first channel. - I HAVE ONLY ONE ENTRY
Select the MIDI input and output without an ending as the second. - THIS IS NOT VISIBLE

Everything works so far except I do not have an option for second entry in MIDI controller set up. I did everything as you explained in video, I mapped knobs to my Komplete M32, they work, all buttons work except keys. No sound, no MIDI. No option in setup to add second entry for midi. Any ideas?

**Comment by git-moss** [comment]
So, which of the MIDI ports is missing? If the DAW one misses it means that the NIHostIntegration service is  not running. If the other one misses the driver is not installed correctly. In both cases try to reinstall the Komplete Kontrol software.
If that does not help please contact NIs costumer support.
