### ISSUE TITLE
Session scene button indication for current scene play

### ISSUE THREAD

**Issue by git-moss** [git-moss/DrivenByMoss#13]
Scenes currently don't have a play state.

Could be indicated if all clips of the scene are playing?

**Comment by abique** [comment]
Bitwig does not have a play state for a scene.
We could have a computed value which indicates if there are any clip playing for the given scene.

**Comment by git-moss** [comment]
Yes. Thats how I do it currently, but with the disadvantage that I have to
use a large bank page.

Alexandre Bique <notifications@github.com> schrieb am Mi., 22. Mai 2019,
18:14:

**Comment by git-moss** [comment]
Can be worked around with a large clip bank if needed.
