### ISSUE TITLE
No lights on APC Mini

### ISSUE THREAD

**Issue by chriscraws** [git-moss/DrivenByMoss#131]
First off - thanks so much for sharing all this work!

I am running Bitwig 2.5.1 on Ubuntu 19.04 and I have an APC mini.

All the controls I have tested work, but no lights display on the controller. I tried sending raw midi events from my command line to the APCmidi and was able to get the lights to turn on and off - any ideas what the issue could be?

**Comment by git-moss** [comment]
I did some tests on Ubuntu 19.04 and the APCmini behaves totally erratically. Sometimes everything works fine, sometimes (as you wrote) only the input and sometimes nothing at all.
I guess it is some kind of driver or system incompatibility. Sorry, but I have no idea what I could do about it.
