### ISSUE TITLE
Strange clip focus behaviour in clip launcher 

### ISSUE THREAD

**Issue by elvisfurcic** [git-moss/DrivenByMoss#132]
In my project I have many tracks grouped together. When I click in the clip launcher on one of the tracks inside the group or on the group scene the push reflects that current focus state. As I trigger a scene on the push it plays the scenes inside that group. That is all expected behaviour regarding the focus it is current in. 
However when I'm navigating out of the group using the push or when I click on a global scene clip and I trigger a scene the focus jumps back to the group I was last in and plays only the group scene. 
The way I bypass this for now is by adding a single track globally and click on one of the clips to set the focus there whenever I want to play the global grouped scenes. 
Is there maybe an easy fix for this? I hope I explained it clear enough. If not let me know, maybe I can record a video.

**Comment by git-moss** [comment]
I see what you mean. Since I only call start on the scene, there is nothing I can do about it. Maybe you should talk to Bitwig what the idea is here.

**Comment by elvisfurcic** [comment]
Ok, I'll try to get in touch with them and present them this issue. And if I understand you correctly you don't do any focus management from the push to bitwig when you navigate out of a group, right?

**Comment by git-moss** [comment]
I only call "cursorTrack.selectParent ()".
