### ISSUE TITLE
What template to use with Novation 61SL mkII

### ISSUE THREAD

**Issue by klingtnet** [git-moss/DrivenByMoss#134]
What template of the 61SL mkII do I have to use (this nowhere documented)?

I'm using Bitwig 3.0.1 and the latest `master` from this extension, here are my Controller settings:

![Screenshot-1564232295](https://user-images.githubusercontent.com/1538057/61994764-1e779780-b07f-11e9-805b-017fef2d8307.png)

PS: I can play notes, but nothing else.

**Comment by git-moss** [comment]
No need to load a template because it uses the Live-Automap mode. But you need to select the 2nd in-/output as first and the 1st input as the 2nd.

**Comment by klingtnet** [comment]
If anyone wonders, this is the configuration to use:

![Screenshot-1564336835](https://user-images.githubusercontent.com/1538057/62010985-a094b880-b172-11e9-8d12-bb0980fcfff5.png)
