### ISSUE TITLE
Komplete Kontrol Mk2 - instrument not detected if it's not the first device in the chain

### ISSUE THREAD

**Issue by bbbscarter** [git-moss/DrivenByMoss#135]
Repro:
- In Bitwig, add a Komplete Kontrol device to a new, empty device chain. Note the KK keyboard detects and syncs with the KK device.
- Add a third party arpeggiator before the KK device - e.g. Cthulhu or BlueArp. Note that the KK keyboard no longer detects the device.
- Move the third party arp after the KK device - the KK keyboard now detects the KK device, but the arp no longer sends midi events to the KK device.

Given that the 'instance' button on the KK keyboard also doesn't list all the devices in Bitwig, it's no longer possible to control the KK device from the keyboard at all if there's a third party arp before it.

I think this is because both BlueArp and Cthulhu are registered as synths, as well as midi out devices, and thus the controller script finds the first synth in the device chain and thinks the chain doesn't contain a KK synth device.

A workaround is to have the arp on a seperate device channel, and pull in the midi notes through a note sidechain modulator.

Thanks!

Simon

**Comment by git-moss** [comment]
Interesting problem but I am afraid I cannot fix this. Looking up a device is very limited and I can only tell Bitwig "give me the first instrument".

**Comment by bbbscarter** [comment]
No worries - thanks! 

And more generally, thanks for your Bitwig integrations - they're greatly appreciated!

Simon

**Comment by bbbscarter** [comment]
Sorry to be annoying and continuing this, but I was wondering if there was a workaround.

I was trying out your 7.03 version, with its support for editing non-KK devices in Bitwig. (It's really excellent - thanks!). I noticed that the device being edited on the KK keyboard changes depending on which device you have selected in the device chain.

I was wondering if the same thing could be done for KK devices. e.g.
- By default, when a track is selected it selects the primary device in the chain. (As now, this will fail if the KK device is not the first one in the chain).
- If the KK device within the chain is manually selected, it overrides the selection with the cursor device.

This would allow third party arps to work, and would also allow fancy things like instrument layers, XY layers, etc, to work.

(I'm happy to try this out myself, if you can point me at where the device selection happens in code).

Thanks!

**Comment by git-moss** [comment]
Now that you can select devices on the KK it makes sense. I could check if the selected device is a KK, if not try with the first instrument (as it is now).

**Comment by bbbscarter** [comment]
Yup - that sounds absolutely perfect.
