### ISSUE TITLE
Sending MIDI CC via Grid Pads

### ISSUE THREAD

**Issue by dschiller** [git-moss/DrivenByMoss#136]
Copied the PrgChangeView.java and cloned it to CCAView.java to be able to create a new View for sending MIDI CC Data via the GridPads. But the ``this.surface.sendMidiEvent (0xB0, this.programNumber, 127)`` doesn't come trough. The Pads always send Note Data instead of MIDI CC. Is it possible to find the Code where the Note Data will be send and the CC will be filtered ? I also tried to use the handleCC / handleCCEvent Methods. They send kind of CC but only internaly for the Push Device not to Bitwig.

Thanks a lot!

**Comment by git-moss** [comment]
That's a bit complicated. Your code is correct but it works only with VST devices. If you want to control Bitwig devices with CC you need to create a UserControlBank.
