### ISSUE TITLE
Launchpad MKII : playing state not reflected

### ISSUE THREAD

**Issue by flyingrub** [git-moss/DrivenByMoss#137]
When in session mode and launching a clip, the pad color involved should reflect the playing state by blinking green, it is not the case with the latest version 31.07.2019.

Note : I would be glad to work on this and do the pull request if you have some recommendation. :)

**Comment by git-moss** [comment]
Thanks for reporting, will be fixed in the next update.

**Comment by flyingrub** [comment]
I can confirm it is fixed on the latest master.
