### ISSUE TITLE
Novation launchpad mkII : black pad randomly blink sometimes

### ISSUE THREAD

**Issue by flyingrub** [git-moss/DrivenByMoss#138]
Here is a video showing the behaviour :
![no_data_blink](https://user-images.githubusercontent.com/3988628/62580166-dc7ffa00-b8a5-11e9-8d72-81d2687d01aa.gif)

**Comment by git-moss** [comment]
Is that now with 7.05 or was that before?

**Comment by flyingrub** [comment]
It was already there before...

**Comment by git-moss** [comment]
Sorry, I cannot replicate that. Are you in a specific mode when that happens?

**Comment by flyingrub** [comment]
It was in Play mode but it happens also on any other mode. This only happen on my linux machine.

**Comment by git-moss** [comment]
Could also be a power issue or a problem with cable / or the port you use. I am afraid I cannot do anything about it.
