### ISSUE TITLE
Bitwig 3.0 suppport

### ISSUE THREAD

**Issue by aleksfadini** [git-moss/DrivenByMoss#140]
Doesn’t seem to work with Bitwig 3.0. Any chance we can have it updated to the latest bitwig release?

**Comment by git-moss** [comment]
Works fine with Bitwig 3.0. If you give me some info what is actually your problem / platform / etc. I might be able to help.

**Comment by aleksfadini** [comment]
Apparently the script does not recognize the different inputs from the KM Bop Pad as notes.
The regular "Bitwig Shortcuts" menu does.
Will open as a specific issue.
