### ISSUE TITLE
KM Bop Pad not supported on Bitwig 3.0.2

### ISSUE THREAD

**Issue by aleksfadini** [git-moss/DrivenByMoss#141]
Apparently the notes KM Bop Pad are not being recognized - in fact they are being ignored.
The regular "Bitwig Shortcuts" menu does read the Bop Pad outputs as midi notes correctly.

**Comment by git-moss** [comment]
Again: please give as much info as possible when report a problem. Otherwise it is not possible to help you!
Please describe in steps what you are doing. I guess you are talking about Generic Flexi? Could you add it? Do you receive MIDI in the mapping area of Generic display at all?

**Comment by aleksfadini** [comment]
The Bop Pad can be selected from the midi input in and out, but when hitting different quadrants on the pad (which send midi notes), in the section of Flexi that says:
"Use a knob/fader/button then click set..."
Instead of the correspondent midi note, the script picks up "2MMC Play, CC Breath Control" for any midi note being sent.
The Bitwig built-in Shortcuts -> Controller menu instead correctly picks up the different notes.

Sorry for the vagueness and thank you for looking into this.

**Comment by git-moss** [comment]
The text is the same for all MIDI types (cannot change it during runtime), I guess thats causes the confusion. Important thing is that the drop down above read "Note". "2 MMC Play, CC Breath Control" means that note 2 was received.
Now click on the "Set" button. After that the "Selected Slot - MIDI trigger" section should contain the same values. Now assign a function and store your settings.

**Comment by aleksfadini** [comment]
Thank you - will check in a few days and report back. 
Everything worked as you explained in 2.4, but for some reason unresponsive in 3.0 (config files should have carried on when updating).

Regardless, I can get to the Bop Pad in a few days and I will let you know after extensive testing.
Thanks a lot for helping me troubleshoot this, your script is great.

**Comment by aleksfadini** [comment]
Doing extensive testing, the BopPad midi notes are not being detected by the flexi script with bitwig 3. It works with bitwig 2. 

When I press a quadrant of the bop pad bitwig 3 “shortcuts” screen reads correctly as “midi keyboard C#-2” after setting up the bop pad as a general midi keyboard. 

But flexi doesn’t change the “uses knob/fader/button” and it reads as “2MMC Play, CC Breath control” any midi note. 

Now, with bitwig 2.4, the same flexi script reads the actual note. 

How can I submit a more detailed feedback?

**Comment by git-moss** [comment]
What OS are you using? Can you please check with the Midi Monitor, whoch os also part of DrivenByMoss what the wxact values are which are sent by the Boppad?

**Comment by aleksfadini** [comment]
Will do and report back. I am using Linux (arch)

**Comment by git-moss** [comment]
I did a bit of testing, all notes on all midi channels worked fine for me. But I noticed that Bitwig sometimes needed a reboot after I changed the midi input assignment. So, you can give that a try too.

**Comment by aleksfadini** [comment]
I did more testing and it would still work. Now that I updated to Bitwig 3.0.3 and last DrivenByMoss, it seems to work but some quadrants are “overlapped” and when I assign a midi note cc to a function (like transport play) the note is still played in any active instrument. 
Any ideas?


Did you test it with a KM BopPad and Linux?

**Comment by git-moss** [comment]
I do not have a BOP Pad and cannot test that. My tests above were done with different controllers I own.
