### ISSUE TITLE
Bitwig 3

### ISSUE THREAD

**Issue by Saber540** [git-moss/DrivenByMoss#142]
Is Ableton Push 1 not supported in Bitwig 3?

**Comment by git-moss** [comment]
It is supported.

**Comment by Saber540** [comment]
Hmmm... have the latest version both on a Mac and Win machine.  Not working in either.  Any ideas?  Push has latest firmware.  (Ver 1)

**Comment by git-moss** [comment]
Have you selected the 2nd in-/output? See https://github.com/git-moss/DrivenByMoss/wiki/Ableton-Push-I-&-II
