### ISSUE TITLE
Push 1 and Bitwig 3.02

### ISSUE THREAD

**Issue by Saber540** [git-moss/DrivenByMoss#143]
Unfortunately the latest version 7.21 still not working with push1 and Bitwig 3.02.  I've installed the script on both a Mac with Mojave and a pc with Win 10 Home, neither recognize my push, any suggestions?

**Comment by git-moss** [comment]
What do you mean by "neither recognize my push"? Do you see the "Push 1" extension in the controller settings? Can you add it manually? Do you see the Push 1 midi-in-/ouputs?
You need to select the 2nd in-/output!

**Comment by Saber540** [comment]
Good day, when I launch Bitwig (3.02) have the Push connected, under control settings nothing shows up.  No midi in or out ports, the script does not appear in controller settings.
I've attached a screenshot.
![Screen Shot 2019-09-11 at 12 55 54 PM](https://user-images.githubusercontent.com/52611314/64718136-9d8c2800-d493-11e9-948f-a79391b4553d.png)
it is the same on my windows system.  
On Mac w/ osx 10.14.6 Script location:  User/Documents/Bitwig/Controller Scripts/DrivenByMoss-7
I know there isn't an issue with my push, it works fine with Ableton 10.  Also if I create a generic controller and choose the push midi ports that way, the pads respond to note input.

**Comment by git-moss** [comment]
You copied the file in the wrong directory, see the installation instructions here: https://github.com/git-moss/DrivenByMoss/wiki/Installation
