### ISSUE TITLE
Question: /track/1/position << which position is this?

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#145]
Hey,

In OSC messages is /track/1/position an arranger position or the position inside a clip?

How can I render/plot the value of this message in Open Stage Control?

**Comment by git-moss** [comment]
It is the overall position of the track. E.g. if you have 20 tracks the position might be number 18. This value is independent from the bank paging.
To display it you can use any element which allows to display a value.

**Comment by j28** [comment]
Thank you! How do I display this value? I tried to put it inside a Text module, but it does not render in there. I'm slightly mystified by the return value types and which type can be shown in which plot module.

**Comment by git-moss** [comment]
E.g. add Plot->Text.
Select the text widget.
Scroll down to the OSC section.
In "address" e.g. enter /track/5/position
Note that you need to restart DrivenByMoss or rearrange the tracks to trigger sending the value (and therefore displaying it).

**Comment by j28** [comment]
This is what I tried and it did not work. I though that the value expected is a different type and that's why it does not work. I will try it again exactly as you described and if it does not work I'll confirm here.
