### ISSUE TITLE
Push 2 Touch Strip Pitch/CC

### ISSUE THREAD

**Issue by aarongeorge** [git-moss/DrivenByMoss#148]
It would be cool if the half of the touch strip that has the pitch, would allow both positive and negative changes to the pitch.

This way the pitch at 0 would be at 1/4 of the touch strip. 1/2 would be +MaxPitchBendRange and 0/4 would be -MaxPitchBendRange.

It would be nice if you could configure the halves to either snap back to 0 or stay at the last value.

Is this possible?

**Comment by git-moss** [comment]
I think that is a bit too much.
