### ISSUE TITLE
Launchpad Mini MK3: Device and bank labels do not display in Bitwig

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#150]
Hey,

I am playing with the Launchpad Mini MK3 mapping. When I toggle the device or remote control presets bank/page via Keys (mode) > first 4 buttons in the top row... Bitwig does not display the correct labels. The selection works... only the labels in Bitwig don't show as expected.

This works flawlessly in the APC Mini script... which is how I know what the expected behavior should be.

This is in 7.60 on a Mac. I have not changed any of the defaults

**Comment by git-moss** [comment]
Thanks for reportiung. Will be fixed in the next update.

**Comment by j28** [comment]
You are welcome. Thanks!

**Comment by j28** [comment]
Hey,
The behavior is different in the new release, but still does not work as one might expect. In the new version the parameter page label flashes briefly and within a fraction of a second is replaced by the track name label... which stays visible the regular amount of time. The parameter page label flash is too quick to read the content of the label.
Thanks.

**Comment by git-moss** [comment]
Are you using the latest release 8.60? Sorry, cannot spot a problem.

**Comment by j28** [comment]
Yes, I am.

I am also running a few other scripts, but even when I unplug these controllers (so their scripts are not active) the behavior above persists. I can record a short video if that helps.

**Comment by git-moss** [comment]
Yes, please.

**Comment by j28** [comment]
Here you go... In the video/gif below I am going through 2 actions on the Launchpad Mini MK3 in Keys mode:
1) toggling between devices [you can see the label remains Bass Arp the whole time]
2) going down the remote controls presets pages [you can see the label remains Bass Arp the whole time]

![label](https://user-images.githubusercontent.com/1156607/77231999-b130ed80-6b9e-11ea-875d-b2e44b0e7f56.gif)

**Comment by git-moss** [comment]
I am not sure what you are doing. Are you trying to use the hardware mapping features? If this is the case than this will not work. With DrivenByMoss you have to select the Device mode to change devices and banks (with the cursor keys).

**Comment by j28** [comment]
That's exactly what I am doing. I am using DrivenByMoss in device mode... using the cursor keys...  to switch devices and remote controls pages. 

So I assume that when the device or remote controls page is changed the corresponding label will show (like it does in the APC Mini).

I called it "Keys" mode because the label on the button which switches to Device mode says "Keys" (on the Launchpad Mini MK3).

**Comment by j28** [comment]
Sure, no problem. I will try to do it this weekend.

**Comment by j28** [comment]
This works as expected in the latest version. 

The issue was that when I switched devices and remote control pages via the arrows buttons (top left of the controller) on the Launchpad Mini MK3 the labels which say "Selected device: ..." and "Page: ..." did not appear.

They do now. Thanks!
