### ISSUE TITLE
Launchpad Mini MK3: Device selection

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#151]
I am not sure if this is an issue or this is the functionality by design... 

but on the Launchpad Mini MK3 when selecting devices the top arrow moves to the next device while the down arrow moves to the previous device...

It would be more intuitive if the top arrow moved to the previous device while the down arrow moved to the next device.

This is because the devices are displayed left to right (in Bitwig and in the Push display), not bottom to top.

**Comment by git-moss** [comment]
Yes, I agree. Will change it in the next update.

**Comment by j28** [comment]
Great. Thanks!
