### ISSUE TITLE
Launchpad Pro: no indication of deactivated tracks/clips

### ISSUE THREAD

**Issue by ahihi** [git-moss/DrivenByMoss#153]
hello,

just bought a Launchpad and i'm very impressed with this extension, fantastic work!

one thing that confused me for a moment is that deactivated tracks (and clips) aren't indicated in the session view in any way, and also do not disappear when "show deactivated tracks" is disabled...

after poking around in the code a bit, it looks like the clip and bank APIs may be lacking functionality to implement these things. but `Track` has `isActivated()` (via `Channel`), so it should at least be possible to indicate disabled tracks e.g. by using desaturated colors, right?

i just got my IDE set up, so i might take a shot at implementing this myself :) but i'm new to both Launchpad and Bitwig programming, so if you have any additional thoughts about this idea please let me know!

**Comment by git-moss** [comment]
The Bitwig API provides many features but nevertheless has some hole. This is one of them. My wish and buglist can be found here: https://github.com/teotigraphix/Framework4Bitwig/issues/226
