### ISSUE TITLE
Faders for tracks within a group

### ISSUE THREAD

**Issue by valankar** [git-moss/DrivenByMoss#154]
I cannot seem to figure out how to expand group tracks and adjust faders of tracks within the group. I'm using a Push 2. I also notice this with the Bitwig native Faderport 8 driver as well. Is it possible?

**Comment by valankar** [comment]
https://github.com/git-moss/DrivenByMoss/wiki/Ableton-Push-I-&-II

1st 8 button row: Press to select a track, press again to enter a group. To rec arm a track, keep the record button pressed and select the channel (first button row). Use in combibation with the Delete button to delete a track. Long press a button to leave a track group.

I also tried this but it does not seem to do anything.

**Comment by valankar** [comment]
Did some more testing and strangely this works in a new project. It just doesn't work in an existing project for some reason. If I can do any more testing let me know.

**Comment by git-moss** [comment]
Strange, never had such an issue. Can you post the problematic project?

**Comment by valankar** [comment]
I did some more experiments and it seems related to hidden tracks. See the attached project.

When 'show hidden tracks' is off, you cannot descend into the Drums folder, even though there are unhidden tracks in there. When 'show hidden tracks' is on, it seems to work.

[folder test.bwproject.zip](https://github.com/git-moss/DrivenByMoss/files/4014216/folder.test.bwproject.zip)

**Comment by git-moss** [comment]
I can reproduce that. Seems to be a Bitwig bug.

**Comment by git-moss** [comment]
Cannot reproduce this anymore in Bitwig 4.2.
