### ISSUE TITLE
Page display Issues in Browse Mode

### ISSUE THREAD

**Issue by dschiller** [git-moss/DrivenByMoss#157]
Wrong Pages are shown when browsing Presets Metadata. The Cursor is on a different Page then the displayed Page, this way it is impossible to make a Selection.

Repro Steps:

- Open Browser on empty Track
- Navigate Right to "Preset" Section
- Touch Rotary for Section "Location" << Displayed first Entries: "All Presets", "Packages" ...
- Rotate to select "Packages"
- Hold Rotary touched << after approx one Second the "Location" jumps from Page 1 to Page 2; it should stay on Page 1 as long the Selection doesnt reach the last Entry on Page 1

Same happen for all Sections except the Presets itself.

Note: This only occours if the List has more than one Page.

Push Moss 8.6.0
Bitwig 3.1.2
Windows 10
Push 1 ( Firmware 1.16 )

**Comment by git-moss** [comment]
I cannot replicate this but I just changed something in that area, which could have fixed this. Please test with the next update.

**Comment by dschiller** [comment]
Seems to work Thanks!
