### ISSUE TITLE
Midi monitor does not propagate sysex messages

### ISSUE THREAD

**Issue by MINDoSOFT** [git-moss/DrivenByMoss#158]
Hi there !

I was trying to implement something that needed to handle a sysex message, and I noticed that the sysex message wasn't shown in the extension console, but was shown in the midi monitor extension console.

Once I disabled the midi monitor extension the sysex messages are properly received from my extension.

Don't know if that is the desired functionality ! Just putting it here as a note.

**Comment by git-moss** [comment]
Most MIDI drivers are single client, which means you can only assign it to one extension.
