### ISSUE TITLE
Launchpad Mini MK3: Clip Grid Navigation

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#159]
Hey,

On the LP Mini MK3 when in Session mode the UP arrow button moves the selected 8x8 area of the clip launcher grid DOWN... and the DOWN arrow button moves the selected area of the clip launcher grid UP. :)

UP button = moving the grid selection UP
DOWN button = moving the grid selection DOWN

Would be more intuitive. :)

Thanks!

**Comment by git-moss** [comment]
I just changed this because many other people complained about being the other way round :-) Sorry, will stay that way now.

**Comment by j28** [comment]
Hah. They must have muscle memory from an older version of the controller or another controller. I'm just starting with it. I suppose I can use tape or something. :)
