### ISSUE TITLE
OSC did something wrong - Parameter port (=0) must be in the range 1024 to 65535

### ISSUE THREAD

**Issue by ovitus** [git-moss/DrivenByMoss#161]
I'm getting the following error when trying to start the OSC controller:

OSC did something wrong - Parameter port (=0) must be in the range 1024 to 65535

I haven't had any problem with this on my other PC.. any idea what the issue is?

**Comment by git-moss** [comment]
Yes, this requires a Bitwig update (hopefully available soon). I forgot to mention that in the release notes.
However, I am checking now the lower range toe be >= 1024 as well as different receive/send ports.
