### ISSUE TITLE
Programming Mode turn off for Launchpad (esp. X)?

### ISSUE THREAD

**Issue by Jengamon** [git-moss/DrivenByMoss#162]
When I close bitwig, my Launchpad X simply turns all its lights off rather than going back to the default standalone mode.

It might be possible that the code leaves programming mode on. According to the Launchpad Mini Mk3 programming guide, it should be possible to set it back to live mode using:
`F0002029020D 0E 00 F7`
Which is just "[header] [p/l mode select command] [live mode] F7".

I think this is the problem, as it resets when I power-cycle, but I don't want to have to powercycle everytime I close Bitwig...

DrivenbyMoss Version: 8.70

**Comment by Jengamon** [comment]
Ok, weird. I dug into the code and I found where it should be called.
And it looks fine. It might be a Bitwig bug, because when I restarted Bitwig, even though the extension started, the Launchpad X's mode didn't change...

**Comment by Jengamon** [comment]
Yeah, this is probably a Bitwig bug, as powercycling a few times makes the device connect again, and if I close Bitwig after turning off the device, everything is fine, but if I leave it on, the last state, or even all blacked-out pads are left, and it also happens with my custom JS script.

**Comment by Jengamon** [comment]
Steps to produce the problem are:

- Connect the Launchpad X to Bitwig using DrivenByMoss
- Close Bitwig.

The last state, or an all blacked-out set of pads are what this results in.
I may be not entirely in the clear here, though, as I am using a USB hub.

**Comment by git-moss** [comment]
By coincidence I implemented this just some days ago. It will be in the next update.
The problem with the exit function is a long standing issue:
https://github.com/teotigraphix/Framework4Bitwig/issues/104
