### ISSUE TITLE
Master view upon Push doesn't stick when master fader knob is touched.

### ISSUE THREAD

**Issue by lunardigs** [git-moss/DrivenByMoss#164]
Push2, Fedora 31 Linux, BWS 3.1.2, DBM 8.70.

Upon touching the master fader knob, the master fader view appears (on the Push screen), but then disappears after ~1 second. Turning the master fader knob does not change this behavior.

Meanwhile, the master fader knob works to control the DAW. Moreover, you can press the Master button on Push and the intended view will stick, regardless of master fader knob interaction (touch/release,turn).

**Comment by git-moss** [comment]
Thanks, will be fixed in the next update.
