### ISSUE TITLE
OSC script default should be set to 1024 or higher

### ISSUE THREAD

**Issue by polarity** [git-moss/DrivenByMoss#165]
When you add OSC as a controller and select an midi device you get the message (Parameter Port (0) must be in the range 1024 -  65535). Which obstructs the input fields, becuse they never show up. (you cant change the port because the port is wrong ...)

Easy solution would be to set the port to 1024 or something as default.

**Comment by git-moss** [comment]
Thanks, see here: https://github.com/git-moss/DrivenByMoss/issues/161
