### ISSUE TITLE
OSC did something wrong - Bitwig 3.1.2 / DrivenByMoss-8.70

### ISSUE THREAD

**Issue by dschiller** [git-moss/DrivenByMoss#166]
When adding the OSC Controller in Bitwig, Bitwig shows the Error Message:

OSC did something wrong

Parameter port(=0) must be in the range 1024 to 65535.
Disable / Restart

How can I fix that ?

**Comment by git-moss** [comment]
You can't: https://github.com/git-moss/DrivenByMoss/issues/161
