### ISSUE TITLE
Advanced Step Editing in the APC40/MKII Sequencer

### ISSUE THREAD

**Issue by martinsotirov** [git-moss/DrivenByMoss#167]
It would be really helpful if the drum/note sequencer allows to edit the step with the device knobs on the APC40 MKII while the step is pressed.

Something like:

- Knob 1 - Pitch
- Knob 2 - Gate (Note Length)
- Knob 3 - Velocity

I'm not a Java developer but if you point me in the right direction I can try implementing a PR. I assume a new mode would be needed under `framework/mode/device/`?

**Comment by git-moss** [comment]
Upcoming in Version 9!
