### ISSUE TITLE
'Flip session' for Launchkey Mini Mk3? (poss just documentation)

### ISSUE THREAD

**Issue by peterdutton** [git-moss/DrivenByMoss#168]
Hi,

firstly thanks for these amazing extensions to Bitwig!

I was finding it hard to get used to the clip launcher controls in session mode, because the orientation is strange in the default view (i.e. in this mode the the pads control clips across the channels, which are usually displayed in rows).

However I came across Mix view and in this view it works much better, because the channels are across the top instead of the scenes. I think this is closer to how Ableton does it and so closer to the orientation that the controller is expecting.

Maybe this is worth adding to the documentation? Or possibly it's only confusing because I am new to Bitwig.

Thanks again!

**Comment by git-moss** [comment]
Yes, the mix mode has the layout of the Ableton session/clip mode. The Launchkey layout is in that regard identical how it works with Ableton. Flipping the layout does not make much sense if there are only 2 rows of buttons.
