### ISSUE TITLE
Launchpad Mini MK3: Trackbank becomes 7 tracks (incl. group track) instead of 8 when there is a group track

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#169]
Hey,

When I have a group track inside a track bank the Launchpad has an empty track after the group track, which reduces the total amount of tracks within the trackbank from 8 to 7 (incl. the group track).

I am attaching a screenshot of Bitwig as well as a corresponding photo of the Launchpad. In the controller photo you can see the 6th track is empty and the 6th and 7th tracks in Bitwig are in positions 7 and 8 on the Launchpad.

![IMG_6851](https://user-images.githubusercontent.com/1156607/77228455-ea119800-6b87-11ea-85b0-144b5311e24e.JPG)
<img width="695" alt="Screen Shot 2020-03-21 at 3 04 02 PM" src="https://user-images.githubusercontent.com/1156607/77228461-f695f080-6b87-11ea-81b7-faf49d609328.png">

**Comment by git-moss** [comment]
I admit this looks confusing (and I also had to look up again what is going on) but it is actually a Bitwig feature. If the mastertrack is added to the track bank, this also adds the master tracks of the groups. You can display the mastertrack of the group if you right click on the track and click on "Show Mastertrack content". The clips you put in there appear in this empty row.

**Comment by j28** [comment]
I don't think we are speaking about the same thing. What you are referring to is right clicking on the group/folder track... In which case we can hide/show its content in track 1 (position 0). In the first screenshot above the group master track clips are highlighted in green.

What I am speaking about is the gap between tracks 5 and 7. Toggling between "show group track content" and "show master track content" does not affect the gap between tracks 5 and 7.

**Comment by j28** [comment]
Oh no, you are right...
