### ISSUE TITLE
Feature Request :) >> Settings switch/variable to toggle the presence of group master track content as a track separate from the the group master track

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#170]
In response to your comment below, is it possible to add a switch in the settings which when toggled would make it so that the track after the group is not reserved for group master track content?

I have 2 additional controllers for mixing tracks 1-8 and tracks 9-16... I currently don't have a reason to use the group master track content/clips... and dedicating 2 tracks to the group master track (one in the beginning of the group and another one after it) *really* throws me off during live performance... because the extra track is a slot in the Launchpad mini but not a slot in my mixing controllers (as it is not represented in the Bitwig UI as an additional track). 

So the 8 tracks in the Launchpad hardware control 7 tracks in the UI, while my other controller's 8 tracks control 8 tracks in the UI.

---

I admit this looks confusing (and I also had to look up again what is going on) but it is actually a Bitwig feature. If the mastertrack is added to the track bank, this also adds the master tracks of the groups. You can display the mastertrack of the group if you right click on the track and click on "Show Mastertrack content". The clips you put in there appear in this empty row.

_Originally posted by @git-moss in https://github.com/git-moss/DrivenByMoss/issues/169#issuecomment-602056766_

**Comment by j28** [comment]
P.S. The group master track (track 1, position 0) can already handle the display of the group master track clips/content... and when performing one could always make a scene which only has the clips included in the track bank... which makes the 2nd use of the group master track (to launch the clips inside the track banks for that row/scene) unnecessary. 

In that sense it would be better if people who play live with Bitwig could match the behavior of the Launchpad with the behavior of the Bitwig UI via the controller settings (in case anyone really needs 2 separate tracks to control the group master track content and the trackbank scene content launch separately).

**Comment by git-moss** [comment]
Will be available in the next update.
