### ISSUE TITLE
Feature request/suggestion for sequencer: Flash note that is played for current/active step.

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#171]
Hello,

It would be great if when in this sequencer mode:
![20200329_150945](https://user-images.githubusercontent.com/1156607/77850105-88c57680-71d0-11ea-9df5-71e254d1b613.jpg)

The controller would flash/turn green the note that is played by the current/active note that the sequencer is going through:
![20200329_150659](https://user-images.githubusercontent.com/1156607/77850117-a09cfa80-71d0-11ea-98a1-8a235dfc14d3.jpg)

The state of the buttons/leds when the sequencer is going through steps where notes are not present, could stay exactly as it is now:
![20200329_150739](https://user-images.githubusercontent.com/1156607/77850150-db069780-71d0-11ea-9d3e-c866a6b1d00e.jpg)

This is already the case for these 2 sequencer modes:
![20200329_152642](https://user-images.githubusercontent.com/1156607/77850381-70eef200-71d2-11ea-9d0b-1577047d34b5.jpg)

![20200329_152722](https://user-images.githubusercontent.com/1156607/77850383-75b3a600-71d2-11ea-9e47-0e11da68e7cd.jpg)

Thanks!

**Comment by git-moss** [comment]
Will be fixed in the next update.

**Comment by j28** [comment]
Thank you!!
