### ISSUE TITLE
Add Diagrams for Launchpad Menus in Wiki

### ISSUE THREAD

**Issue by porkloin** [git-moss/DrivenByMoss#172]
Hey there!

I'm super thankful that these plugins exist - being able to use my Launchpad with Bitwig is really amazing.

As I've been trying to learn how to rely less on my keyboard and more on my controller, I've been having a hard time remembering what every function on my Launchpad does, especially on the "shift" menu.

Anyway, I have no idea if you'll be interested in this, but I went ahead and forked the wiki and added a diagram for the Launchpad X/Mini/Mk3's layout for the shift menu. I hope the diagram that I created for my own uses can be helpful to other folks who might have the same problem as me!

Sadly, wikis don't allow pull requests, so I have to stuff all of this into a Github issue instead of a PR, but here's a link to the Launchpad page on my fork. I hope you'll consider merging it into the mainline repo!

https://github.com/porkloin/DrivenByMossWiki/blob/master/Novation-Launchpad.md

Also, let me know if you have any interest in me putting together more diagrams like these – the only controller that I have access to is a Launchpad X, but I'm happy to help make more of these if it helps folks get better at using your awesome software :)

Also, if anyone out there want to help create more diagrams to improve the Launchpad documentation, here is a public Figma document that has my complete source for the Shift Menu diagram I created:

https://www.figma.com/file/AG9vAxZdG7GvcK0kjCcmSk/Launchpad-Diagram-Public-Edit-Access-Please-Create-Duplicate-Before-Editing?node-id=0%3A1

**Comment by git-moss** [comment]
Hi! I like this a lot! Great job!

Yes, the Wiki functionality is very limited (e.g. no sub-folders). I thought about this a bit and decided to create a separate repo for the documentation. I plan to integrate the Reaper version there too and maybe generate PDFs from it to integrate into the release.

The new repo is here: https://github.com/git-moss/DrivenByMoss-Documentation

This is just a basic conversion of the Wiki and I did not integrate your diagram. 
Feel free to send a pull request. Please put the image(s) into the same sub-folder.

Cheers!

**Comment by porkloin** [comment]
@git-moss Awesome! I'll definitely open a PR.

In the meantime I've gone hog wild building out diagrams for the rest of the functionality of the extension based on the Launchpad X.

Before I open a PR it might make sense if you have a chance to review the verbiage and correctness of them in my design tool, since doing iterations before I export them to PNG is much easier.

If you have a minute to review, take a peek here: https://www.figma.com/file/AG9vAxZdG7GvcK0kjCcmSk/Launchpad-Diagram-Public-Edit-Access-Please-Create-Duplicate-Before-Editing?node-id=0%3A1

**Comment by git-moss** [comment]
Wow, that's incredible! I thought you would do 2 or 3 but that's the full box!
What I spotted:
- Drum Sequencer: The right bottom part: One pad is one edit page, you can change the length of the clip by pressing first the start (keep pressed) and then the end. The differently colored pad represents the edited page (not a page with notes).
- Device/Inst controls should be Device/Parameters. The right/upper button is "Toggle device window".
- The 2nd "Device/Inst controls" shoudl be "Browser" (and then the button on the previous page as well). The middle buttons should be "Scroll Browser columns". The up/down cursor keys toggle between "Insert before device" and "Insert after device". The left/right cursor keys are "Previous Browser tab" and "Next browser tab".
- "Session overview": I call this "Birds Eye view" but that is up to taste. Here it would be nice to show that 1 pad repesents a block of 8x8 clips.

**Comment by porkloin** [comment]
Awesome, I'll go ahead and make some edits and then open a PR once I have these changes finished up!

**Comment by git-moss** [comment]
Would be great if you could update the diagrams with the 9.10 changes.

**Comment by git-moss** [comment]
@porkloin Will you look into this?

**Comment by porkloin** [comment]
@git-moss Yes! Sorry for the delay, but I will generate some new screens for the new features. I also saw your response on KVR about your Figma account so I can grant you ownership on the design source files, but the invite system on that app requires an email address, not a username. If you can give me the email address you used to create your Figma account I'll get those shared as well. Feel free to just sent it to me in a DM on KVR if you'd rather not have it posted publicly.

I'll try to get the new screens generated within the next day or two!
