### ISSUE TITLE
Possible bug - Novation Launchpad Mini MkIII - cannot return to note mode selection

### ISSUE THREAD

**Issue by pgum** [git-moss/DrivenByMoss#173]
Hello,
from the docs, and from #172 diagrams I understand that "Note" button should make transition to "Note mode selection". In my Mini Mk.III case I also understand that Note on my device is Drums.

My usecase: 
Open up fresh reaper
add track with VSTi
launchapd goes to play mode - scale - autmatically - ok
press Note (Drums) button
proper menu occurs
I can select and return from play mode (first row) options - scales, piano, drum64
I can also select and return from sequencer (bottom most row) options

I can select DRUM, DRUM4, DRUM8 options, but once I click them "Note" button doesn't do anything. With Debug hardware emulator, all colours and behavoiur is the same as on physical device.

Once new track is created, on new track I can select play modes, but cannot undo if once selected DRUM DRUM4 DRUM8.  

I cannot find anything in wiki or mentioned documentation repo (from #172), what am I missing?

**Comment by git-moss** [comment]
Thanks for reporting! Just fixed it, will be available in the next update!
