### ISSUE TITLE
Push 2 - More colors configuration for different screens (feature request)

### ISSUE THREAD

**Issue by hoergen** [git-moss/DrivenByMoss#175]
Is it possible to have some more color configuration for different screens on the push 2 controler?  So you can configure the different screens in a different way. Or maybe it is sufficient if e.g. Background is always the same. See the last image with the clips, where the "background" is grey instead of the defined "black"

And maybe a way to save the color "preset" ?

At the moment I have this configuration which is less bonbon colorful and in darker environments better for my very personal taste

![01_temp](https://user-images.githubusercontent.com/24474762/78771455-772e5c80-7990-11ea-9ac5-d75037a406ab.png)

This results in looking like this
![02_temp](https://user-images.githubusercontent.com/24474762/78771489-83b2b500-7990-11ea-8b02-ded864012be3.png)
![02_temp_a](https://user-images.githubusercontent.com/24474762/78771493-86150f00-7990-11ea-88df-f01cc839dad8.png)

The clip view has a grey background, even i have configured a black background. But it would additionally help, if I could configure maybe different background colors for the different screens, so it gives me additionally a visual hint where I am. So for example I would like to define a dark brownish background on the clip screen. As well the color of top "Bar" should be configurable

And maybe define a max height for the notes, that doesn't make use of the full height of the screen, if there is only one note on the bar. Just for the beauty ;)

![03_temp](https://user-images.githubusercontent.com/24474762/78771913-3551e600-7991-11ea-8d3a-f74152cd525a.png)
![04_temp](https://user-images.githubusercontent.com/24474762/78771920-371ba980-7991-11ea-9e44-843f0ebd4809.png)

**Comment by git-moss** [comment]
Thanks for the ideas! Will put it on the wishlist but this has some low priority.

**Comment by git-moss** [comment]
Next update will respect the color settings in the MIDI clip display. Also there will be always at least 4 rows visible.
