### ISSUE TITLE
[feature request] Komplete Kontrol MK2 - Assign touch strip/mod/pitch wheels?

### ISSUE THREAD

**Issue by neonhaus** [git-moss/DrivenByMoss#176]
Love the control scripts, you're a magician, been perusing through the documentation, and I was unable to find out how, if it's possible to map the touch strip. I suppose it would also be helpful to remap pitch/mod wheels as well, but I'd love the ability to assign midi CC# through your control script, so I don't have to be bothered to do it through the Komplete Kontrol app - for some reason, they don't like to play nice. 

I would love to use the touch strip for enabling sustain for more expressive playing without a sustain pedal.

Cheers!

**Comment by git-moss** [comment]
You can already do that:
1) Insert a MIDI CC device and select CC64.
2) Add a MIDI modulator in the MIDI CC device.
3) Learn the touch strip (CC11)
4) Map the modulator to the CC64 knob.

![grafik](https://user-images.githubusercontent.com/3090132/81479441-68eb8e80-9223-11ea-99f0-60c9cf0b8978.png)
