### ISSUE TITLE
Feature Request: [Launchpad line] Layer/pin/stack user modes to bottom rows of session mode

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#177]
This feature would be enormously useful to people who play live with Launchpad controllers. The basic idea is that the user modes can be pinned/layered to the bottom five rows as shown in the mockup below.

![moss-user-modes-layers](https://user-images.githubusercontent.com/1156607/79101607-2db38800-7d69-11ea-8968-6a9dccb9d66d.jpg)

This could work in the following way:
1) User presses and holds User button then presses and holds one of the bottom 5 user mode buttons (select track, mute, stop, solo/cue, record arm).

2) [Let's say upon step 1 above user pressed and held record arm user mode button] the controller would pin the user record arm row of buttons to the last row of the launchpad RGB pads.

3) Now the user repeats step 1 above, but presses and holds the solo/cue user mode button... the controller would pin the solo/cue row of buttons to the 2nd to last row of launchpad RGB pads.

4) Let's say the user would like to now "unpin" the record arm row of buttons... they would press and hold the User button + press and hold the record arm user mode button... the launchpad will remove the bottom row of record arm buttons and drop the solo/cue row of buttons in its place (moving it from second to last to last row of buttons).

The method for pinning and unpinning above would be amazing. However if it's too much work the pinned rows of user modes could also just be selected in the Bitwig controller settings. If using the settings to pin the user modes, it would be great if the user could choose the order of user modes rows.

**Comment by git-moss** [comment]
Next version will contain a mix mode with all modes on one page.

**Comment by j28** [comment]
Thanks. The new mixer mode is very convenient for production. What I described above is more convenient for playing live. I can fork and try to implement the above myself (now that the mixer mode is in place).
