### ISSUE TITLE
Pad at: Vert.: 2 horiz: 2 inactive

### ISSUE THREAD

**Issue by jminiko** [git-moss/DrivenByMoss#178]
Hello,
Tremendous work and kudos to you Jurgen,
I can not make the button/pad at: x:2y:2 (from up left corner) work, with Push 2 and Bitwig 3.1.3
will try to compile on my side but the source comments are rather scarce.
Best

Jimmy

**Comment by git-moss** [comment]
Could it be that you accidently mapped the pad in Bitwig?

**Comment by jminiko** [comment]
No I have a fresh install of bitwig 3.1.3 upon fresh install of linux (with KDE wm),
seems weird since for other projects it behaves normally.
I will have to invistigate.
Still another weird behaviour is :
I can not record the Track #1 in Sequencer mode (but when I select disarmed track #2 all is back to normal).
I send the link for you to try Jurgen.
[Nen-Lambo](https://drive.google.com/file/d/10drjPsBTSFZrDPhnslPZnCEkDYiz0Eb2/view?usp=sharing)


If you need any help in development and testing...I will be there.
I have in  mind the master mixer from RME for Linux, tell me your thoughts about it.
Best und Tschuss
Jimmy

**Comment by jminiko** [comment]
Hi,
It appears that when a scene (for a particular track) is launched on controller and then deselected in bitwig there is a problem,
I closed my ticket since it has a workaround
Viel Gruß
