### ISSUE TITLE
Push 2 - Scene buttons change Scenes when in NOTE mode 

### ISSUE THREAD

**Issue by hoergen** [git-moss/DrivenByMoss#179]
When in NOTE mode the scene buttons shouldn't switch the scenes. They should change the zoom of the clip right? 

In the current 8.96 they change the scene when in NOTE mode.

**Comment by git-moss** [comment]
You mean the normal play mode? No, there is no clip involved in this mode. The grid size is only controlled in the different sequencer modes.

**Comment by hoergen** [comment]
I have to investigte more, because at some point when using the drum sequencer it changes the scenes. But I don't know when exactely.
