### ISSUE TITLE
Push 2 - Bitwig 3.2 Beta 2 - User Screen doesn't show assignements

### ISSUE THREAD

**Issue by hoergen** [git-moss/DrivenByMoss#180]
Currently I'm testing Bitwig 3.2 Beta 2 and I noticed that controller assignments on the user screen are not shown anymore on the user screen. But they are still functioning (invisible) 

Maybe they changed something in the API?

**Comment by git-moss** [comment]
It's a bug in the Beta, they are already looking into it.
