### ISSUE TITLE
Push 2 button lights

### ISSUE THREAD

**Issue by JustMog** [git-moss/DrivenByMoss#181]
if possible it'd be great if unselected buttons on push 2 could be lit at a reduced brightness rather than completely unlit as this makes them almost impossible to read. (using bitwig)

**Comment by JustMog** [comment]
discovered the issue only occurs when running on usb power only

**Comment by git-moss** [comment]
You can try to increase the brightness in the settings.

**Comment by JustMog** [comment]
sorry, should have mentioned, this is at max settings
