### ISSUE TITLE
Push 2 switching from instr./scene recording does not update state [Midi Scene]

### ISSUE THREAD

**Issue by jminiko** [git-moss/DrivenByMoss#182]
Hello,
I wanted to operate following:
- arm on record scene / instrument 1
- in session mode create a midi scene for instrument 1(new button and pad)
- back to note mode with drum mode activated , record some stuff
- disarm on record the scene / instrument 1
- arm on record scene / instrument 2
- in session mode create a midi scene for instrument 2 (new button and pad)
- back to note mode with drum mode activated , 
- recording some stuff is impossible since it reflects inst. 1
Is this normal behaviour?

**Comment by git-moss** [comment]
I did not fully understand what you are doing. You cannot record enable a scene only tracks.
For drum sequencers (and all other sequencers), the selected clip is relevant.

**Comment by jminiko** [comment]
Yes I record a second track after having recorded a first one (with drum view)
However when recording the second one, the drum view displays the first one as ghost track
btw I am on linux kubuntu+realtime+jackd

**Comment by git-moss** [comment]
Could be that this is that bug you are experiencing: https://github.com/teotigraphix/Framework4Bitwig/issues/247

**Comment by jminiko** [comment]
No I think it is a new one:
arming a new track for record does not reflect in drum view after having recorded previously a first track with drum view
easy to reproduce each time

**Comment by git-moss** [comment]
You always see the selected clip in the sequencer views! No matter which track is selected or which one is record enabled.

**Comment by jminiko** [comment]
what do you call the sequencer view?

**Comment by jminiko** [comment]
Ok I found a workaround for what I wanted to do.
Vielen Dank :)
