### ISSUE TITLE
push 1 / bitwig 2.3 / drivenbyMoss 2.0, help plz :(

### ISSUE THREAD

**Issue by lunatao13** [git-moss/DrivenByMoss#183]
hello Moss, i use push 1 / bitwig 2.3 / drivenbyMoss 2.0, i extracted the 2.0 archive in /controller scripts/ but dunno what to do. push shows "start live to play". push wont show in controller.

can you help me plz ?

**Comment by git-moss** [comment]
It needs to be in the extension folder. Installation instructions are the same as with the latest release.

**Comment by lunatao13** [comment]
omg ! thk you very much Moss ! u rock ! :D
