### ISSUE TITLE
sustain is reversed

### ISSUE THREAD

**Issue by jameh** [git-moss/DrivenByMoss#184]
Hi, I have a Yamaha F-5 sustain pedal which unfortunately doesn't have a polarity switch on it.

Plugging it into footswitch 1 on my Push 2 which is connected with Bitwig Studio on Linux running this controller script, the polarity is reversed (pedal down does not sustain, pedal release sustains)

I've tried turning the Push 2 off and on, and unplugging and replugging the sustain pedal, also restarting Bitwig, but it never changes state.

I've also tried depressing the sustain pedal and turning off and on the Push 2 (this works sometimes with midi keyboards)

As soon as I unplug the footswitch, the sustained notes are terminated.

I'm wondering if the polarity is hard-coded in the controller script?

**Comment by git-moss** [comment]
I use what the hardware sends. As suggested in the Push manual you can try to press it before turning the device on. If this does not work you need a different footswitch.

**Comment by jameh** [comment]
Gotcha, I ended up being able to reverse the behaviour in hardware and made a video showing how: https://youtu.be/jdEH_xSkKRQ
