### ISSUE TITLE
Push 2 - In 3.2 Beta 3 Sequencer not showing last pressed instrument

### ISSUE THREAD

**Issue by hoergen** [git-moss/DrivenByMoss#185]
Noticed in the last Beta 2 and the latest DrivenByMoss 8.97 when using a drum sequencer the instrument doesn't change. I only can type in the the eg. Kick drum to the sequencer , but not one other instrument.

I'm able to play the instrument, but not editing the sequence is only possible with the first instrument on the drum rack.

**Comment by git-moss** [comment]
Yes, there are some breaking changes in 3.2. I am working on adapting my code to 3.2. This one is already fixed.

**Comment by hoergen** [comment]
Ok, maybe I wait until the final 3.2 Bitwig is released and you give a go for the script to be 3.2 ready ;)
