### ISSUE TITLE
Feature Request : tempo visual indicator, blinking play button

### ISSUE THREAD

**Issue by laurentdebricon** [git-moss/DrivenByMoss#187]
I was inspired by this video 
https://www.youtube.com/watch?v=CT6ABqYno6Y&start=307
where the author demos differents ways to get a visual tempo feedback.
It is usefull in live performances, you don't need to listen to the click.

I tried to look at the code, to make the launchkey mk2 play button blink on tempo. But i got lost. 
- subscribe to transport position ?
- on event && if (isPlaying) && if it is the beat right now
- blink play button without breaking to much stuff :dagger: 

Would appreciate some clues

**Comment by git-moss** [comment]
I do not have the Mk2. You would need to check if it is supported by the hardware. If yes it should be sufficient to send MIDI clock to the device.

**Comment by laurentdebricon** [comment]
oups i was talking about mk3 that DrivenByMoss supports :)

**Comment by laurentdebricon** [comment]
Hello,
i did it !
replace in LaunchkeyMiniMk3ControllerSetup.java l.195

```
this.addButton (ButtonID.PLAY, "Play", new PlayCommand<> (this.model, surface), 15, LaunchkeyMiniMk3ControlSurface.LAUNCHKEY_PLAY, () -> {
	if(t.isPlaying()){
                // t.getBeatText() return something like "3.2.1:66" , extracting '1'
		String[] tokens = t.getBeatText().split("\\.");
		if(Integer.parseInt(tokens[2].split(":")[0]) == 1){
			return true;
		}else{
			return false;
		}
	}else{
		return false;
	}
});
```

would love a feedback.

**Comment by git-moss** [comment]
You won't get a stable blinking that way. Bitwig only sends notifications or updates to the API "when there is time". Which means if processing is getting a bit heavy it will do funny things and blink very random.
Only solution is if the hardware itself provides time based blinking. Devices who support that normally receive MIDI clock to sync up. I checked the documentation and for the Launchkey Mini Mk3 this feature is available for the drum and scene pads but not for the other buttons (not the Play button).

**Comment by laurentdebricon** [comment]
ok ! 
i am going gently in the controler world, trying to find one little challenge after another.

How could I sync the pad lights then ? even with a basic script that does just that. 
I have searched the novation doc (i only find the midi table), bitwig scripting guide ...
If you could tell me where to start !

the best is this video https://www.youtube.com/watch?v=Ld_-f2XcBfA that will push me to write my arduino beat indicator :D 
Too bad i have a spare launchkey mini waiting for me to make it blink.

**Comment by git-moss** [comment]
To make the pads blink or glow send the note on MIDI channel 2 and 3.
