### ISSUE TITLE
Push 2 - Sampler - Textures - Motion parameter is lacking ?

### ISSUE THREAD

**Issue by hoergen** [git-moss/DrivenByMoss#188]
I can't find the entry for changing the Motion parameter in the sampler

![00_temp00](https://user-images.githubusercontent.com/24474762/81945534-85f6d780-95fe-11ea-825b-d6855038c922.jpg)

![51663e72-3c4d-41d3-bbe4-26c556b26944](https://user-images.githubusercontent.com/24474762/81945561-8e4f1280-95fe-11ea-880e-6f93d6cb94b1.jpg)

**Comment by git-moss** [comment]
Seems they forgot to add the new parameters to the parameter pages. Simply create a new parameter page and add the missing parameters.

**Comment by hoergen** [comment]
I used the User Page and mapped the controls there. Just wanted to info you, There are some more things that are laggy, like entering the note length in the sequencer works most time random by one click, double click up to 5 clicks with several retries. And in the drum Sequencer sometimes a pad doesn't dim back to off when deleting a note. Mostly the one on the bottom left (kick drum in a drum machine). But I think this is still because of the Beta version?
