### ISSUE TITLE
MCU: Cannot achieve bidirectional control with Allen & Heath DAW Control 1.71 (Mackie Control emulation)

### ISSUE THREAD

**Issue by douglas-carmichael** [git-moss/DrivenByMoss#189]
I'm trying to set up Bitwig Studio 3.2b6 (with DrivenByMoss 9.0b5) to use an Allen & Heath mixer using their supplied DAW Control driver speaking the Mackie Control protocol: (https://www.allen-heath.com/daw-control/) as a control surface.

Unfortunately, enabling four DAW Control devices (one main, three extenders) does not enable me to have bidirectional control as shown in the attached video. But, using one DAW Control device set up as a single Mackie Control surface works fine.

(When I set the four DAW Control devices up as Main/Extender/Extender/Extender I was able to get transport control from the simulated console but still no bidirectional fader/mute/solo control.)

What could cause this?

Here is a video of my tests: [https://www.youtube.com/watch?v=0F5iYkO5A9M](url)

**Comment by git-moss** [comment]
You selected the wrong in-/outputs. The 1st four are the inputs, so you need to select input 1-4. Then the outputs 1-4.

**Comment by douglas-carmichael** [comment]
Thanks! I selected the proper inputs and outputs, and it worked perfectly.
