### ISSUE TITLE
Can't switch back from "session" mode to "drum" mode in Reaper.

### ISSUE THREAD

**Issue by Determinant** [git-moss/DrivenByMoss#190]
How to reproduce:
In Reaper, with Launchkey Mini MK3:
1. Set up channel 1 and channel 10 for the keys and drum pads respectively. And they work well until...
2. Use shift to switch drum mode to session mode, and then back.
3. The drum mode no longer generates notes after going back.

BTW, this extension is great work!

**Comment by git-moss** [comment]
The sequencer does send notes. It creates notes in the selected MIDI clip and visualises them. I guess you did select a different clip on a different track when using session mode.

**Comment by Determinant** [comment]
That works, thanks!
