### ISSUE TITLE
Reaper: "Note" state tied to selected track in mixer

### ISSUE THREAD

**Issue by pgum** [git-moss/DrivenByMoss#191]
Using Launchpad MkIII mini, Reaper v6.11, Moss v9.02.
What happens:
Device in "Note" mode doesnt show any notes (no leds are on).  
Device is still sending proper notes.  
  
How to reproduce:  
* In Reaper create two tracks, Track A, Track B
* Set Track B so it is sub-track of Track A
* In Track Manager hide Track A from TCP view
* In Track Manager hide Track B from MCP view
* Select Track B from TCP and record
* You will see observed behaviour
* Behaviour is observable with Debug surface simulator

Additional info:  
* Select Track A from MCP view
* Track A colours are seem on surface (colours and on/off leds for notes)  

Workaround:  
* Select ARM recording in desired track, in example - Track B  
* Only select (click) on MCP view on Track A, to get any colours.

My use-case:
I got BBC Orchestra Discover.  
My track structure template is as follows -Root/Section/Instrument/Technique:  
* BBC
* * Woodwinds
* * * Piccolo
* * * * Piccolo Long
* * * * Piccolo Staccatissimo
* * * Flute
* * * * Flute Long
* * * * Flute Staccatissimo
* * * Oboe
* * * * Oboe Long ...
* * Brass
* * * Same 

In my TCP I have tracks from last level so:  
* Piccolo Long
* Piccolo Staccatissimo
* Flute Long
* Flute Staccatissimo
* Oboe Long
* ...etc  

In mixer I see instruments, so:
* BBC (as main track sink)
* BBC Woodwind (as separator)
* * Piccolo 
* * Flute  
* BBC Brass (as separator)
* * Horn  
* * ...

Because I mix instruments that gather techniques under them, this setup seems to work best, because I don't get clutter on TCP, nor do I ever intend to blend techniques in one instrument in MCP

**Comment by git-moss** [comment]
Why are you doing such things? ;-)

The extension uses the MCP list. Therefore if you hide a track from the MCP it will not be present anymore on the device and it will be displayed in black (actually it is black since there is no selected track on the device).
The recording is not necessarily tied to what you see on the device since the MIDI is sent to all tracks which are record enabled.

**Comment by pgum** [comment]
Ok but in my case I do it that way, because I have over 70 tracks to manage.    
And I use tracks as subdirectories to encapsulate techniques in instruments. But not all abstractions are needed to see in TCP. Same goes for MCP. In MCP I keep instruments and mixes, but not details of instruments technique.  

Anyway problem is when track is not visible in MCP. Which is regardless of my cursed bbc use-case :)


Can then be a feature to go get color of parent track, if selected track is not on MPC?
OR  
Can there be a feature to go get color of selected track, regardless if it was selected from MCP or TCP?

**Comment by git-moss** [comment]
The situation I could reproduce yesterday was that if the track is hidden in the MCU but slected in the TCP it does not show up on the controller (it is black). There is nothing I can do about this.
I am not sure if you describe a different situation. Maybe can you send a (as simple as possible) project which shows your effect?

**Comment by pgum** [comment]
Yes, that is the situation as you said. Sorry for my potato english ^^  
Oki if its not possible then I will need to look up/write some lua script to unhide track in MCP if its selected in TCP. That would resolve this probably, should be easy.   

Thank you for your help :)
