### ISSUE TITLE
Reaper: Launchpad Mk.III repeated "Note" button press makes selection menu buggy

### ISSUE THREAD

**Issue by pgum** [git-moss/DrivenByMoss#192]
Using Launchpad MkIII mini, Reaper v6.11, Moss v9.02.
What happens:
Three rows of led buttons from Note section (LP MK.III its "Drums" button, but always referred as Note, and here too) at first glow normal, instantly. When pressing more and more Note button, and changing options - red and blue lights start to randomly blink. From time to time only one row, usually either red or blue one, are visible.  
Invisible (turned off) buttons are still usable.

In device simulator, behaviour is different. Blinking occurs as on normal device. But second situation where only one row is visible, in simulator looks alright.

How to reproduce:

* In Reaper create one tracks Track A  
* Select Track A
* On Device push Note ("Drums")
* Select "play"
* On Device push Note ("Drums")
* Select "piano"
* On Device push Note ("Drums")
* Select "drum64"
* On Device push Note ("Drums")
* Select "drum"
* On Device push Note ("Drums")
* Select "drum4"
* On Device push Note ("Drums")
* Here it starts for me...  

Observations:  
* Options still can be selected
* Selecting any second row (blue one) option makes glitching almost instantly

If needed I can deliver video of how it looks.  
Not device malfunction, mint, and worked with previous version, and was alright. I see glitches also on Debug device simulator, but not looking the same way as on real device. Looks like buggy Note menu redraw?

**Comment by git-moss** [comment]
I sometimes noticed strange update behaviours with Launchpads but mostly with the older models. Did not yet recognise something like this on the Mini Mk3. I could also not reproduce what you desribe.

**Comment by pgum** [comment]
Hello,  
If it helps I can take video.  
Before v9.02 I have been using v8.9.x and apart from issues that I submitted I was happy user.  
Now I am still happy user, but with glitchy Note menu.
Reproducing on hardware is easy, can you reccoment me a site where to put video file?

**Comment by git-moss** [comment]
Yes, please do. Also give 9.10 a try which I released yesterday, just to be on the same page.

**Comment by pgum** [comment]
oki I will, sorry for late response, I wil get back to this today :)

**Comment by pgum** [comment]
Hello,  
on version: 9.10, with v.6.11/x64 I report bug fixed.  I have different bug tho, will open new ticket
