### ISSUE TITLE
Note highlight laggy in Play mode

### ISSUE THREAD

**Issue by pgum** [git-moss/DrivenByMoss#193]
Observed behaviour:  
Go to Note -> Play  
repeatedly (doesnt have to be fast) press notes.  
Observation: same note in different place lights up, but not synchronized. Sometimes note stays lighten up, when no input is given.  

This behaviour is observable in Debug Mode device simulator, but harder because it also lags on its own, so hardware tests give better results.  
Reaper version 6.11/x64, Windows10  
Moss 9.10.  
Observed behaviour was visible in previous versions, but much more rare.  

No logs from Loggging console, only this:  
```
Loading device INI files from C:\Users\killme\AppData\Roaming\REAPER ...
C:\Users\killme\AppData\Roaming\REAPER\reaper-jsfx.ini not present, skipped loading.
Novation Launchpad Mini MkIII: Starting...
Firmware version: 285
Novation Launchpad Mini MkIII: Running.
```

**Comment by git-moss** [comment]
I played around with for some time but did not spot an issue. Might be that it is dependent on high COU load?! If that is the case I am afraid I cannot improve that.

**Comment by git-moss** [comment]
Did you try to disable all in-/outputs of the LP in the Reaper settings?

**Comment by pgum** [comment]
Disabled and reenabled. With few whole PC reboots, and several reboots of Reaper alone.  
I see it like if btn press signal from device and feedback send from software to device in response are not in sync/"packages are missing" dunno. Just an idea. I come from different field, only did things in midi one way, and on arduino platform.

**Comment by git-moss** [comment]
Can't be improved.
