### ISSUE TITLE
OSC "Index out of bounds..." errors crash plugin

### ISSUE THREAD

**Issue by jarmitage** [git-moss/DrivenByMoss#194]
I might be wrong, but I feel it would be preferred for this error to be thrown without crashing the plugin.

Interested to know if there's a specific reason why it does.

**Comment by git-moss** [comment]
Yes, could be argued. I guess I was thinking that this way you directly notice that you did something wrong.

**Comment by jarmitage** [comment]
Are you able to popup notifications even when the extension has not crashed?

**Comment by git-moss** [comment]
No, I can only log to the console, which many users do not even know it exists.

**Comment by jarmitage** [comment]
Ok, in that case I agree that notification is important even if it does crash. I will clamp all the values on my side. Thanks 👍🏻
