### ISSUE TITLE
OSC: MPE polyphonic pitchbend

### ISSUE THREAD

**Issue by jarmitage** [git-moss/DrivenByMoss#195]
We have poly aftertouch in the OSC spec which is great, but only channel pitchbend:

```
/vkb_midi/{Channel:1-16}/aftertouch/{Note:0-127} {Pressure:0-127} Sends Poly Aftertouch
/vkb_midi/{Channel:1-16}/pitchbend {Pitch:0-127 (No-Bend:64)}
```
https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Generic-Tools-Protocols/Open-Sound-Control-(OSC).md#receive---play

Is there a reason why?

**Comment by git-moss** [comment]
The commands implement MIDI 1.0. Switching this to an MPE controller would mean it would always act as MPE (notes distributed on 16 channels), which also might not be what most user want.
