### ISSUE TITLE
launchpad gray colors (index=1,2) swapped?

### ISSUE THREAD

**Issue by ensonic** [git-moss/DrivenByMoss#196]
Can it be that these two colors are swapped?
https://github.com/git-moss/DrivenByMoss/blob/master/src/main/java/de/mossgrabers/controller/launchpad/controller/LaunchpadColorManager.java#L174-L175

If you look at the the various launchpad programmers references:
![image](https://user-images.githubusercontent.com/1279486/85785940-11997300-b72a-11ea-9fd0-ed8b01dbacfd.png)

it should probably be
``` java
        this.registerColor (LAUNCHPAD_COLOR_GREY_LO, DAWColor.DAW_COLOR_GRAY_HALF.getColor ());
        this.registerColor (LAUNCHPAD_COLOR_GREY_MD, DAWColor.DAW_COLOR_LIGHT_GRAY.getColor ());
```

**Comment by ensonic** [comment]
One more thing, in the same file 'Red' and 'Amber' got the same color.
```
  this.registerColor (LAUNCHPAD_COLOR_RED, DAWColor.DAW_COLOR_REDDISH_BROWN.getColor ());
  this.registerColor (LAUNCHPAD_COLOR_AMBER, DAWColor.DAW_COLOR_REDDISH_BROWN.getColor ());
```
For context, I wrote a LP miki mk3 progressive web app to see if a launchpad would work for my music workflow:
https://ensonic.github.io/ -> open 'midi pad matrix' on a mobile android device, connect via usb to your computer and enable midi in the usb menu. then start bigwig and selct the midi ports for the launchpad mini mk3.

**Comment by git-moss** [comment]
Argh, colors :-)
The problem is that there is only this fixed palette, which even contains duplicates and the ones who should be different are hardly noticable to be different and depend highly on LED calibration as well. E.g. I played a bit with the gray settings but could hardly notice any difference at all between the different gray values.

**Comment by ensonic** [comment]
This was mostly a heads up for you. I now cut out the image from the manual, cropped it with gimp, then expanded the color-palette (to make black actually black and white actually white) and then used a python script to pick colors from the image :)

Now the colors match nicely in the device mode (with the bitwig rainbow colors), but in session/play mode the track colors are still wrong:
Track color is yellow, on my simulated mk3 it is orange
![20200628_153007](https://user-images.githubusercontent.com/1279486/86530881-e1399d80-bebc-11ea-8799-347e160e2eb8.jpg)
Track color is orange, on my simulated mk3 it is red
![20200628_153017](https://user-images.githubusercontent.com/1279486/86530886-ff9f9900-bebc-11ea-861f-c51cdacaca30.jpg)
for the other tracks: pink, purple and bright blue works. For the top track, orange shows as red. 

I now ordered a real device (Launchpad X) - will hopefully be able to compare next week and most important - make some funky music!
