### ISSUE TITLE
[Feature request] Clip Select - Option to navigate clips instead of pages in Session view

### ISSUE THREAD

**Issue by gnzgg** [git-moss/DrivenByMoss#197]
(Novation Launchpad mini MkIII // Bitwig)
Hi ! 
I've been using DrivenbyMoss (with a Launchpad mini MkIII) with Bitwig for a couple weeks now and everything has been working great for me so far, thanks for making this, it's very stable and the documentation is great !

There are a couple of features that I would love to see implemented. The issue is that some of these apparently aren't easily doable because of limitations on Bitwig's part, (e.g Being able to properly select Drum Machine chains, mute them, control their sends individually, access their devices seems to be an issue) 
In order to keep this orderly I will make separate threads for each feature, starting with the smallest/simplest ones

----------------------------------------------------------------------------------------------------
[SELECTING CLIPS]

It seems that in order to display and edit a clip in drum sequencer mode, you need to select both the clip and the track that contains it. Selecting the track isn't a problem in "Session" mode, however, there seems to be no way to select specific clips (on my Launchpad at least)

Currently, there are, as far I can tell, two main ways to select clips in bitwig

-Click on them (Obviously not ideal for live editing and kinda gross imho)
-Press "l" (small L) to focus on the "launcher" interface and navigate using arrows (up/down to select clips, left/right to select tracks)

One way to solve this I can think of would be to have The "Up" and "Down" buttons ("Next/Prev Group")in session modes have an alternate "Next/Prev Clip" mode that would be toggled in the "Shift" menu, for instance,

That way you could have a similar "up/down to select clips, left/right to select tracks" thing going in session mode, without losing the "Group" navigation, pretty sweet !

**Comment by git-moss** [comment]
With upcoming DBM 10.5 you can now long press a clip to only select it.
