### ISSUE TITLE
[Feature request] Loop region // Step by Step - Finer setting (not only bars)

### ISSUE THREAD

**Issue by gnzgg** [git-moss/DrivenByMoss#198]
(Novation Launchpad mini MkIII // Bitwig)
This is my second feature request thread: https://github.com/git-moss/DrivenByMoss/issues/197
This one might be a slightly confusing read, Imma get coffee and edit it in a couple hours to make it a little more readable :)

-----------------------------------------
[Loop region // Step by Step]

It would be great if there was a way to have controls on a clip's loop region, for polymetric loops, breaks, fills and all kinds of fun stuff !

Currently this can be done on a "page by page" basis using the SEQUENCER PAGE function in sequencer mode
What I'm thinking of would be a way to do it on a "step by step" basis, in order to let you easily make shorter loops, including odd time divisions

One way to implement this feature would be to create a new playmode that would essentially extend the "Sequencer page" type of controls (Select start/end point) to the entire 8x8 step by step grid and would include the "SEQ. NOTE RESOLUTION" controls 
That way you get a pretty nice "Select start/end step" function, that would be very similar to the "select start/end page" function

Obviously asking for a new playmode might be kind of a big thing, but it is the simplest way I can think of off the top of my head

**Comment by git-moss** [comment]
Thought about this for a while but do not see how to integrate this in a usable way.
