### ISSUE TITLE
[Feature request] More complex stuff

### ISSUE THREAD

**Issue by gnzgg** [git-moss/DrivenByMoss#199]
(Novation Launchpad mini MkIII // Bitwig)
Third thread in my "Feature request" trilogy ! https://github.com/git-moss/DrivenByMoss/issues/197
I still have a couple more feature request threads I'd like to write but in order to do so I need to be able to sort which feature is  doable and which isn't, so I'm going to mention all of them briefly here and if one of these turns out to be doable, I'll make a specific thread going in more detail

By the way sorry if I'm flooding your issue page, I'm trying to be as constructive as possible but I understand that posting several threads in a row can be kinda annoying, hope this isn't too much of a problem :)

--------------------------------------

DRUM MACHINE CONTROLS AND NAVIGATION
The Drum machine device has some really annoying inconsistencies when it comes to navigation which make it essentially impossible to navigate without using the mouse (eww). This clearly an issue with bitwig and I don't know that it would be possible to solve it here

Of course this is really annoying because being able to properly select a Drum Machine's chain would allow all kind of stuff, like chain mute/solo, sends and devices control
As it stands, the "device select" and "control pages" function are kinda broken when working with the Drum Machine, but I can't think of a way to fix it without fixing Bitwig itself

One thing I can think of is using the Drum Machine's "Fold/Unfold" function (2 arrows pointing downwards in Bitwig's "Mix" mode to select each chain in "Session mode" but I don't know if it's doable currently

------------------------------------------------------------------------------

STEP BY STEP EDITING

Another set of features that seems kinda problematic to implement but absolutely essential in my opinion relate to step by step editing: (partly mentionned here https://github.com/git-moss/DrivenByMoss/issues/19)

There should be a way to select a specific step in a sequence for more precise editing, with controls like:
-Micro-timing (offsetting a step forward of backward by a very small amount)
-Velocity control
-Pitch control 
etc

---------------------------------------------------------------------------

INPUT VELOCITY:

Note input in sequencer mode is velocity sensitive, which is great. However, this requires a velocity sensitive controller (Which isn't the case for the Launchpad mini mkIII unfortunately :/ ).
One way to work around this would be to have an "input velocity" parameter, that could be set through the "shift" menu, for instance (similar to "volume" or "pan" control)
Another way would be to have a Velocity/Resolution toggle which switches the right-hand column between the current "Seq. Note Resolution" controls to "Input Velocity", so that you could set the input velocity without having to switch screen, which would be great in terms of workflow

However I don't know that this is doable currently and, to be fair, this is only really a problem for velocity-insensitve controllers which makes it a pretty low priority feature but I guess it's worth mentionning

Anyway, this all I can think of right now, so I'm going to stop flooding for now :)

**Comment by git-moss** [comment]
1) DRUM MACHINE CONTROLS AND NAVIGATION
I am afraid this can't be improved right now, also such navigation is problematic without a display.

2) STEP BY STEP EDITING
I support that on several controllers but I am not sure if this makes much sense on the Launchpad since you would constantly need to toggle between two modes.

3) INPUT VELOCITY
Also something I already did for many controllers, could be added.

**Comment by gnzgg** [comment]
Thanks for answering, I guess I didn't really consider the fact that the launchpad is a comparatively limited controller (next to an ableton push or a maschine for instance), I'll take the time to read the documentation for other controllers to avoid confusion :)
