### ISSUE TITLE
[Feature request] Scale 50% / 200%

### ISSUE THREAD

**Issue by gnzgg** [git-moss/DrivenByMoss#200]
Hi again (again) !
I said I would stop flooding in https://github.com/git-moss/DrivenByMoss/issues/199 and I meant it, but this is a very small and very cool feature and probably the easiest one to implement so far, so I thought it deserved its own thread

---------------------------------------

When right-clicking a clip, you can select "Scale 50%" and "Scale 200%" to scale the clip, very useful ! 
It would be great to have a control for this, perhaps through the shift menu (similar to "Delete active" where you first press "scale up" or "down" to activate it and then select a clip in session mode)

Here's a short and silly example, because why not ! :) 
https://youtu.be/05C_e306Xkc

No more flooding from this point on, this time for real !

**Comment by git-moss** [comment]
In general a good idea but the especially the Laucnhpad is already crammed with so many functions (incl. the Shift menu), I do not want to add more.
