### ISSUE TITLE
Akai Fire, Bitwig 3.2.6, Note Mode

### ISSUE THREAD

**Issue by barrysims** [git-moss/DrivenByMoss#201]
Scenario: 
I'm in drum4 view, I have a pattern in place.  I want to check the velocity (or pan, etc) of a note.  I touch the corresponding knob.

Expected: 
The velocity is displayed and the note stays lit

Actual:
The velocity is displayed but the note is turned off

I have a PR to fix this, but I need permissions to commit to a branch for PR.

Thanks!

**Comment by git-moss** [comment]
Thanks for reporting, will be fixed in the next update.

You can always send change requests, no need to for commit access.
