### ISSUE TITLE
Push 2: Powering off device crashes Bitwig

### ISSUE THREAD

**Issue by Funkatronics** [git-moss/DrivenByMoss#202]
Title says it all. If you are using the Push 2 with Bitwig and turn off the Push while Bitwig is open, Bigwig immediately crashes. 

Using DrivenByMoss 10.6.4 and Bitwig 3.2.7

**Comment by git-moss** [comment]
Yes, I am aware of the issue. The display sending process is now in its own thread to make Push more responsive. This can cause the crash if the sending is happening when you turn it off, not sure if this is fixable.

**Comment by Funkatronics** [comment]
I see. Well that's a bummer but not a huge deal. I'll report the issue to Bitwig support, maybe they could implement something to catch the error instead of crashing. Thanks!

**Comment by git-moss** [comment]
Fixed since 10.7.0.
