### ISSUE TITLE
APC40: User page mapping is inconsistent

### ISSUE THREAD

**Issue by mcristi** [git-moss/DrivenByMoss#205]
### Current mappings
Changing sends: 
- hold `Sends` + press `Track Select 1-8` to select the sends 1 to 8.

Change user page: 
- `Cursor right` - Move to next user page
- `Cursor left` - Move to previous user page

### Proposed mapping
Change user page mapping to 
- hold `User` + press `Track Select 1-8` to select user page 1 to 8.

Arguments for the new mapping: 
- to have consistent mapping 
- moving track bank with 1 track (`Cursor right`/`Cursor left`) is overlapping

**Comment by git-moss** [comment]
I like the idea. Will be in the next update.
