### ISSUE TITLE
Serum doesn't react to mod wheel

### ISSUE THREAD

**Issue by izhargo** [git-moss/DrivenByMoss#206]
I'm using NI Komplete Kontrol A61, bitwig 3.1.3 and DrivenByMoss-8.98-Bitwig. 
When using Serum plugin - it doesn't react to mod wheel at all.

**Comment by git-moss** [comment]
I am sorry but I can only support the latest release (but there was non change in that area). I tested with that and it works fine. But I do not have Serum, so it could also be that there is a problem with Serum. Do you have another keyboard to test?
