### ISSUE TITLE
APC40 mk2: Pressing Shift and moving Volume Fader to match the current value no longer working

### ISSUE THREAD

**Issue by mcristi** [git-moss/DrivenByMoss#208]

**Comment by git-moss** [comment]
Yes, that was intentional to clean up some code. I am surprised that someone actually uses that :-) Please use the default Bitwig "Takeover mode" setting on the controller page instead.

**Comment by mcristi** [comment]
It was really useful during jams :) Did not know about the "Takeover mode", it looks to be almost the same. Thanks 😎

**Comment by mcristi** [comment]
Turning knobs in "takeover mode" of any VST page is lagging a lot (not changing smoothly the value). This is not happening with native Bitwig devices. Initially, I supposed it is a Bitwig bug, but I checked the Bitwig's script and it is not reproducible.
