### ISSUE TITLE
APC40 mk2: Turning knobs in takeover mode of any VST page is not changing smoothly the value

### ISSUE THREAD

**Issue by mcristi** [git-moss/DrivenByMoss#210]
Turning knobs very fast will lag the value behind and prevent having a filter sweep. 
This is not happening with native Bitwig devices.
Initially, I supposed it is a Bitwig bug, but I checked the Bitwig's script and it is not reproducible.

**Comment by git-moss** [comment]
I can reproduce that but only in Catch mode. Did you try Relative Scaling mode?
Will report it to Bitwig.

**Comment by git-moss** [comment]
OK, the trick is to understand that these knobs act like motor faders and catch-mode can be disabled for the knobs.
Will do that in the next update!

**Comment by mcristi** [comment]
> I can reproduce that but only in Catch mode. Did you try Relative Scaling mode?

Indeed only Catch mode behaves this way. 

> Will do that in the next update!

🥳🙇🏻‍♂️
