### ISSUE TITLE
APC40 mk2: Add device and bank navigation led feedback

### ISSUE THREAD

**Issue by mcristi** [git-moss/DrivenByMoss#212]
- light left device led (1) when there is a device on the left of the selected device
- light right device led (2) when there is a device on the right of the selected device
- light left bank led (3) when there is a page to scroll left 
- light right bank led (4) when there is a page to scroll right

This is the behavior in Bitwig's default script and I believe it is really useful, giving you another reason to avoid looking to the DAW.

**Comment by git-moss** [comment]
Yes, will be added in the next update.

**Comment by mcristi** [comment]
Great 🎉 Thank you for all your work!
