### ISSUE TITLE
XCtl Support

### ISSUE THREAD

**Issue by dronenb** [git-moss/DrivenByMoss#213]
I think this project is excellent. One thing I think would be super cool would be to implement XCtl support for Behringer's XTouch product line. Although you can use the XTouch devices in MCU or HUI mode, the XCtl mode has the added benefit of supporting color scribble strips. Additionally, it can be done over MIDI (via a MIDI interface, not via USB unfortunately) or via the network. [This project](https://github.com/pythag/x-touch-xctl) is an implementation of the XCtl protocol in C++ over the network. [This document](http://www.budgetfeatures.com/XctlDOC/Xctl%20Protocol%20for%20X-Touch%20V1.0.pdf) outlines the XCtl MIDI protocol.

**Comment by git-moss** [comment]
Thanks for the interesting info. I only have the X-Touch One, which I think is sufficently supported by MCU and have no plans to get any of the other models.

**Comment by ri0t** [comment]
I just received a full XTouch, it generally seems to work quite well, although i yet have to understand how everything works.

Is there any chance to add color to the channel strip display(s) though? Those allowing colors are one of the main reasons i didn't go for the smaller version, it just helps so much with the way BWS embraces colors in the workflow.

The XTouch One should allow for colors, as well.

OP's comment seems to indicate that fiddling with midi sysex messages is required (don't know if that's a problem) and the xctl protocol document seems to imply that there are only 7 available colors.. a bit sad, but it would be better than nothing.

**Comment by git-moss** [comment]
I was not aware that the One does support colors as well. I just did a test and it really does. BUT it only works in MIDI mode (not MCU). The MIDI mode instead has the limitation that the fader has only a 7-bit resolution (instead of 14-bit in MCU mode). This seems to be different on the big version; I made another attempt to get one, lets see...
