### ISSUE TITLE
APC40 mk2: Launching any scene also selects the track with the selected clip

### ISSUE THREAD

**Issue by mcristi** [git-moss/DrivenByMoss#214]
This is happening using the latest code from master.

**Comment by git-moss** [comment]
I cannot reproduce that. Could you please give steps to reproduce or make a video?

**Comment by mcristi** [comment]
Hi Moss, 

I have an empty project with 3 tracks and 2 scenes. When I select a clip with a long press, the clip is selected and the track is also selected. All good.
Then I select another track for doing other stuff, use the device control knobs for instance.
Now when I launch any scene the track is changed to the track of the previously selected clip.
Here is a video to show you this behaviour: https://drive.google.com/file/d/14d3h_zsZcsFb8t37J4-mOoCY9kSflj6_/view

Thanks a lot again for your effort 💪🏼

**Comment by git-moss** [comment]
Turn off "Select tracks when ... Selecting Clips in Clip Launcher" in the Bitwig settings on the Behavior page.

**Comment by mcristi** [comment]
Damn, that was something I missed from Bigwig’s settings. Thanks for solving this for me 🤘🏻
