### ISSUE TITLE
DrivenByMoss creating infinite launch clips?

### ISSUE THREAD

**Issue by giacecco** [git-moss/DrivenByMoss#215]
I'm running DrivenByMoss 10.7.4 and Bitwig 3.2.8 on macOS.

This is something strange that has started happening to me since a few days ago. I turn on the Push 2, launch Bitwig, open a project and immediately "something" creates as many clips as possible in the selected track, until all scenes of that track are full and I get an error message saying "No empty slot in the current page. Please scroll down." If I delete the clips, they are populated again, until I turn the Push off.

I presume that the matter is related to DrivenByMoss because it is associated to the Push. Also, I guess that it may be related to rogue MIDI signals being received and interpreted by Push :-) I've read Moss' documentation [here](https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Ableton/Ableton-Push.md) but found nothing that gave me ideas. 

Any suggestions or check you'd like me to do? Thanks.

**Comment by git-moss** [comment]
Sounds like the "New" button on the Push is somehow stuck. Maybe simply connect it to a MIDI monitor to check.

**Comment by giacecco** [comment]
@git-moss you're correct, next time the issue happened I could see the light of the "new" button receiving a burst of activations, so one of my devices must be sending "new signals" to it.

I've searched for references to MIDI in the documentation to see how to configure the Push differently. The only references I found are, in [the Push documentation](https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Ableton/Ableton-Push.md): 

> To add the controller manually, choose Ableton -> Push or Ableton -> Push 2 depending on your specific controller. On Push 1 make sure that for MIDI in- and output the 2nd port is selected (MIDIIN2 (Ableton Push) and MIDIOUT2 (Ableton Push) on Windows). For Push 2 it is the first port.

... but that seems to refer to the non-USB ports. Also in [the general installation documentation](https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Installation.md) there are some MIDI references but they seem to apply to Reaper only.

I've also looked into the configuration of DrivenByMoss within Bitwig and there are no references to USB.

Any suggestions?

**Comment by git-moss** [comment]
I was thinking more in the direction of a hardware defect. Have you checked the device with a simple MIDI viewer?
Even if you send MIDI to the device it does not trigger to repeat it through the output (at least I do not know how that could happen).

**Comment by giacecco** [comment]
The issue did not happen any more, it must have been a glitch.

**Comment by giacecco** [comment]
@git-moss hope you can give me advice, the issue has restarted and is systematic now. With MIDI Monitor, and filtering out everything but the Push 2, I see a series of:

```
10:34:39.166	From Live Port	Active Sense		
10:34:39.166	From User Port	Active Sense		
10:34:39.180	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 38 6A 00 70 00 75 00 58 00 F7
10:34:39.198	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 39 08 01 05 01 1D 01 59 00 F7
10:34:39.232	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 3A 6C 00 6A 00 75 00 5A 00 F7
10:34:39.250	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 3B 1D 01 05 01 1C 01 5A 00 F7
10:34:39.279	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 3C 74 00 6A 00 74 00 5B 00 F7
10:34:39.296	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 3D 1C 01 1D 01 05 01 5B 00 F7
10:34:39.331	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 3E 74 00 75 00 6A 00 5C 00 F7
10:34:39.348	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 3F 1D 01 04 01 04 01 5C 00 F7
10:34:39.383	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 40 75 00 6A 00 6A 00 5D 00 F7
10:34:39.401	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 41 66 00 19 00 14 00 5D 00 F7
10:34:39.430	From Live Port	SysEx		Ableton 17 bytes	F0 00 21 1D 01 01 04 42 21 00 08 00 06 00 5E 00 F7
```

The first ```F0 00 21 1D 01 01 04``` part and how it ends in ```00 F7" is always the same, the rest changes. They are occasionally interrupted by random

```
10:34:38.583	From Live Port	Control	1	Hold 2 Pedal	0
10:34:38.586	From Live Port	Control	1	Hold 2 Pedal	127
```

... sometime together, sometimes not. Would you confirm your intuition, that this is a hardware problem? Thanks.

**Comment by git-moss** [comment]
These are the color messages, nothing to worry about.

**Comment by giacecco** [comment]
Thanks @git-moss , I've realised that the Push was still under a 3 yrs warranty and I simply sent it back for replacement before it was too late.
