### ISSUE TITLE
Bitwig Controller Features ?

### ISSUE THREAD

**Issue by daslicht** [git-moss/DrivenByMoss#217]
Does the  MCU also have a EDIT PLUGIN layer where you can freely assign controllers per device and controllers per preset (as with the  FaderPort 16 extension) ?
Hidden Tracks should  **not be shown** on the Controller.
When we have a Group Track (Drum Rack) and expand the Group , the nested tracks  should be controllable form the  controller. I we collapse the group the track should be hidden from the controller.

Is that already possible with any Controller ?

I currently have a FaderPort 16 but the Bitwig implementation is a bit buggy and miss most features above

**Comment by git-moss** [comment]
1) Currently not, can put it on the wishlist.
2) Not possible. Send the wish to Bitwig.
3) Dito.

**Comment by daslicht** [comment]
> Hidden Tracks should **not be shown** on the Controller.

lil' workaround, but hidden and bounced  track in a group :)

**Comment by git-moss** [comment]
You can also deactivate the track and enable to hide deactivated tracks in the settings.

**Comment by daslicht** [comment]
Any change on this behaviour?

**Comment by daslicht** [comment]
Any news on this ?

**Comment by git-moss** [comment]
Since DrivenByMoss 16.4.0 you can edit drum channels. See here: https://www.youtube.com/watch?v=JOlhQ-fXh2U

**Comment by daslicht** [comment]
awesome !

**Comment by daslicht** [comment]
> Since DrivenByMoss 16.4.0 you can edit drum channels. See here: https://www.youtube.com/watch?v=JOlhQ-fXh2U

I have tried it but when I press teh select button again, all faders get deactivated. Whern I move them up they just jump down as when the unit is disconnected. 
Any idea what coudl be wrong? 
please?

**Comment by daslicht** [comment]
I figured out what was wrong !
the Extender Seup was wrong ! now it works ! <3
