### ISSUE TITLE
Recording audio

### ISSUE THREAD

**Issue by d3vMode** [git-moss/DrivenByMoss#218]
Hi, 

I'm trying to do live looping within bitwig and an ableton push 1. Do you know by any chance if there is a way when you create a new empty clip with a specific length to record audio into that clip on the fly? 
If it's not possible do you know if there's a way to start recording a clip with the sustain pedal? I can't seem to find a way to do that in the settings and I really like to use my pedal to trigger a new slot recording. Thanks.

**Comment by git-moss** [comment]
I think the first is not possible but maybe ask Bitwig support what they suggest.

For the 2nd footswitch you can choose "clip based looper", which could be what you are looking for.
