### ISSUE TITLE
APC40 mk2: After script start-up button colours states are not initialised

### ISSUE THREAD

**Issue by mcristi** [git-moss/DrivenByMoss#220]
Steps to reproduce:

1.1 Create an empty project, add multiple tracks
1.2 Mute, arm, solo and A|B tracks randomly
- colours are updated accordingly

2.1. Restart controller
- none of the buttons colours are updated according to the project state

2.2 If Shift is pressed and released the clips/note grid, selected track and mute buttons are updated correctly
- A|B, record and solo buttons are not updated accordingly 

Even if the controller is opened before Bitwig, when opening projects sometimes the mute/arm/A|B LEDs are inconsistent.

**Comment by git-moss** [comment]
Could you please add your OS?

**Comment by mcristi** [comment]
MacOS 11.0.1
Bitwig 3.3

**Comment by git-moss** [comment]
This seems to be an issue with Bitwig on Macos 11. I added a workaround which flushes all controls 10 seconds after startups, which such fix the issue.

**Comment by mcristi** [comment]
Thanks for the quick answer and fix! 🤩
