### ISSUE TITLE
APC40 mkI: (Built from master) Selecting a new track shows selected grid mode from previous track

### ISSUE THREAD

**Issue by meburton** [git-moss/DrivenByMoss#222]
When building from the current master branch and using a grid mode other than session, selecting a new track shows the grid mode that was selected for the previous track.

Using the prebuilt current release or reverting to 2c862d8ba8c6fb854b198905d0665b1795d1c80d and rebuilding resolves the issue so I believe the most recent commit 80b05ded543f2d5bdffe2b185ce13ac697d8021e introduced the issue, but I haven't investigated further than that.

I haven't checked if this affects other devices.

Repro steps:
Start with an empty project
Add three instrument tracks
Add an empty clip to each track
Switch to track 1 and activate the note pads
Switch to track 2 and activate the drum sequencer
Switch to track 3 and activate the poly sequencer
Switch to track 1 and observe that the poly sequencer mode is still shown
Switch to track 2 and observe that the note pads mode is shown
Switch to track 3 and observe that the drum sequencer mode is shown

**Comment by git-moss** [comment]
Thanks for the report! This prevented a difficult bug to sneak in the next update!

P.S.: The change is checked in but I falsely linked your other report in the comment.
