### ISSUE TITLE
CC control from OSC

### ISSUE THREAD

**Issue by electrypnose** [git-moss/DrivenByMoss#224]
Hello there, new here :)

Been working on a launchpad layout to control Bitwig, using Open Stage Control and Drivenbymoss script, working pretty well !!
I'm missing something to be able to add CC controls to my template that could be mapped to parameters in BW.

This command wouldn't work here : /vkb_midi/{Channel:1-16}/cc/{CC:0-127}

And according to this old topic it's maybe normal since it would be to apply specific CC values to a dedicated VST maybe ?
https://github.com/git-moss/DrivenByMoss/issues/119

But I don't know how to achieve what I want then.. How could I assign a knob to a VST parameter ?
Thanks for your help !

**Comment by git-moss** [comment]
That's what the /user/... messages are for. They have the advantage that you get the parameter descriptions as well instead of only CC.

**Comment by electrypnose** [comment]
got it !! Thanks, sorry that it wasn't clear for my beginner's vision.
