### ISSUE TITLE
[Launchpad Mini Mk3] Tap Tempo seemingly does not work

### ISSUE THREAD

**Issue by lierdakil** [git-moss/DrivenByMoss#226]
Hello. First of all, thank you for the amazing software! I'm running into a small problem though. I have Novation Launchpad Mini, and everything seems to work _except_ tap tempo feature. Shift (i.e. User) + Tap Tempo doesn't affect the tempo. The OSD of "Tap Tempo" appears on screen though.

Software:
- DrivenByMoss 11.5.0
- BitwigStudio 3.3.1
- Linux

Terribly sorry if I'm missing something obvious. Let me know if I can help debug this.

**Comment by git-moss** [comment]
Thanks for reporting! Will be fixed in the next update.
