### ISSUE TITLE
Launchpad Mk1 / MkI support

### ISSUE THREAD

**Issue by goncalopp** [git-moss/DrivenByMoss#228]
Are there any plans to support the Novation Launchpad Mk1 in the future?
Would patches be welcome? How much help / support could potential developers expect?

Thanks for your excellent work supporting the Bitwig community Moss, your code has made our lives so much better

**Comment by git-moss** [comment]
There are no plans. I had the device when it was released and it has quite some latency (also with pad LEDs). I would not suggest to use it nowadays.

I cannot support much, since this keeps me already too busy :-)
