### ISSUE TITLE
Launchpad MK2 Stucks

### ISSUE THREAD

**Issue by gguney** [git-moss/DrivenByMoss#230]
I'm trying to use Launchpad MK2 with this script,

However, when I try to change drum or sequencer pattern it stucks and pads flashes/blinks like %1 brightness and It doesn't show any sign of sequencer etc.

When I press the User 1 button "Drum" shows up in my screen but in launchpad area there is nothing.

I think it stucks and I couldn't find a way to reset it without quitting the app. I even tried to remove cable and start it again but no luck.

After few minutes it returns to normal.

**Comment by git-moss** [comment]
Sorry, I somehow did not get notified about your issue. Is it still relevant with latest DrivenByMoss 11.7?
