### ISSUE TITLE
MAudio Axiom Pro

### ISSUE THREAD

**Issue by Frikazoid** [git-moss/DrivenByMoss#231]
Hello,
I have an MAudio Axiom Pro, and I'm also a Java programmer.
Where should I start to look if want to try to add this controller?
Trying to get some Midi/SysEx data from mi keyboard through many tries?
Thank you!

**Comment by git-moss** [comment]
Hi,
you can give the Generic Flexi a shot which should keep you going with the device.

If you love coding for the sake of it, check out my Bitwig development series on my Youtube channel:

https://www.youtube.com/watch?v=l4AuiQ8krQc&list=PLqRWeSPiYQ66KBGONBenPv1O3luQCFQR2
