### ISSUE TITLE
Maschine Mk3 changes & Atom SQ Support

### ISSUE THREAD

**Issue by gguney** [git-moss/DrivenByMoss#232]
Hello, 
I just trying to switch to Bitwig and found your scripts. I'm using bitwig and studio one but thinking to switch to bitwig. Thanks for all of your scripts. 

Before I asked few questions but I found solutions. 
For Maschine MK3 is there way to shorten the messages on the screen of maschine? For example when change the plugin, it stays quite long, I think. 

For Atom SQ. Is there a plan for it? It has screen and it has encoders. Also with its pad it is nice sequencer like elektron or roland style. It has so much potential but Presonus did not update it for few months and I'm really sad about it because the lack of software support is holding this hardware back.

Thanks for the scripts again

**Comment by git-moss** [comment]
Sorry, there is no option to change the delay time.

I have no plans to support the Atom SQ. While it looks interesting, the possibilities to program it are very limited (I looked into it some time ago).
