### ISSUE TITLE
bug: Push crashes on Bitwig's "Polynom" modulator

### ISSUE THREAD

**Issue by mattly** [git-moss/DrivenByMoss#233]
if I have a device open and active on my Push2, and add a "Polynom" modulator, the Push controller will crash, and I have to quit and relaunch Bitwig before it will work again.

**Comment by git-moss** [comment]
I cannot reproduce that. Can you please give some exact steps what you are doing? Also please check if there is an exception in the JavaScript console (accessible from the studio pane on the right). If yes, please post it as well.

**Comment by mattly** [comment]
Digging a bit deeper, I'm not sure this is a problem with the DrivenByMoss script as it is a larger problem with my Bitwig setup. I've only ever _noticed_ it when attempting to create a polynom modulator but I'm going to close this for now. Sorry for the alarm.

**Comment by mattly** [comment]
Since my push is really the only midi controller I use while playing with modulators, I never noticed this, but something with Polynom and another modular that displays phase info such as the LFO or Vibrato mod (but not an envelope) will cause my Bitwig install's MIDI input engine to seize up entirely. No midi inputs work. I'll take this up with Bitwig. Sorry for the false alarm
