### ISSUE TITLE
request: option to turn on Push's text button lights

### ISSUE THREAD

**Issue by mattly** [git-moss/DrivenByMoss#234]
I would really like to be able to turn on all the lights for the text buttons on my Push2 (akin to how it works in Live), so I know what they do.

**Comment by git-moss** [comment]
This issue was raised by 2 people in the KVR thread. I only see that behaviour on my device when there is no power connected. I checked the Push documentation several times as well as the Ableton script but have no idea what Ableton is doing differently.

**Comment by mattly** [comment]
ooof, I haven't been on KVR in over a decade... I'm... surprised that's still around

Anyway, I got my unit used without a power adapter, had never tried  plugging it in; and indeed not only do the lights work but they're much brighter. Thanks!
