### ISSUE TITLE
clip and track stop OSC methods not recognized by Bitwig

### ISSUE THREAD

**Issue by giohappy** [git-moss/DrivenByMoss#236]
Looking at the code of the OSC controller it seems that stopping a clip [is supported](https://github.com/git-moss/DrivenByMoss/blob/master/src/main/java/de/mossgrabers/controller/osc/module/ClipModule.java#L84). I'm trying to use it with `/track/{n}/clip/{n}/stop` but Bitwig returns the following log:

```
Receiving: /track/1/clip/1/stop [ 1 ]
Unknown OSC command: /track/1/clip/1/stop stop
```

I've also tried the [track stop method](https://github.com/git-moss/DrivenByMoss/blob/master/src/main/java/de/mossgrabers/controller/osc/module/TrackModule.java#L273) with `/track/{n}/stop` but I get Unknown command also in this case.

What am I doing wrong?
Bitwig 3.3.3 with [DrivenByMoss 11.6.1](http://www.mossgrabers.de/Software/Bitwig/Bitwig.html#3.2)

**Comment by git-moss** [comment]
The command is: /track/{1-8}/clip/stop
So, no need to add a clip number since there can be only 1 playing clip which can be stopped.

**Comment by giohappy** [comment]
thanks @git-moss.
Just a curiosity, reading the code I don't understand which commands expect the clip number and which don't. Where does the parser extracts the clip number when, for example, `/track/{n}/clip/{n}/launch` is triggered?

**Comment by git-moss** [comment]
There is no need to look into the code. The DrivenByMoss contains a manual which explains all available commands.

**Comment by giohappy** [comment]
Well, probably I missed those pages, but it wasn't my point. In the spirit of OS sw (I'm also a developer in the open source arena) my question was about the code, and I admit I'm a bit surprised by such an answer.

Thanks anyway for sharing your work :)
