### ISSUE TITLE
Launchpad pro MK3 / Bitwig - add a way to use the polysequencer with a keyboard

### ISSUE THREAD

**Issue by mikefaille** [git-moss/DrivenByMoss#237]
Using the Launchpad pro mk3 + DrivenByMoss there is a way to use the polysequencer with a Keyboard + Bitwig ? 
As example, if I know a chord using a keyboard, I want to sequence using the polyphonic sequencer from the Launchpad.

I tried : 
- plug my Keyboard midi out to the Midi in on the Lauchpad. On the launchpad, when I send midi notes from the Keyboard, it only remove lights on touches with the same midi code but my launchpad doesn't send midi out to the computer using the USB connection
- plug the keyboard midi out directly on the computer. Bitwig can send the touch press from my keyboard to my Lauchpad as the related touch on the Launchpad change his color like if the Launchpad is able to receive a note/chord. But, the launch pad is not able to register the note/chord as step on the polyphonic sequencer. 

Thanks for you work !

**Comment by git-moss** [comment]
I am sorry but there is no interaction between the different extensions. You would need to write a specific extension (script) for such a purpose.
