### ISSUE TITLE
Launchpad pro mk3 - The aftertouch is partially working.

### ISSUE THREAD

**Issue by mikefaille** [git-moss/DrivenByMoss#238]
Hi Moss (or any contributor).

The Aftertouch in note mode only work when I hit 2 notes at the time.
I could confirm it visually on the modulator `expressions`,  I could see if the `pressure` (representing the aftertouch) turning from blue to white the expression is working.
And, if I change the pressure on one key at the time, the Aftertouch never work at all.

If I press 2 keys at the time, the Aftertouch works but not always. 

If I monitor the midi protocol coming out my Launchpad, I could see there is pressure/aftertouch data commit out even from a single key.

Thank you for work !

**Comment by git-moss** [comment]
Thanks for reporting. Will be fixed in the next update.
