### ISSUE TITLE
Spurious `ICMP Port Unreachable` error

### ISSUE THREAD

**Issue by ssssam** [git-moss/DrivenByMoss#240]
Using [Protokol](https://hexler.net/protokol) on Linux and TouchOSC 1.9.11.16 on Android, I can connect phone to computer successfully and send OSC messages. The computer appears in TouchOSC's 'Found hosts' list when Protokol is running.

When I run Bitwig 3.3.7 with DrivenByMoss 11.7.3, the computer doesn't show in the TouchOSC 'Found hosts' list and I see these errors in Bitwig console output after adding the OSC control point:

```
java.net.PortUnreachableException: ICMP Port Unreachable
	at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(Unknown Source)
	at java.base/java.net.DatagramSocket.receive(Unknown Source)
	at com.bitwig.flt.control_surface.opensoundcontrol.puf.nyW(SourceFile:60)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Do you have any idea what my next steps would be to debug this ? The bitwig-studio process is run with same privilege as Protokol. I don't see how this could be caused by a real network error when TouchOSC is able to connect to Protokol, but I don't know much about how it works.

**Comment by git-moss** [comment]
Sorry, no idea. Network debugging is not really my area of expertise. Maybe you can try your luck with Bitwig support.

**Comment by ssssam** [comment]
OK, thanks for the reply. So the com.bitwig.flt.control_surface.opensoundcontrol.puf.nyW error comes from Bitwig itself, not the extension?

In that case, I will see if Bitwig support can help, and I will try to test on a different network. In the meantime, I am using VNC to control Bitwig.

Thanks a lot for making the plugin!
