### ISSUE TITLE
Bitwig : Novation 61SLIII MK3 is not autodetected under Ubuntu 21.04

### ISSUE THREAD

**Issue by mikefaille** [git-moss/DrivenByMoss#241]
The automatic detection of the Launchpad Pro MK3 works very well under Ubuntu 21.04 but it doesn't work for the Novation 61SLIII MK3.

I also tried manual configuration but the midi input to configure the device doesn't work. (the manual configuration works perfectly for the Launchpad Pro MK3). The midi output for the device works under manual configuration but only with the default midi template as there is no Bitwig's automatic configuration working. 

The firmware version is : 384
The boot loader version is : 104
Bitwig version : 3.3.7
![Screenshot from 2021-04-18 23-08-03](https://user-images.githubusercontent.com/978196/115176350-f4f47000-a09a-11eb-94af-e6310a48e290.png)

**Comment by git-moss** [comment]
Just tried it on Ubuntu and it works fine. Are you aware that you need to press the "INCONTROL" button on the SL?

BTW: Just fixed the names on Linux, so autodetect will work in the next update as well.

**Comment by mikefaille** [comment]
I was not aware about the Incontrol button. I don't know where and how I should do that. Maybe I need to read the manual 😁. Thanks, you are awesome !

Tell me how when you can please. In exchange I will update the guide on a PR.

**Comment by git-moss** [comment]
The INCONTROL buttono is on the left between the Global and Tempo button. You need to press it to enter DAW control mode. Toggling the button allows you to use both the features of my Bitwig implementation as well as the hardware features of the SL.
Will add it to the documentation.

**Comment by mikefaille** [comment]
Noted thanks !

**Comment by mikefaille** [comment]
It works perfectly !
