### ISSUE TITLE
Novation SL61 MK3 : I can't use the multi-zone feature

### ISSUE THREAD

**Issue by mikefaille** [git-moss/DrivenByMoss#243]
Again, thank you for the project.

Is it possible to enable the multizone feature for instruments in Bitwig ?

Actually, I want split my keyboard for multiple midi channels using the awesome feature called zone as showed here : https://www.youtube.com/watch?v=iruCtkliNUI&t=1647s

Actually, it seems the driver redirect all channel to the channel 1. But, to use one channel by instrument as supported by Bitwig input configuration, I would need the driver not redirecting all the channel to the channel 1.

I tested the SL61 MK3 using the generic midi driver and I can configure my channel by instrument by zone.

Thanks in advance for caring about this issue !

**Comment by git-moss** [comment]
This is already the case. Check the following:

1) Are you running the latest DrivenByMoss?
2) Zones are enabled with Shift+Zone (this confused me when testing it :-))
3) Check the destinations without zones
4) Check the inspector of the Bitwig track you are sending the data to. The default is to merge everything to MIDI channel 1!

**Comment by mikefaille** [comment]
1. I use the version : 11.7.3
2. It works on Ardour to send the channel 2 on the second instrument. The channel 2 representing the second zone (yellow keys). 
3. It doesn't work more.
4. On the device inspector, I see only to element : pad and keys for the keyboard. Normally, with driver provided by Bitwig, I see all midi channels. 

Note: My instruments are only Soft synths then my usage for instruments are to assign a zone to a channel then I need more than only the channel 1. Do you plan to support it ?

**Comment by git-moss** [comment]
Maybe I was not clear: the extension supports all MIDI channels sent from the SL, as you want it. I just tested it and it works fine.
Check your track settings in Bitwig it merges everything to MIDI channel 1 as the default! Change this to "Same":
![grafik](https://user-images.githubusercontent.com/3090132/115982442-55077c80-a59b-11eb-894a-e76affdde7e8.png)

**Comment by mikefaille** [comment]
Oh wow, it definitively work !
I learned to change the midi channel on the device selection menu !
I didn't saw the dedicated menu above. My bad, thanks for your great patience and support.
