### ISSUE TITLE
Akai Fire Step Pressure and Timbre support

### ISSUE THREAD

**Issue by etherealist** [git-moss/DrivenByMoss#244]
I'd like to set `pressure` and `timbre` with Akai Fire. My idea if `USER 1` is selected `gain` and `pan` are replaced by `pressure` and `timbre`.

I botched the feature here, this is terrible code, just to test if it is possible:

https://git.io/J3B9K

In fire/mode/NoteMode.java check if the previous mode was `DEVICE_PARAMS` and set `pressure` and `timbre`

**Comment by git-moss** [comment]
Thanks for the idea. Will add it to the wishlist.
