### ISSUE TITLE
Crashes Reaper with certain plugins

### ISSUE THREAD

**Issue by mknart** [git-moss/DrivenByMoss#247]
This took me a while to pinpoint what was going on. Long story short, DrivenByMoss with an Akai Fire makes certain VST plugs crash Reaper entirely, amongst others anything from the [Melda Productions free bundle](https://www.meldaproduction.com/MFreeFXBundle).

Verified on a fresh install with progressively adding items until Reaper crashes on said plugins and works again when the DrivenByMoss4Reaper config files are removed.

Windows 10 Pro, Reaper 6.28, DrivenByMoss4Reaper 11.7.3.

**Comment by git-moss** [comment]
Please see the known issues section in the manual.
