### ISSUE TITLE
Touch OSC device param going to 0 after release on IPad

### ISSUE THREAD

**Issue by jderiz** [git-moss/DrivenByMoss#250]
I have the OSC template setup with Bitwig 4 as of now, but the problem also occurred with all of 3.x. 

When in the Mixer page everything behaves nicely as it should, but when changing to the device page and editing a parameter, the parameter gets set to 0 when i release it on the ipad. Resetting it in the software gets mirrored correctly on the Ipad but changing it over the Ipad again sets it to zero (on the Ipad as well as in Bitwig) once i release it. 

So my guess was something goes wrong in the /device/param/x/ value endpoint which seems to be responsible both for sending and receiving values. Any guesses or Ideas where this behaviour results from are highly appreciated.

**Comment by git-moss** [comment]
Haven't used TouchOSC for quite some time. Could it be that there is a touch release event happening as well, which you might need to deactivate?

**Comment by jderiz** [comment]
Yep it was a Touch OSC App side setting! For potential readers in the same Situation: 
Touch Messages (/z) have to be disabled in the OSC Options on the Touch OSC App on the IPad. 
The Accelerometer (/accxyz) messages do not interfere.

Thank you jürgen, it really is great work that you do with the Framework!! I'll close this issue.
best regards, jannis
