### ISSUE TITLE
Ability to add longer notes in sequencer

### ISSUE THREAD

**Issue by eras** [git-moss/DrivenByMoss#251]
So today I discovered, with my LaunchKey Mini mk 3, that there's a step sequencer in this thing. Cool!

But I also noticed that it does not seem to be possible to add longer than one step notes to the sequencer, which I imagine is a typical limitation of these kind of sequencers—but it can sometimes be limiting, for example if the drum machine entry has a short release time, or longer notes are desirable for other reasons.

Here's an idea for entering longer notes: pressing multiple adjacent notes at the same time would enter a long note.

Removing a note from the sequence would then split the existing note.

Velocity could be min/max/avg/median from all the presses.

An alternative would be a mode where all notes would be rendered 'legato' to the clip while only displaying start steps in the device, but I imagine it would cause other problems (and it would need a setting to enable/disable).

**Comment by git-moss** [comment]
Will add it to my wishlilst.
