### ISSUE TITLE
Ability to adjust note operators in the sequencer

### ISSUE THREAD

**Issue by eras** [git-moss/DrivenByMoss#252]
I realize Bitwig 4 is still in beta, but it introduced the interesting feature of operators, which can really spice up some rhythms.

It could work simply by:
- hold down a step; if there is no note at that step, add one
- all knobs would be assigned to the operators section for the note
- release the step; if a knob has been adjusted, do not remove the step

Related idea: one knob could be used for finely adjusting the start time of the note.

Some other ways to implement this are probably feasible as well.

This way might be a conflict if there was to be the ability to adjust automation lane in the sequencer, which would be cool too, but I don't think it exists yet :thinking: .

In particular this would be most beneficial for the three note repetition parameters, but it's probably useful for other parameters as well.

**Comment by git-moss** [comment]
I already released a test version for Push 1 and Push 2 (Link is in the KVR forum thread, scroll a bit up).
I have some ideas how to implement it on the other devices as well but that may take a bit.
