### ISSUE TITLE
Fixed Length button to select clip Length on Launchpad Pro Mk3

### ISSUE THREAD

**Issue by alanzanattadev** [git-moss/DrivenByMoss#253]
Hi,

The button Fixed Length on Launchpad Pro Mk3 on Bitwig creates a new clip rather than replicating the Ableton behaviour: enabling the selection of Clip Length using tracks buttons.

I can't figure out how to actually change clip fixed Length using the controller and I came to the conclusion that it may be implemented like that by design.

I would find the clip length selection feature using the Fixed Length button very useful for live looping with the LPP mk3.

If you come to implement it, just change the "each track is a bar" as explained in the Launchpad Pro mk3 user guide to "each track is a math power 2" , such as the first button is 1 bar, the second 2 bars, the third 4 bars, the fourth 8 bars, the fifth 16 bars etc 😁 so we can easily reach 32 bars or more.

Best

**Comment by git-moss** [comment]
Good idea. Will add it to my TODO list.
