### ISSUE TITLE
Add "Sequent" mode to pad layout options

### ISSUE THREAD

**Issue by jgcook935** [git-moss/DrivenByMoss#254]
From the Ableton docs "The “Sequent” layout puts all notes sequentially in order. This layout is useful if you need a very large range of notes available, because it has no duplicated notes.". I tend to use this mode the most in Ableton so I can play scales without having overlapping notes. It'd be great if this feature could be added. If there are no plans to add it I think I'll take a stab at submitting a pull request. @git-moss Do you accept PRs?

**Comment by git-moss** [comment]
Are we talking Ableton Push?
You can activate Sequent layout by pressing Scale, then keep the Shift button pressed and select "Seqent".

**Comment by jgcook935** [comment]
Ahh, thanks Moss
