### ISSUE TITLE
Launchpad Pro MK3 - inconsistent stop clip behavior

### ISSUE THREAD

**Issue by yilin-zhang** [git-moss/DrivenByMoss#255]
Currently on Launchpad Pro MK3, there are three methods to stop clips:
1. Short click "Stop Click" to go into the stop click mode, press the track buttons in the bottom to stop clips, short click "Stop Click" to go back.
2. Press and hold "Stop Click" to temporarily go into the stop click mode, press the track buttons, release "Stop Click" to exit the stop click mode.
3. Press and hold "Stop Click" to temporarily go into the stop click mode, press the corresponding pads to stop the clips.

However, in method 3, when releasing "Stop Click", it doesn't exit the stop click mode.

I'm not sure if that's a bug, but it looks inconsistent to me. 

In addition, I think we should either completely allow the behavior of tapping pads to stop clips, or completely disable it. Specifically:
1. Disable the method 3, which means users can only trigger clips using pads instead of stopping clips.
2. Or add a new method, which allows users to short click to go the stop clip mode, and tap the pads to stop clips, rather than trigger the clips.

**Comment by git-moss** [comment]
> However, in method 3, when releasing "Stop Click", it doesn't exit the stop click mode.

I cannot reproduce that. Can you give more details in which mode you are, which buttons you press, etc.

**Comment by yilin-zhang** [comment]
> > However, in method 3, when releasing "Stop Click", it doesn't exit the stop click mode.
> 
> I cannot reproduce that. Can you give more details in which mode you are, which buttons you press, etc.

In Launchpad Session mode, while the clips are playing, press and hold "Stop Clip" button and tap the pad whose corresponding clip is playing, release "Stop Clip" button.

**Comment by git-moss** [comment]
Sorry, cannot reproduce your issue. Can you maybe do a video of what you are doing?

**Comment by yilin-zhang** [comment]
Here's the video: https://drive.google.com/file/d/1Y7REQg_td8ITT675g9690zIReChzYVTP/view?usp=sharing

Sorry that I wasn't able to shoot the whole Launchpad while holding the phone, but basically I was pressing the "Stop Clip" button until the clip was stopped.

**Comment by git-moss** [comment]
Ah, ok. You must not press the clip button but the button in the row above the "Stop Clip". They are lit in the same color as the "Stop Clip" button when you press it. Same for Mute, Solo and Rec Arm.

**Comment by yilin-zhang** [comment]
Yeah this is exactly the "method 1" that I wrote above. I know it's nitpicking since that's a corner case. I think typically people press an empty clip or "Stop Clip" + track button to stop the clip. It just feels a little inconsistent when users are trying to do so. It should be able to go back to the previous mode after the long press. Maybe this feature (tapping pads to stop clips) can be disabled, just like we can not solo the clip or track by pressing "Solo" then the pad.

Again, this is really nitpicking and might not be your priority. I just think it can be a nice little improvement :)
