### ISSUE TITLE
Bitwig 4.0 + LuanchKey Mini Mk3 MIDIOUT2 error

### ISSUE THREAD

**Issue by giohappy** [git-moss/DrivenByMoss#258]
After upgrading Bitwig and the extention (release 14.08.2021) I get the following error when I add the LuanchKey Mini Mk3 controller.

![image](https://user-images.githubusercontent.com/571129/131361816-02561492-bd24-4c44-83d3-61641b413014.png)

**Comment by git-moss** [comment]
This means that something has already opened the MIDI port(s) of the Launchkey.
First reboot your computer and try again.
If it fails again, check if you have any other tools running which accesses the MIDI port, e.g. Bome or MIDI-OX.

**Comment by giohappy** [comment]
I don't what was going but only after several plug / unplug and restarts of Bitwig it got back working.
Sorry for the noise.
