### ISSUE TITLE
sk mk2

### ISSUE THREAD

**Issue by AlexFundorin** [git-moss/DrivenByMoss#26]
Hi, Jurgen. I have a question about this controller.
What's the reason behind the following behaviour:
If some info was displayeв on the LCD, it would stay there, but only until any of the faders was moved or a button from one of the two rows on the right side is pressed. Then, "Automap is offline" is shown.
This doesn't happen if pressing any other button or touching any controls.
I've tried to inspect your script and Ableton one for the answer, but couldn't find anything.
Help, please.

**Comment by git-moss** [comment]
The idea to have only 1 display when the machine actually was designed for 2 displays (on the MkI) causes some strange effects. I tried to work around them as best as possible but sometimes you do not have an influence on what the hardware is doing.

**Comment by AlexFundorin** [comment]
Yeah. I realized yesterday that controller wasn't "offline" at all, all this time. It was just a message on the "right" screen that was showed when pressing any controls on the right side of the surface.
Should've get the old Remote 25 SL from the closet aтв check the same script with two LCDs. Thanks.

**Comment by AlexFundorin** [comment]
Hi, Jurgen. I have another issue with the controller.
I want to light up row select button on the right, but is only lights up if some control on the right side of the surface was pressed (i.e faders or buttonsC or buttonsD). How did you solve this issue? Thanks in advance.

**Comment by git-moss** [comment]
Should work when you enable Automap. See SLControlSurface.java

**Comment by AlexFundorin** [comment]
Thanks. Still don't get it. You're sending the following commands: https://i.imgur.com/OKi5gRd.png
Me too: https://i.imgur.com/voxt8Zz.png
Will experiment further with it.
