### ISSUE TITLE
Missing nativefilechooser from Maven repo?

### ISSUE THREAD

**Issue by giohappy** [git-moss/DrivenByMoss#260]
today I did an upgrade of my local dev project and I stumbled on the following error:

`[ERROR] Failed to execute goal on project DrivenByMoss: Could not resolve dependencies for project de.mossgrabers:DrivenByMoss:jar:13.7.0: Failed to collect dependencies at de.mossgrabers:nativefilechooser:jar:1.2: Failed to read artifact descriptor for de.mossgrabers:nativefilechooser:jar:1.2: Could not transfer artifact de.mossgrabers:nativefilechooser:pom:1.2 from/to MavenCentral (https://mvnrepository.com): Authorization failed for https://mvnrepository.com/de/mossgrabers/nativefilechooser/1.2/nativefilechooser-1.2.pom 403 Forbidden -> [Help 1]`

I purged my local repos to be sure it wasn't a problem with my Maven cache, or whatever, but any path I take Maven complains about the missing artifact. Is that removal intentional?

**Comment by git-moss** [comment]
Sorry, forgot to update the POM. Should work now.

**Comment by giohappy** [comment]
Thx, I supposed it was the case ;)
