### ISSUE TITLE
Is it possible for a device to send type of param?

### ISSUE THREAD

**Issue by fractalf** [git-moss/DrivenByMoss#261]
Hi,
thank you very much for this great piece of software!

I'm currently making an "Open Stage Control" template for Bitwig that will work for the latest version v1+ 

It would be awesome if there is a way to also send `/param/<id>/type` where type typically would be one of

* knob
* button
* dropdown

That way I could do a condition based on this and show the respective thing in the controller UI.

Right now I can "hack" the button to work (by using "On" and "Off", but this is dirty and won't work for dropdown)

![image](https://user-images.githubusercontent.com/5707457/134431906-8e84ecfd-b925-4415-84e3-d2312e8c200b.png)

* RED - a button
* YELLOW - a dropdown

![image](https://user-images.githubusercontent.com/5707457/134432087-86d22a0a-517e-4ea2-a0d1-6db8aa9cbc57.png)

Danke Schön :)

**Comment by git-moss** [comment]
Sadly, this information is not available via the API.

**Comment by fractalf** [comment]
OK, thank you. 
I will try to hack it. Come to thing about it all knobs follow a certain `<float> <unit>` format, while dropdowns usually have a `<string>` format. I will try out some reg exp magic
