### ISSUE TITLE
Configurable footswitch actions for Maschine Mk3

### ISSUE THREAD

**Issue by btubbs** [git-moss/DrivenByMoss#263]
I'm using Bitwig with a Maschine Mk3, with a two-button footswitch plugged in.  I would like to be able to configure what actions will happen when those buttons are pushed.  I see in the manual that there's functionality like this for Ableton and Mackie controllers.  Would love it for Maschine!

**Comment by git-moss** [comment]
Will be in the next update!

**Comment by btubbs** [comment]
Awesome!  Thank you <3
