### ISSUE TITLE
Feature Request: Flexi control combinations? 

### ISSUE THREAD

**Issue by mrfugu** [git-moss/DrivenByMoss#264]
Simply stated, some controllers have limited features, and depth. 

Specifically, Combination control (Button+Button, Button+Fader) could allow for flexible workflows by relating the 1st half of the combination (mnemonically)  to a 'mode' or 'focus' that the subsequent control then activates/modifies.

Additionally, Combination controls already appear in some of the default mapped controllers in this package.

**Comment by git-moss** [comment]
Generic Flexi already supports several modes, which are explained here: https://youtu.be/m4DkBlhR09g?list=PLqRWeSPiYQ64O9Ulu_aMQ9mdEDJDColcP&t=193
Furthermore, you can define a Shift button (Global -> "Global: Shift button"), which gives you several combinations.
