### ISSUE TITLE
The Ableton Push extension no longer produces notes in BWS 4.1 beta 1

### ISSUE THREAD

**Issue by robbert-vdh** [git-moss/DrivenByMoss#265]
I wasn't sure whether to report this here or to Bitwig themselves (since they obviously changed some things for this to happen) or here, so please let me know if I should send an email to them instead! My original Ableton Push no longer plays notes in any of the notes modes. All other functionality still works as expected, including the feedback on the pads when those notes are currently being played back.

Tested using the latest master branch version of the extensions (54f4d63afb9a66f2fb678351e1a6e904a5f8d9a9), Arch Linux, and Bitwig 4.1 beta 1 with build date 2021-11-04.

**Comment by robbert-vdh** [comment]
Got a response from beta@bitwig.com. I'll leave this issue open until the next beta drops so others can see this as well:

> Hi Robbert,
> 
> I could reproduce it over here, it's filed. Not sure yet what exactly is causing this. Thanks for reporting!
​
> Best regards,
> 
> Jogi
> Bitwig Technical Support Team

**Comment by git-moss** [comment]
Seems to be a general issue. Also broken on other controllers.

**Comment by git-moss** [comment]
Fixed in Beta 2.
