### ISSUE TITLE
Illegit use of 'audio' group

### ISSUE THREAD

**Issue by jarkkojs** [git-moss/DrivenByMoss#267]
Please. see: https://wiki.ubuntu.com/Audio/TheAudioGroup

I've sorted this out  by creating a group called 'realtime' for multimedia. E.g. 

```
$ cat /etc/security/limits.d/realtime.conf 
@realtime   - memlock   16777216 # 16 GB
@realtime   - rtprio    49
```

So in this framework the udev config would become:

```
$ cat /etc/udev/rules.d/99-userusbdevices.rules 
SUBSYSTEM=="usb",ATTR{idVendor}=="2982",ATTR{idProduct}=="1967",MODE="0660",GROUP="realtime"
SUBSYSTEMS=="usb",ATTRS{idVendor}=="17cc",ATTRS{idProduct}=="1340",MODE="0660",GROUP="realtime"
SUBSYSTEMS=="usb",ATTRS{idVendor}=="17cc",ATTRS{idProduct}=="1350",MODE="0660",GROUP="realtime"
SUBSYSTEMS=="usb",ATTRS{idVendor}=="17cc",ATTRS{idProduct}=="1360",MODE="0660",GROUP="realtime"
SUBSYSTEMS=="usb",ATTRS{idVendor}=="17cc",ATTRS{idProduct}=="1410",MODE="0660",GROUP="realtime"
```

**Comment by git-moss** [comment]
To be sure to understand this correctly:
- It works as I describe it in the manual but it is not suggested to do this this way anymore
- Now, create any group of which the user is a member and the USB device access
Correct?

**Comment by jarkkojs** [comment]
OK, so I did some rethinking and I actually think that putting those devices to the group is the correct action taken :-) But here comes the real story...

The problem part is this sentence in the manual: *Make sure that your user is a member of that group and the group does exist*. Putting user to the **audio** group effectively allows any process in users session to launch with any possible privileges that this group might have. Some of them, e.g rtprio, could actually cause harm to the system if used by either dysfunctional or purposely malicious software.

This perhaps might sound nitpicking but any mainstream distribution, such as Ubuntu or Fedora, would never support this with their default configuration. I know that your recommendation is very common but that does not make it right. Because Linux stack has been vastly improving during last couple of years for music production purposes (e.g. VST3, https://pipewire.org/, https://github.com/robbert-vdh/yabridge), it really makes sense to think what would work out for default configuration that would be feasible also for multimedia applications.

There is a pretty standard practice to deal with this kind of issue. It is to use sticky bits for executables, so that they will run with a specific effective UID/GID when launched. That way you can limit the access to the resources. I'd project that sticky bits will be part of the solution when mainstream distributions become more interested to polishing audio (which I hope takes wind after PipeWire becomes the mainstream).

So how to fix this? I think there should be a context for risks involved (and also that fixing them is out of context for DrivenByMoss), e.g. *The user must be member of the audio group in order the software to function. This has a security risk involved as this will allow any software that user launches have all the privileges of this group. There might be a better solution in future, as the distributions improve but this is the current reality.*

**Comment by git-moss** [comment]
Thanks for the investigation. So, the workaround with using a different group is not working? Sure, I can add the suggested text.

**Comment by jarkkojs** [comment]
Can this open for a few days? I can try to figure out proper patches.

**Comment by git-moss** [comment]
Sure.

**Comment by jarkkojs** [comment]
Hi, I took a more constructive route: https://github.com/systemd/systemd/issues/21743

This is the right place the fix it. As soon as I get feedback, I'll bake up a patch at least the MIDI controllers that you have in the rules file, and Launchkey Mini Mk3 (1235:0102).

I.e. better to make things right rather than explaining how to make best of things being wrong...
