### ISSUE TITLE
push2: knob/encoder sensitivity too high

### ISSUE THREAD

**Issue by feli74** [git-moss/DrivenByMoss#27]
I would like to have a scale factor for the encoder sensitivity in the preferences. For my fingers, the knobs answer far to quick, which makes e.g. using the browser to skim search through the presets a real pain - the slightest movement of my knob finger, or even just releasing it from the encoder, changes the dialed in value (in this case the preset). So I suggest having a scale factor in the preferences to 'slow down' the encoders to personal taste.

I am running linux if this matters

**Comment by amkdev** [comment]
Same here on Push 1 ... it's nice to have this browsing features but it's really not very usable atm

**Comment by git-moss** [comment]
WIll be improved in the next version (9.30).
