### ISSUE TITLE
Bitwig/Launchpad mk2 - sends don't work at first

### ISSUE THREAD

**Issue by spectromas** [git-moss/DrivenByMoss#271]
If I press shift + Send A at first the sends do not do anything. It seems like they can be made to work if you move the send pot slightly in Bitwig with a mouse, then a white light will show and you can then take control of the parameter. Is there no way to make them work initially from the launchpad? I'm using the latest bitwig and DBM.

**Comment by git-moss** [comment]
I cannot reproduce that.

What is your OS?
How many Sends are there?
Can you give some exact steps what you press or do?

**Comment by spectromas** [comment]
I'm using linux but I've just tried it on Windows and the same thing happens there too. 

The number of sends doesn't seem to make any difference, I usually have up to 3 or 4. 

Steps: 

Open default project (1 inst, 1 audio, 1 send)
On Launchpad press and hold Mixer and press Send A
Press the pads for either column 1 or 2 (from left) and nothing happens. 

To make them work I have to move the Send A knob with a mouse and then the feedback shows on the launchpad with the top lit pad being white, press this white pad and then the column works as expected.

**Comment by spectromas** [comment]
I've noticed this with device mode as well. 

Add Distortion to a track
Press User 2 to enter device mode
Column 3 with the default preset has no pads lit (parameter at zero)
Pressing any pad on that column does nothing
Move the parameter with the mouse, it reflects on the launchpad
Press the top/white pad in the column and then the launchpad can control it

**Comment by git-moss** [comment]
Could reproduce it on Linux, got fooled by it as well and added it now to the manual:
You need to set the "Takeover mode" to "Immidiate" because the virtual faders do not cover all values!

**Comment by spectromas** [comment]
Ah that's it, thank you! You know, the funny thing is that I tried changing that but neglected to restart the script so it didn't seem to make any difference. 

Thanks so much for this script, as a linux user with there being next to nothing like this available, and together with bitwig, it's like a dream come true.
