### ISSUE TITLE
Browser takes a long time to load when triggered by push

### ISSUE THREAD

**Issue by einfachfelixverdammt** [git-moss/DrivenByMoss#275]
When triggering the Browser via Push it takes way longer to load than by hitting "B" on the keyboard. 
Is there maybe a timer problem or sth. ?
I havent had the time to look at the code myself - just wanted to file this issue here

Thanks for all your great work!

**Comment by git-moss** [comment]
Yes, there is a delay and it was necessary in the past. But I did some tests now and it seems to work fine without it.
Will remove it in the next update.
