### ISSUE TITLE
Maschine Mikro MK2 Support

### ISSUE THREAD

**Issue by han-so1omon** [git-moss/DrivenByMoss#276]
Hi! Love your product! Would you be able to support the NI Maschine Mikro MK2 controller? It is the only controller that I have currently, and the other templates for NI Maschine products aren't compatible

**Comment by git-moss** [comment]
Sorry, I do not own a Mk2 and cannot support this. However, you could try to replicate the Mk3 template for the Mk2 and see how far this brings you.
