### ISSUE TITLE
Issues with OSC controller for Bitwig on Linux

### ISSUE THREAD

**Issue by fractalf** [git-moss/DrivenByMoss#278]
Hi,
I'm on Bitwig 4.1.6 using the latest 15.5.0 moss driver. Linux Mint 20.3 (5.4.100 kernel)

I experience 2 strange things when activating the OSC controller

1. I cannot quit bitwig property, it just freezes/hangs. Have to kill it in the terminal to get out..
2. The generic flexi driver for another HW controller just stops working

Not sure how I can debug this, but willing to help out

Some images:

![moss-bug-1](https://user-images.githubusercontent.com/5707457/154963933-529834c4-a186-4104-87ad-f4aa826a100d.png)
![moss-bug-2](https://user-images.githubusercontent.com/5707457/154963937-f25a5f5a-9bfb-4c3e-bbb7-ee1c8b2c8537.png)
![moss-bug-0](https://user-images.githubusercontent.com/5707457/154963927-dd3d0a13-5061-4bae-ae8a-5cec0e0a671c.png)

**Comment by git-moss** [comment]
Could be an issue with the Linux distro. I got some random reports from Linux people in the last time.
Are these things happening always (100% reproducable)? You can try to narrow them down by using only 1 controller as well as switching USB cables and -hubs.

**Comment by fractalf** [comment]
Is there some logs I can tail?

**Comment by git-moss** [comment]
You can check the Bitwig and Engine logs.

**Comment by git-moss** [comment]
So, you found the issue?

**Comment by fractalf** [comment]
No, this runs deeep, so I guess I will look at it "another day" and spend time on music instead ;) 
I closed it, because I thought it maybe was something on my end, but if you get reports from others on Linux, feel free to open it again until we resolve this
