### ISSUE TITLE
A/B solo and rec button not work in input 

### ISSUE THREAD

**Issue by rez23** [git-moss/DrivenByMoss#279]
Hi, on tracks only mute/un-mute button seems to works. All other buttons not controll relative features (A/B, Solo, Rec)

Controller: Akai APC40 MK2
Step To Reproduce: Open Bitwig, connect and configure the APC40 and simply try to operate with one of this buttons on any track.
Bitwig version: I have tested this on Bitwig 4.1.6 and 4.2 beta 1

**Comment by git-moss** [comment]
Which controller? Steps to reproduce?

**Comment by rez23** [comment]
Sorry I'm going to add the missing info

**Comment by rez23** [comment]
Ok strangely after conncting my apc40 on ableton now all seems to work correctly.... Really not know what happened.
So I cloese this issue.
Thanks for your support and thanks for your awesome work :)
