### ISSUE TITLE
Velocity Faders LP Pro MK3

### ISSUE THREAD

**Issue by ndee77** [git-moss/DrivenByMoss#280]
Hi!

First of all, thanks for your great work!

Just one thing is a little bit annoying me and that are the faders. Very often they are not working with velocity. So it's a direct movement to the position instead of delayed (with low velocity). Do you know this problem? (Launchpad Pro MK3)

**Comment by git-moss** [comment]
Didn't notice this so far. Did you check your velocity settings? Latest Firmware?

**Comment by ndee77** [comment]
Yes, latest firmware and i have tried all the different velocity settings (threshold and curve). When in use with Ableton, there are no issues with the velocity sensitive faders.

**Comment by ndee77** [comment]
Did some testing with the basic Bitwig script of Weskoop (https://github.com/weskoop/Launchpad-Pro-Mk3-for-Bitwig) and I noticed that the (Novation default) order of (4x) subdivisions per pad is different than in your script.

Your script: When you manually tick the first pad at a certain device control, you'll get the values: **0 - 0.551 - 0.866 - 1.181** and at the second pad: **2.441 (pad in track color) - 1.260 (light off) - 1.811 (white) - 2.126 (white) - 2.441 (track color)** etc. It doesn't matter how hard I hit the pads. 

Basic script, 1st pad in fader: **0.000 - 0.315 - 0.630 - 0.945** and 2nd pad: **1.339 - 1.654 - 1.969 - 2.283** etc.

So, in the default script every pad in the fader starts on the lowest value, in your script at the highest value, therefore it isn't possible to fluid fade up manually. Is that the problem? Further is the velocity sensitivity on the faders, at least at my device (v1.2.1 build 465 and DrivenbyMoss 15.6.0) not consistent. Sometimes it's working, most of the time there is no velocity control on the faders.

**Comment by git-moss** [comment]
DrivenByMoss does not use the "hardware faders" since they are quite different between the LP models or not existent. Therefore, you will see a different behaviour. The four step behaviour applies only if you press an already lit pad. I tried to improve the logic of this now a bit so it remembers the direction of the change and also does not wrap around but instead invert the direction of the change. Will be available in the next update.

**Comment by ndee77** [comment]
Thanks! That would be a huge difference. Keep up the good work!
