### ISSUE TITLE
Maschine Jam on Linux and Bitwig

### ISSUE THREAD

**Issue by rustikus** [git-moss/DrivenByMoss#282]
Hi,

thanks for your amazing scripts. I am currently using a Maschine Jam on MacOS with Bitwig and it works pretty well so far. Although I have to admit that I am on the very beginning of my journey into DAWs.

I would love to use the Maschine Jam on my Linux system as Bitwig itself works pretty well so far including various VSTs via yabridge. The only thing really missing is the proper support for my Maschine Jam (including your mappings).

I researched a bit and found some support via https://github.com/styyle14/maschine-jam-linux is available.

I compiled and loaded the mentioned module and it seems to work so far. Any chance to support Linux with the help of the mentioned project? 

Thanks and best!

**Comment by git-moss** [comment]
This would require a totally different implementation. I am afraid I will not look into this.

**Comment by rustikus** [comment]
OK, understandable.

Thanks anyway and keep up the great work!
