### ISSUE TITLE
Have To Disable Push 1 For User Mode Animations

### ISSUE THREAD

**Issue by seedrick** [git-moss/DrivenByMoss#284]
Something I used to do in Ableton quite a bit is light shows like shown here:
https://www.youtube.com/watch?v=Ezi6yXD9i1o

The only way I'm able to do this now with this extension is by opening the settings and killing the controller there, thus freeing up the user port. If this is currently the only way to do so, I can try fixing it and dumping it in a PR for the repo (I can't be the only one who misses this). I'm just checking that there isn't a toggle or something I'm missing somewhere. Really, all that needs to happen is for the extension to temporarily turn into a MIDI passthrough on just the pads.

**Comment by git-moss** [comment]
I am afraid you are the only one asking for this feature so far. ;-)
I have no plans to add this.
