### ISSUE TITLE
Sequencers not working with launchpad mk2 with bitwig linux

### ISSUE THREAD

**Issue by hamstah** [git-moss/DrivenByMoss#285]
Hi,
I use bitwig 4.0.1 on linux and the sequencers don't work with my launchpad mk2.
I can see fast faint flashing of lights on it so I see something is going on but it's not responding to touching the pads. 
Every pad on the 8x8 grid is turned off.

In the poly sequencer and the first drum sequencer modes the bottom half do have the notes lit up.

Any suggestion on how to further debug to help tracking down what's going on?

Thanks!

**Comment by git-moss** [comment]
Make sure you have a clip created and it is selected. Does that help?

**Comment by hamstah** [comment]
hey, thanks for the quick response!
I just tried, created a clip and selected it. I can hear the notes when I press the pads fine, and can record in the clip that way but the sequencer is still blank. I can see very faint flashes of white light as it goes.

**Comment by git-moss** [comment]
Could you make a video? Sometimes it is easier to spot this way, what is going on.

**Comment by hamstah** [comment]
Here you go, easier to see the flashing in the dark
https://www.dropbox.com/s/zoscej2shsuefmf/2022-03-19%2022.13.20.mp4?dl=0

**Comment by git-moss** [comment]
I did a test on latest Ubuntu and all works fine. I had some reports about strange behaviours on non-Ubuntu systems. Besides that I sadly have no idea.

**Comment by hamstah** [comment]
hey thanks for checking this. I'm on ubuntu 20.04
if you have suggestions on how I can further debug I'm happy to look more into this.
I have a clock transmitter device on a virtual midi to link to other stuff, is it possible that it interferes with it?

**Comment by git-moss** [comment]
Worth giving it a try.
