### ISSUE TITLE
BLE MIDI For Push 1

### ISSUE THREAD

**Issue by seedrick** [git-moss/DrivenByMoss#286]
Let me first thank you for your work on this--it's wild how thorough it is!

I have a [WIDI Uhost](https://smile.amazon.com/gp/product/B09GS326QW/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&th=1) that I tested in Ableton--everything is functional but the Sysex is a bit buggy. Some sections of the screen don't refresh until something is written over them. No big deal, a microscopic price to pay to have a wireless Push.

The problem is that the Uhost only has one port so much like with the other issue I opened, the problem comes down to the script being parked on the Push 1's second port. I'm reading through all the API stuff right now to get up to speed. Before I actually do a fork and try what I was thinking, I wanted to know if it was sane.

In theory, all I should have to do is change the logic around `isMkII`, correct? Is there any special reason you used the second port for Push 1, like the first being completely unavailable to third party scripts? I would hate to go set up a Java environment only to find out it's not possible to use that first port.

**Comment by git-moss** [comment]
I am not sure if I understand. The Push extension only uses 1 MIDI in and output. That is required for all the buttons, knobs and on Push 1 also the display.
For your idea with the animation you would need to write a new "View" as I call it in my framework and handle the notes accordingly.

**Comment by seedrick** [comment]
Ok, let me try to be more clear:

I'm using a bluetooth to USB MIDI adapter. That adapter only exposes the very first port of the device connected to it to the host. The extension does only use one port, but the second one. If I point the extension to the one port exposed by the adapter, it doesn't work.

Basically I need the extension to go from MIDIIN/OUT2 to MIDIIN/OUT1. Will changing line 61 in `PushControllerDefinition.java` get me the behavior I want?

**Comment by git-moss** [comment]
If the Widi device does not show the correct port, changing the code will not help you anything. Either you can select in the menu or not.

**Comment by seedrick** [comment]
Ok, thanks that's what I wanted to know. The WIDI port is there in the menu and I point to it but it's bugged. Let me run through my settings again and make sure I didn't fat-finger something. Thanks again for the help!
