### ISSUE TITLE
Bitwig computer keyboard won't typing ,shortcuts only Push 2 

### ISSUE THREAD

**Issue by KuKiW** [git-moss/DrivenByMoss#287]
is there anybody had the same issue?

**Comment by git-moss** [comment]
Sorry, I cannot understand the question.

**Comment by henning** [comment]
@KuKiW maybe this helps to understand what a developer needs to solve an issue with their software: 

https://medium.com/pitch-perfect/how-to-write-the-perfect-bug-report-6430f5a45cd

If you just want to chat with other users to see if they have similar effects, the driven by moss Forum on KVR might be a good place to start.

**Comment by KuKiW** [comment]
I was just moved the DrivenByMoss.bwextension to Bitwig Extensions folder for Push2

Everything works well but the Keyboard doesn't  work for example rename or search devices in the field but shorcuts

Sorry for my broken English! 

Thanks anyway !

**Comment by KuKiW** [comment]
https://www.reddit.com/r/Bitwig/comments/nijbhu/pc_keyboard_wont_write_only_shortcuts/

This is what I trying to say...

**Comment by git-moss** [comment]
So, you are saying you cannot type anymore in this field when the extension is running? Does it already stop working when the Push is connected? What is your operating system?
