### ISSUE TITLE
OSC vkb_midi ignores midi channel

### ISSUE THREAD

**Issue by bgola** [git-moss/DrivenByMoss#288]
I'm using Bitwig 4.2 trying to send different midi events to different channels but the MIDI note or CC events always arrive on channel 1.

Checking the source code and Bitwig's API documentation it seems like NoteIn.SendRawMidiEvent really ignores the Midi channel. Maybe there is another way to send a Midi event without ignoring the channel?

Is there a workaround?

**Comment by panda-madness** [comment]
@git-moss where do I find this setting? I'm having a similar issue with my Keystep Pro controller.

**Comment by panda-madness** [comment]
Nevermind, as usual I've found this setting right after posting for help :D
For anyone looking, it's located in the inspector tab on the left hand side, and is visible when you select an instrument track
![Screen Shot 2022-05-12 at 10 31 22](https://user-images.githubusercontent.com/6180087/167992558-b3fac3f4-6b5f-4526-8135-eb31ab8265b9.png)
.
