### ISSUE TITLE
Drum-Mode: Unable to reach all Drum Machine's Sample-Slots via Octave-Up/Down

### ISSUE THREAD

**Issue by amkdev** [git-moss/DrivenByMoss#29]
As the title says: the 12 very top and 4 very bottom sample slots in Drum Machine can not be reached via Push's Octave up/down buttons. An improvement would be nice.

An Idea could be the use of the Shift-button together with the Octave-buttons  to jump only 4 notes/slots up or down instead of 16.

**Comment by git-moss** [comment]
There was a problem getting this in sync again when you moved the other direction. I also thought about letting the user move in smaller steps but didn't do it because I think this is hard to understand where you currently are.
