### ISSUE TITLE
Drum rack color in 'Instrument selector' don't work

### ISSUE THREAD

**Issue by BillTribble** [git-moss/DrivenByMoss#291]
I have loads of color coded drum kits that work great on Push. This is really handy so I can see where kicks, snares, etc. are and play by feel. They normally look like this:

![image](https://user-images.githubusercontent.com/5898620/163048292-9eb6d0f6-5617-4960-ad75-61623e145496.jpeg)

However, when I try to use them in an Instrument Selector, the colors don't show up. Looks like this:

![image](https://user-images.githubusercontent.com/5898620/163048582-e3f29aaa-3501-4e43-aefe-2d519b599b20.jpeg)
![image](https://user-images.githubusercontent.com/5898620/163048620-35d252ad-6ca5-4850-9acc-180652fd9f50.jpeg)

Be great if you could fix this so we could use drum kits in an 'Instrument Selector' and still see the colors. Many thanks!

**Comment by git-moss** [comment]
This cannot be fixed by me. The (known) issue is that the drum device is only found among the top level devices but not if it is wrapped inside a container. Therefore, the colors will not be drawn.
