### ISSUE TITLE
Adjust instrument colors?

### ISSUE THREAD

**Issue by BillTribble** [git-moss/DrivenByMoss#292]
In Ableton, 'non octave' notes are a neutral green - this is easy on the eyes. I can crank the LED brightness up so text labels are clear everywhere.

![image](https://user-images.githubusercontent.com/5898620/163051780-e307bbe2-36b2-4f7b-9957-eca182385c23.jpeg)

However, in Bitwig all the 'non octave' notes are lit WHITE, which makes them a bit blinding in a dark room. If I drop the brightness, I can't see the button text.You can see here how hard to read the labels are.

![image](https://user-images.githubusercontent.com/5898620/163051055-08fae526-c524-4350-9e52-898605daf62b.jpeg)

Any chance you could change the color of these notes to work more like the Ableton version? Works much nicer in a dark room (or club!) for me. IMO an orange or red would work nicely - or you could add a color option to Bitwig.

Many thanks 🙏

**Comment by git-moss** [comment]
White was actually the original Ableton color :-) Nevertheless, will add it to my wishlist.
