### ISSUE TITLE
[feature request][Launchpad mini mk3][Bitwig] allow stop clip in session mode by long or double tap on clip

### ISSUE THREAD

**Issue by ehanuise** [git-moss/DrivenByMoss#293]
Hi.
New Bitwig linux user, and proud owner of a new launchpad mini mk3 (I decided for this model after I saw it was supported by your add-on, and because the novation components web app works fine in linux).
First, thanks a lot for this wonderful add-on and the support of so many devices. This is greatly appreciated!
I just ran through the DrivenByMoss user manual for the launchpads, and it's great too, something often missing with Open Source project. Thanks again :)

When in session mode in Bitwig, clicking on a clip launches it, and clicking again on the clip will re-launch it.
To stop the clip (not the whole track, just the clip), the only way I could find was to either select an empty clip on that track (meaning you have to leave a empty clip in the session for this purpose), or to activate the stop clip (shift, then pink) and lose a whole column of pads in the session view.
Would it be possible to allow stopping a single clip either by long-tapping or double-tapping it ?
This could be an option in the 'workflow' section of the add-on settings : "Stop clips in session mode : Off/long tap/double tap" with "Off" being the current behaviour.

**Comment by git-moss** [comment]
The option should be doable. Will add it to my wishlist.
