### ISSUE TITLE
Push 2: Selected track doesn't show in Push

### ISSUE THREAD

**Issue by BillTribble** [git-moss/DrivenByMoss#295]
When I change track via MIDI, the relevant layout doesn't show in Push if the track is on a different mixer 'page'. Right now I have to limit my live set to 8 channels as I can't use layouts anywhere else. 

Is it possible to fix this? Thanks!

**Comment by git-moss** [comment]
What do you mean by "When I change track via MIDI"? Did you manually map another controller to a track?
Please give some more details what your setup is and what you are exactly doing.

**Comment by BillTribble** [comment]
Of course yup. In my live set I need to get to instruments really quickly. I'm using a channel per drum patch - so I can use the '64' layout and see colour coded which drum is where. 

I select say '808' with a CC from a MIDI controller. (This is MIDI mapped 'channel selection' in Bitwig). Then I switch to a Linndrum, Indian drum kit, etc. This is quicker and more direct than finding tracks on the Push. (I also have a bunch of instruments I get to this way - they live in Instrument Selectors as there's no need for a color coded drum map).

My problem is - with this setup I can only reach 8 tracks. If I choose a drum patch on track '9', the Push pad layout doesn't update, and the device LCD 'knobs' don't match. I have to manually change 'page' in the Push before these things will work.

So my request:
Make the Push layout and channels update to match the channel is selected in Bitwig - even if it's outside the 1-8 you're currently looking at.

**Comment by BillTribble** [comment]
A quick video demo of the problem here - https://www.dropbox.com/s/8852z97zm9fkteu/bitwig-layout.MOV?dl=0

**Comment by git-moss** [comment]
OK, so the actual issue is that the note layout is not remembered when you switch track pages. Correct?

**Comment by git-moss** [comment]
I can replicate it but I am afraid I cannot fix this. The problem is how the value updates work in Bitwig. They are sent asynchroneously and in no guarenteed order. So, storing and reading the selected layout might get mixed up.

**Comment by BillTribble** [comment]
Ah, damn. Well, thanks for confirming! I wonder if we could store layout settings on a text file, anything like that?
