### ISSUE TITLE
Drum Sequencing while playing on APC mini.

### ISSUE THREAD

**Issue by luciotorre** [git-moss/DrivenByMoss#296]
Hi! Thanks for this awesome driver.

I am using bitwig 4.2.3 on Ubuntu 21.10 and everything mostly seems to work fine. 

If I press stop then i can sequence without an issue. I select the drum sample i want to add and then on the top rows i can add or remove the sample at the appropriate time. Then i pick a new sample and i get the pattern for that sample in the top rows.

The problem is when trying to edit the sample patterns while playing, as the presented pattern always switches to the last played sample. For example: I press play on a 1 bar sample. I select the kick and sequence a hit on beat 1. The play head keeps moving. At some point i select the snare. The first rows now show the snare pattern (empty for now). But as soon as the play head reaches beat 1 it will show the kick pattern. And if i press any button it will add a kick, not a snare.

Am I missing something?

Thanks.

**Comment by git-moss** [comment]
I am not sure if I fully understood your issue but could be the browser issue. Are you talking about selecting a sample from the browser? Try switching tracks and check if it works again.

**Comment by luciotorre** [comment]
(thanks for the fast reply)

I think i am not using the right terminology and/or not being consistent. So let me share the steps to reproduce the issue.

On a new and empty bitwig project:
(shift [1,1]): make sure you are in session mode(shift+rec arm): Make clip stop buttons rec arm
(rec arm 1): rec arm track one
(shift+[7,1]): create new clip and it starts playing
(shift+[3,1]): go to drum sequencer
([8,1]): select kick
([1,1]) place a kick on beat one
([8,2]): select snare
if you press any button in the first two rows it will place a snare up to the moment when the play head reaches beat one. Then it will start placing kicks and displaying the kick pattern.

This was a consistent behavior yesterday, but today i could not reproduce it, and it would not change to kick when the kick was played, which is good.

Is there a setting I fat fingered to make it behave like that? I dont know. I have seen other issues claiming APC mini was erratic, so maybe that is it. I can try help you debug issues with it if that would be helpful.

Either way, feel free to close this.

**Comment by git-moss** [comment]
Hmm, the APCmini is really a device I cannot recommend (while other Akai stuff is really good). My device for example always freezes after a while.
