### ISSUE TITLE
Bitwig and Push/2: load items from pads while browsing

### ISSUE THREAD

**Issue by vokinpirks** [git-moss/DrivenByMoss#299]
Hello!
First of all, I want to thank you for this wonderful piece of work. I've been enjoing the Bitwig + DrivenByMoss combo since I discovered it a couple days ago. 

However, I have a proposal how to improve browsing experience.
I order to load a device/preset/whatever I touch the right-most knob and then turn it to scroll through the items till I get to the item I want to load.  This takes some time and Bitwig loads every item I scroll through. On some items the whole process is freezing for a few seconds (Bitwig says it's 'Optimizing devices') .
What if we could use pads to instantly load the desired item?
The Push 2 display shows up to 48 items (6 rows x 8 columns), so we could map pads to items accordingly. So pressing the 3rd row 6th column pad would load item that's showing up in the 3rd row and 6th column in the display. Optionally, the pads that have corresponding browser item to load would lit. So, if the dsiplay shows only 13 items to load, only 13 pads are lit to indicate availability of items. The two bottom rows of pads are still available to trigger notes in order to preview sound that's currently selected.

Additionally, this approach would open up more opportunities. For now, only one item can be selected from collections/category/tags/etc. With this pad approach we would be able to select as many items as we want to. For instance, I'd select three tags to filter presets. Tap a pad to select an item, tap another time to deselect. Of course, the pads that corresponds to currently selected browser items would be lit.      

What do you think of this?

**Comment by git-moss** [comment]
I am not sure if the benefit would be as much as you think since trying to find the correct pad to press in a 6x8 matrix is not easy.
Some things you might try instead:
- You can setup your favorite plugins for the "add track" function
- Create (small) Collections (first column) with your favorite plugins which can be navigated much easier.

**Comment by vokinpirks** [comment]
> since trying to find the correct pad to press in a 6x8 matrix is not easy

Thank you for your reply.
Vertically it's just the same column since it relies right under the browser column, so it's all about to count to six to find a correct row.
