### ISSUE TITLE
Question about SL LCD

### ISSUE THREAD

**Issue by AlexFundorin** [git-moss/DrivenByMoss#30]
I remember that your BW script was in different language before. JS, if I'm not mistaken.
Not it's a one big archive - *.bwextension. I tried to open it and found .class files.
I'm specifically interested in SLDisplay.class.
As far as I understand, you've already implemented a method to reduce plugin name strings, so they would fit into 8 character fields on the SL's LCD. I wonder what function/set of rules did you use for that task.
Like, leave numbers untouched, leave capital letters, delete vowels and so on.
Could you, please, share your approach with me?

**Comment by git-moss** [comment]
There is this pretty simple function here:
https://github.com/git-moss/DrivenByMoss/blob/master/src/main/java/de/mossgrabers/framework/StringUtils.java

**Comment by AlexFundorin** [comment]
Thanks. I wasn't clear. What was your method to convert and display long track names on the LCD (8 char per track name)?
http://i.imgur.com/iT3UmpN.png

**Comment by git-moss** [comment]
Then I guess you mean this:
https://github.com/git-moss/DrivenByMoss/blob/master/src/main/java/de/mossgrabers/framework/mode/AbstractMode.java
optimizeName

**Comment by AlexFundorin** [comment]
Yes, Kinda. What if the name consists of all vowels or doesn't have any, at all?
