### ISSUE TITLE
Bitwig Remote controls - Feedback not shown when adjusting Push2 rotary encoders

### ISSUE THREAD

**Issue by tonybyrne** [git-moss/DrivenByMoss#301]
Hi,

Just spotted something odd with DrivenByMoss v16.4.0 under Bitwig 4.3 Beta 9 on Mac. When adjusting device controls via the Push 2 rotary encoders, no visual knob feedback is shown in the bottom of the Bitwig window like other controllers do.

For example, my Arturia Keylab shows the following when adjusting device parameters via its encoders:

<img width="951" alt="Screenshot 2022-06-25 at 21 14 07" src="https://user-images.githubusercontent.com/27082/175789353-d965c650-83e6-4813-bb14-9e3b6b182a19.png">

However, when doing the same on the Push 2, the on screen 'knobs' are not shown and the controls page name is shown vertically offset from the usual position:

<img width="783" alt="Screenshot 2022-06-25 at 21 13 27" src="https://user-images.githubusercontent.com/27082/175789402-756f06ea-72b7-49d4-8984-1aa89f63748d.png">

Cheers!

T.

**Comment by git-moss** [comment]
I can replicate it. Could be a bug in the new hardware API. Need to check back.

**Comment by tonybyrne** [comment]
Thanks! Let me know if I can help test any fix.

T.

**Comment by tonybyrne** [comment]
@git-moss This is now working with DrivenByMoss v17 & Bitwig v 4.3.2. Thank you!

**Comment by git-moss** [comment]
Yes, got fixed in 4.3.2.
