### ISSUE TITLE
Hitting pads in drum pad layout while auditioning closes the browser

### ISSUE THREAD

**Issue by agrover** [git-moss/DrivenByMoss#302]
Using bitwig studio 4.3.2-beta on Windows 10 with latest DrivenByMoss bwextention, I'm seeing something weird.

When I'm auditioning Drum Machine presets, if I switch the Push2 layout (hit the Layout button 3 times) into drum pad mode and hit some pads, after a few hits it accepts the current preset I'm auditioning. If I am in any other Layout, or if I click the little |> button in each drum cell, it doesn't do this -- it stays in the browser. Expected behavior: it should always stay in the browser until I click OK.

**Comment by git-moss** [comment]
Ah, I see. The issue is when the option to display the drum pads channel is active. Guess this should be blocked when the browser is open.
