### ISSUE TITLE
SL MKIII - polyphonic pressure is missing

### ISSUE THREAD

**Issue by gethiox** [git-moss/DrivenByMoss#303]
Polyphonic pressure for "drum pad" on my SL MKIII device seems to not work at all with DrivenByMoss.
When device is connected by generic keyboard controller (Bitwig) or just midi cable, it works correctly.

**Comment by git-moss** [comment]
It seems that when using InControl mode, the pads do not send aftertouch information. So, you would need to send this as a feature request to Novation.
