### ISSUE TITLE
Akai Fire copy/paste, mute/solo left side buttons don't work

### ISSUE THREAD

**Issue by Nek** [git-moss/DrivenByMoss#304]
Hello! First of all thanks for the great work. The latest drum machine mode update is great and brings Akai Fire and Bitwig combo as close to a live instrument as possible.

I have a problem though. Two first mute/solo buttons don't do what I can see in your latest video.
If I press the button once the indicator on the right of it switch between red/green but holding it and pushing steps as in the video doesn't do anything.

I hope there is a quick solution. Otherwise, I'm into debugging it (I'm developer). Just hoping for a quick solution and a hint on where to start in case of debugging.

**Comment by git-moss** [comment]
Seems to work fine for me. One thing to note is, that the scene must exist where you want to paste the clip. E.g. if you only have 8 scenes you cannot paste in to slot 10.
2nd button is for solo/mute. To copy patterns also use the 1st button.
If that does not help please post some steps to reproduce the issue.

**Comment by Nek** [comment]
Figured it out. I have a pretty special setup that solo and mute are not compatible with. Thanks!
