### ISSUE TITLE
Akai Fire "pin" drum editor to a track

### ISSUE THREAD

**Issue by Nek** [git-moss/DrivenByMoss#305]
I'd like to use several controllers at the same time but keep Akai Fire for drum jamming only (in XoX mode). 
This means it should be "pinned" to the track with drum machine and ignore cursor track.

I'd like to try to implement it  (already browsing through the code). Is it doable as a small hack or should I prepare for something more involved?

**Comment by git-moss** [comment]
You can pin it in the sidebar in Bitwig:
![grafik](https://user-images.githubusercontent.com/3090132/180601945-5d16e0c7-322a-4e47-8a04-95d0d4f7c48c.png)
