### ISSUE TITLE
OSC midi drop down list doesnt show any midi ports  in Bitwigh 4.3.2 for Mac OS 

### ISSUE THREAD

**Issue by chusmc** [git-moss/DrivenByMoss#306]
Hi
I installed the DrivenByMoss-17.0.0 for Bitwig
I am running on MacOS BigSur 

Copied DrivenByMoss.bwextension to $HOME/Documents/Bitwig Studio/Extensions
When I add a new controller, I can see the option to add OSC, so I guess the extension has been recognised
Once the controller is added, I cannot enable it or select a midi port (The only midi option that shows is "None")

I also installed open-stage-control and started the server, but doesnt seem to make a difference

Thanks

**Comment by git-moss** [comment]
Do you have any MIDI ports on your system? You can create a virtual one, e.g. see here: https://dialogaudio.com/modulationprocessor/guides/virtual_midi/virtual_midi_setup.php

**Comment by chusmc** [comment]
Hi
Thanks.. I think that was the issue. I thought the extension was creating virtual midi inputs itself. Thanks for the clarification
