### ISSUE TITLE
Independend navigation with two APC mini connected not working.

### ISSUE THREAD

**Issue by drakh** [git-moss/DrivenByMoss#308]
So i am using two APC MINI controllers.

When navigating thru the TrackBank(left,right,up,down), i found an issue that these two controllers does not have separate navigation. sort of.
When navigating UP/DOWN the track bank can be navigated separately. But when moving the bank LEFT/RIGHT the bank moves for both of the controllers.

**Comment by git-moss** [comment]
That's the expected behaviour. See these 2 videos what you can do about it:
https://www.youtube.com/watch?v=lA4JJsxIcUU
https://www.youtube.com/watch?v=EPjdhBtNNP0

**Comment by drakh** [comment]
> That's the expected behaviour. See these 2 videos what you can do about it: https://www.youtube.com/watch?v=lA4JJsxIcUU https://www.youtube.com/watch?v=EPjdhBtNNP0

Thanks for your reply, I saw this videos. Anyway, i solved it by writing my own controller script. For what I want to say thank you. Your tutorials, and this repository is great source of knowledge, which really helped me a lot to write script for my needs.
