### ISSUE TITLE
push2: encoder sensitivity for scale too high

### ISSUE THREAD

**Issue by feli74** [git-moss/DrivenByMoss#31]
The encoder sensitivity for the scale selection is IMO too high. It's quite hard to select a certain scale and leave the selection in place when releasing the encoder, because releasing it often causes another jump in the selection.
You have recently adjusted the sensitivity for the encoder use in the browser view, thanks a lot for that, is really so much better now! But it seems that the scale selection needs a similar treatment. Again I suggest: Can't we have a knob sensitivity setting in the preferences, and use a common debouncing mechanism based on that value for all the encoders?

**Comment by git-moss** [comment]
Will be slowed down in the next version.
