### ISSUE TITLE
Empty OSC mapping in Bitwig

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#310]
Software:
Bitwig 4.3.4
DrivenByMoss-17.5.0-Bitwig
Windows 10

When pressing the "OSC" text in under Settings -> Controllers -> Any 'Open Sound Control' item, the web page is generated doesn't contain any information, only headers:

Button to click:
![image](https://user-images.githubusercontent.com/1904092/188284491-9291f6a9-0c15-4482-8637-225b79534787.png)

Output:
![image](https://user-images.githubusercontent.com/1904092/188284505-6e266ee1-352e-4344-b16a-85a12a420ae6.png)

**Comment by git-moss** [comment]
That page is automatically created by Bitwig for OSC commands which use Java annotations. I use instead a generic implementation. Therefore, I cannot fill these tables. Instead refer to the documentation in the DrivenByMoss manual.

**Comment by TommyC81** [comment]
Thank you, understood.
