### ISSUE TITLE
OSC - When scrolling using bank/+ and bank/-, incorrect selected track indication when out of range

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#311]
Software:
Bitwig 4.3.4
DrivenByMoss-17.5.0-Bitwig
Windows 10

When scrolling using OSC '/track/bank/+' and '/track/bank/-' and the selected track goes out of range (i.e. outside of the normally 8 tracks), there is no OSC message being sent indicating that a previously indicated "selected" track is no longer selected. In practice, this normally means that Track 1 or Track 8 remains indicated as Selected.

Note in the below log extract how there is no message indicating that /track/1 is no longer the selected track as it goes out of range (question mark in the image). A message like this would be expected where the question mark is:
`RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:63286) ADDRESS(/track/1/selected) INT32(0)`

![image](https://user-images.githubusercontent.com/1904092/188284606-7090e8c7-6e84-4bed-a5b8-8a7dc25daa6e.png)

End-state as per image below. Note: as per OSC data, track 1 is never indicated as no longer selected, although the selected track "Audio 3" is no longer in the range:
![image](https://user-images.githubusercontent.com/1904092/188284675-b45297c6-b896-4551-8432-d94952316c80.png)

**Comment by git-moss** [comment]
These commands move the banks' page by 1. It does not change any track selection. Furthermore, /track/1 is not the first track! It is the first track on the current track page! See the position attribute in your log.
If you want to make the track selections you can use
/track/bank/page/+ 
or 
/track/+

**Comment by TommyC81** [comment]
Maybe a misunderstanding, I don't want to change track selection. The bug is that no message is sent when the selected track is no longer the first track on the current page. Please note that correct messages are sent to indicate that the "relative" track on the track page is (or not) the selected track, but this message is not provided when the selected track goes outside the track page.

**Comment by TommyC81** [comment]
Not sure how to describe this better. Please check the screenshots agsin: the selected track is no longer on the track page, but there is no message received saying that that "track page" track 1 is no longer the selected track.

Track 1 on the track page remains indicated as selected, as no more selected updates are sent as soon as the selected track goes outside the track page.

**Comment by TommyC81** [comment]
An additional note to highlight that the manual also indicates that the message should be sent. I will create a video showing the problem as soon as time permits:
![image](https://user-images.githubusercontent.com/1904092/188374275-5485393d-ebc7-4e77-a0a6-ee5df12c4b72.png)

**Comment by TommyC81** [comment]
I've uploaded a video here: [https://www.youtube.com/watch?v=vz39QwM1Acs](https://www.youtube.com/watch?v=vz39QwM1Acs)

Whilst preparing the video, I discovered another bug: When the selected track has gone outside the "track window" and you then select next track, it selects next track relative to the window (still assuming that the first track in the track window is selected, and thus jumps 2 steps. Check from 0:39 into the video. This link should work [https://youtu.be/vz39QwM1Acs?t=39](https://youtu.be/vz39QwM1Acs?t=39)

**Comment by git-moss** [comment]
I see. Need to check.

**Comment by TommyC81** [comment]
Thank you, much appreciated, hopefully it can resolved.

I'm hoping to contribute with a well-developed tablet sized TouchOSC template in return. You've done some amazing work!

**Comment by git-moss** [comment]
Got it! Will be fixed in the next update.

**Comment by TommyC81** [comment]
Fantastic!! :-)
