### ISSUE TITLE
OSC - Incorrect panning setting in messages after '/pan/reset'

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#312]
Software:
Bitwig 4.3.4
DrivenByMoss-17.5.0-Bitwig
Windows 10

After using '/pan/reset' and then sending a new panning value, it leads to a random panning value being set in Bitwig. Normally stuck at -100% (0) or 100% (127). Subsequent updates work correctly. Sending a FLOAT or INT32 does not make a difference.

There could be some different underlying issue, or there may be other functions affected in the same way, but this is what I've observed.

Update: This issue seemingly has nothing to do with '/pan/reset', whenever trying to set distinct values, panning jumps to an almost random value but corrects itself after further updates to panning.

Message log from TouchOSC below: 

```
23:58:59.156 | SEND       | ENDPOINT(192.168.0.101:8000) ADDRESS(/track/4/pan/reset)
23:58:59.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/update) INT32(1)
23:58:59.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/track/4/panStr) STRING(0.00 %)
23:58:59.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/track/4/pan) INT32(64)
23:58:59.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/update) INT32(0)
23:59:07.157 | SEND       | ENDPOINT(192.168.0.101:8000) ADDRESS(/track/4/pan) FLOAT(19.984459)
23:59:07.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/update) INT32(1)
23:59:07.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/track/4/panStr) STRING(-100 %)
23:59:07.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/track/4/pan) INT32(0)
23:59:07.177 | RECEIVE    | ENDPOINT([::ffff:192.168.0.101]:59620) ADDRESS(/update) INT32(0)
```

**Comment by git-moss** [comment]
Make sure that the "Takeover mode" is set to immediate in the Bitwig controller settings.

**Comment by TommyC81** [comment]
Thank you, didn't realize the takeover setting would apply to OSC messages as well. No way to avoid this? I'm also using other controllers.
