### ISSUE TITLE
OSC: Reversed function between "/device/param/{+,-}" and "/device/param/bank/page/{+,-}"

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#314]
Software:
Bitwig 4.3.4
DrivenByMoss-17.5.0-Bitwig
Windows 10

It seems the function of the following messages are reversed (or the manual is wrong or not clear):

Receive - Cursor Device / Primary Device / EQ
![image](https://user-images.githubusercontent.com/1904092/190232319-c3e2227a-fba5-4915-a341-346b126a33d5.png)

Using "/device/param/{+,-}" jumps 8 pages.
![image](https://user-images.githubusercontent.com/1904092/190233193-345d3d61-6062-458e-b0fb-15f2be4b058b.png)

Using "/device/param/bank/page/{+,-}" goes to the next/previous page:
![image](https://user-images.githubusercontent.com/1904092/190232834-8097fe4c-9ca6-4fde-928e-346fee8d9e5e.png)

**Comment by git-moss** [comment]
Thanks, will be fixed in the next update!
