### ISSUE TITLE
OSC: Inconsistency, missing "name" tag for device remote control pages

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#315]
Software:
Bitwig 4.3.4
DrivenByMoss-17.5.0-Bitwig
Windows 10

OSC messages related to the name for device remote control pages are missing the "name" tag. The messages simply end with a "/" rather than the expected "/name". For the device/page/selected, the message does however end with "/name".

See log below:
![image](https://user-images.githubusercontent.com/1904092/190451754-e0ea8559-7490-4e00-87b6-e598d2b682f4.png)

This seems to be aligned with the manual, but is an inconsistent application compared to all other instances where a name is sent. Suggest to align the message to include the "/name" tag.

From the manual:
![image](https://user-images.githubusercontent.com/1904092/190452400-dc0e907c-2bd0-4357-afae-f5395083dd16.png)

**Comment by git-moss** [comment]
Yes, I agree. I added the 'name' but will keep the old one for backwards compatibility. Will be in the next update.
