### ISSUE TITLE
OSC: Non-documented "Receive" messages: "/device/page/{1-8}/selected" and "/device/page/{1-8}/select"

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#316]
Software:
Bitwig 4.3.4
DrivenByMoss-17.5.0-Bitwig
Windows 10

Receive - Cursor Device / Primary Device / EQ
There is no documentation for the following messages that both work and seem to work the same way:

"/device/page/{1-8}/selected" and "/device/page/{1-8}/select"

They both select the (numbered) device remote control page.

The only related documented message is this:
![image](https://user-images.githubusercontent.com/1904092/190455433-9a7fef47-f917-4345-bed1-64bc34597bc9.png)

**Comment by git-moss** [comment]
Thanks. I added the "selected" message. "select" is only there for backwards compatibility.
