### ISSUE TITLE
OSC: No send/receieve message for "/device/sibling/{1-8}/bypass"

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#317]
Software:
Bitwig 4.3.4
DrivenByMoss-17.5.0-Bitwig
Windows 10

There doesn't seem to be any OSC message available for getting/setting "bypass" status for "/device/sibling/{1-8}", it is only available for the currently active device, like so: "/device/bypass".

Consider adding "/device/sibling/{1-8}/bypass" send/receive messages.

**Comment by git-moss** [comment]
I guess that makes sense. Will add it to the wishlist.

**Comment by git-moss** [comment]
Next update will have:
  * New: Added /device/sibling/{1-8}/exists
  * New: Added /device/sibling/{1-8}/bypass
