### ISSUE TITLE
osc4bitwig seems not listen on IPV4 or does not listen at all

### ISSUE THREAD

**Issue by seegwen** [git-moss/DrivenByMoss#32]
Bitwig studio 2.2.3 registered, downloaded from Bitwig studio website.
Up-to-date macos el capitan.
DrivenByMoss from here: http://www.mossgrabers.de/Software/Bitwig/DrivenByMoss.zip and installed according to the docs

Steps:
Start Bw, Go to controllers preferences, load OSC extension, choose virtual midi (IAC 2 for my case), set listening port to 8016, set sending port to 8017 (both hosts to 127.0.0.1), deactivate extension, reactivate extension.

Now in terminal:
sudo lsof -i | grep Bitwig
output: only IPV6 bindings, and none on the 8016 port.
Two on UDP ports:
   * UDP *:irdmi
   * UDP *:54130

Fire Puredata, create a simple [udpreceive 8017] -> [unpackOSC] -> [print].
Result:
Everything from osc4bitwig is received and printed to the Pd console.

/edit

The sending Pd test:
![capture d ecran 2018-01-30 a 16 25 55](https://user-images.githubusercontent.com/2071961/35574508-44ca6404-05da-11e8-911b-c58c35be4fa5.png)

when pressing the [send /play 1(, the result is no effect in Bitwig, and when pressing a second time, "udpsend send: Connection refused (61)" in Pd console.

**Comment by seegwen** [comment]
Might have been a problem with the osc lib of puredata since the same test worked with a node script.

**Comment by git-moss** [comment]
Great!
