### ISSUE TITLE
OSC: No message for '/device/param/{1-8}/exists' and '/device/page/{1-8}/exists'

### ISSUE THREAD

**Issue by TommyC81** [git-moss/DrivenByMoss#320]
Pressed enter and submitted by mistake, corrected now:

Software:
Bitwig 4.3.4
DrivenByMoss-18.0.0-Bitwig
Windows 10

A message was added in v18.0.0 as per below:
_New: Added /device/sibling/{1-8}/exists_

Although it can be worked around via script (by checking whether the 'name' property is empty or not), it would be convenient to have an 'exists' message for the following items:

- /device/param/{1-8}/exists
- /device/page/{1-8}/exists

**Comment by git-moss** [comment]
OK. Will be in the next update.
