### ISSUE TITLE
Unable to save Flexi file

### ISSUE THREAD

**Issue by misterk73** [git-moss/DrivenByMoss#322]
Hi. I am unable to save (or load) a file for a generic flexi. I may have denied a permission when first asked to do so, but I am having a really hard time figuring out how to change that preference after the fact. Do you have any suggestions? I am on MacOS 11.6.8. When I click "Save" or "Load" my computer switches to the finder, but there's no ability to save, edit, or select that's tied to DrivenByMoss or Bitwig. If it matters, I am currently in Bitwig "demo mode." Thoughts? THANKS!

**Comment by git-moss** [comment]
Congratulations you use a Mac, you are safe now! 👍 
Sorry for the sarcasm but I just wasted 1 hour trying to find the solution to this:
-> go to the privacy settings in the security dialog
-> on the left select "Automation" (not file & directory access)
-> on the right there should be Bitwig in the list
-> enable the checkbox
