### ISSUE TITLE
Bug in the browser display

### ISSUE THREAD

**Issue by banermatt** [git-moss/DrivenByMoss#323]
Bitwig 4.3.8
DrivenByMoss-18.0.0-Bitwig
Windows 7
Push1

There is a bug  in the browser. When navigating some presets (and more importantly when navigating clips/samples when a collection is selected), the selection menu is mixed with the parent browser menu, which makes some presets/samples impossible to select. [Here](https://drive.google.com/file/d/1ZpDFswAgaTqTsBIA82cNNyvKSE-8E4J9/view?usp=sharing) is a video showing the problem.

EDIT: Apparently the bug appears only when non ASCII characters are in the name of one of the filtered presets.

**Comment by git-moss** [comment]
Seems Bitwig got pretty creative with using non-ASCII characters on this device :-)

Will be fixed in the next update!
