### ISSUE TITLE
Wrong triplet notes lengths in sequencer mode

### ISSUE THREAD

**Issue by banermatt** [git-moss/DrivenByMoss#325]
Bitwig 4.3.8
DrivenByMoss-18.0.0-Bitwig
Windows 7
Push1

In the sequencer mode, the triplet default note lengths should probably be shorten a bit, because of [this problem](https://drive.google.com/file/d/1ZgV7ejgWqcDkyKQYV3GlG4Rrh_ikbvbd/view?usp=sharing).

**Comment by git-moss** [comment]
That's handled by Bitwig (I only call to toggle the step). So, try sending it to support.
