### ISSUE TITLE
Preview toggle does not work when browsing clip or samples

### ISSUE THREAD

**Issue by banermatt** [git-moss/DrivenByMoss#327]
Bitwig 4.3.8
DrivenByMoss-18.0.0-Bitwig
Windows 7
Push1

As the title says: the button that toggles the preview does not work when browsing clip or samples.

**Comment by git-moss** [comment]
Didn't notice this so far but the dialogs seem to use a different preview concept and do not have a preview button. Maybe also something to ask Bitwig people about.
