### ISSUE TITLE
Feature request: implement clip content editing and retrieving functionality for OSC.

### ISSUE THREAD

**Issue by seegwen** [git-moss/DrivenByMoss#33]
I think everything is in the title.

The OSC controller script is pretty complete as-is, but I'd like to be able to remotely edit a clip using OSC.

What do you think about it ? Is it feasable ?
I see this in the Scripting docs:
/Applications/Bitwig Studio.app/Contents/Resources/Documentation/control-surface/api/a00032.html

**Comment by git-moss** [comment]
Sorry, for the late reply. I will look into this but need some time (lots of other things going on), incl. a review of the current features.

**Comment by seegwen** [comment]
Hey there, thanks for the reply anyway !
I wish I could help… easy to request for features.

Best

— 
Gwen

**Comment by git-moss** [comment]
I looked into this and decided against iut. Either it would need to be very simple and unflexible or very complex, which would also require a very powerful OSC client.
