### ISSUE TITLE
Select Master Track function in Flexi

### ISSUE THREAD

**Issue by centomila** [git-moss/DrivenByMoss#330]
I've noticed that i can assign
- Select Track,
- Select FX Track 

But i didn't find a way a function to select the Master track. What I'm missing?

![image](https://user-images.githubusercontent.com/26800547/197295296-d85b0a78-fe51-4b65-a208-658be9424b0a.png)

**Comment by git-moss** [comment]
You are missing the function ;-)

Will add it!
