### ISSUE TITLE
Selecting track in "Overview" mode triggers "Note"mode (FIRE controller)

### ISSUE THREAD

**Issue by fractalf** [git-moss/DrivenByMoss#331]
Hi, 
I usually have the FIRE in "Overview" mode, where I can control the mute, solo, arm/rec etc.

But when I select a track in Bitwig the controller automatically jumps to "Note" mode.
It does not do this when in a "Perform" mode.

Is this a bug or "feature" ? :)
(If it's a feature, can we have an option disabling this?)

For my use this is quite annoying, cause I have to go into "overview" mode again every time I switch tracks.

Thank you!

**Comment by git-moss** [comment]
I just recently changed it, so it does not leave the PERFORM / OVERVIEW views. Are you running the latest version 18.1?

**Comment by fractalf** [comment]
Ok, thank you!
I'm still using 16.4.1, because I don't have Bitwig v4.3, so I guess I just have too look forward to this next time I upgrade
