### ISSUE TITLE
[Reaper - APC40 mkII] - Tempo knob only works to decrease tempo

### ISSUE THREAD

**Issue by danielrimaldi** [git-moss/DrivenByMoss#332]
Hi, I've just downloaded the extension and I must say this is some amazing work! I'm still trying things out while reading the manual, but I've noticed that the tempo knob on the APC40 mkII does not work to increase the tempo, but works fine for decreasing tempo. I tested the knob via Reaper's built in mapping and it works fine for increasing/decreasing tempo. Did I miss something? Really appreciate the amount of work you're putting into this project!

Cheers :)

**Comment by danielrimaldi** [comment]
Whoops, my bad! I just looked into my Reaper commands and turns out I hadn't deleted the tempo knob assignment. Everything works okay now!

**Comment by git-moss** [comment]
Best issues are the ones who solve themselves :-)
