### ISSUE TITLE
Launchpad Mk2 toggle overdub launcherclips not working

### ISSUE THREAD

**Issue by shigosu** [git-moss/DrivenByMoss#336]
Hi there,
i have an Issue with the Launchpad Mk2.

Software:
DrivenbyMoss 18.2
Windows 11
Bitwig 4.4.3

In Shift Mode the Toggle-Overdub-Clip-Launcher-Button shows the current setting but won't respond to pressing it.
The same goes with the Arranger-Record button to the left.

Greetings!

**Comment by git-moss** [comment]
Thanks! Will be fixed in the next update!
