### ISSUE TITLE
[Feature request] Clip launch toggle & recording end quantization 

### ISSUE THREAD

**Issue by Robert-K** [git-moss/DrivenByMoss#337]
As someone who does a lot of live looping, I found that Bitwig lacks two very essential features:

**Clip launch toggle:**
Building a track live using controller pads for clip recording is great, but stopping the clips requires an extra stop button/pad. Barely ever do I need to restart a running clip, I usually want to stop them. Using the Launchkey MK3 Mini for example, I can do that with the extra stop clip row. However, I feel like there should be a setting that allows me to stop a running clip simply by hitting it's pad.
Ableton Live has this built in, it's missing in Bitwig sadly. Is this possible to integrate in DrivenByMoss?

**Recording end quantization:**
In Bitwig the clip launch quantization also applies to the recording end. This is plain terrible for live looping. It feels natural to end the clip recording right on the first beat of the next loop, but that will result in Bitwig recording an extra bar (depending on said quantization). The recording end should quantize to the closest bar, not the next one.
The Boss RC-505 does this, and it feels so much better. Ending the recording just a tad late in Bitwig can mess up the live jam entirely. There should at least be an option for said behaviour. Again, I'm not sure if it's possible to implement this in a Bitwig extension.

**Comment by git-moss** [comment]
First one could be done with an option but this area is already pretty bloated. Therefore, I suggest to send both to Bitwig as a features request. Especially, the 2nd one is something I would like to see, too! Talked to Bitwig about it already in the past but the more requesting it the better.
