### ISSUE TITLE
Up/Down for pattern change on Akai Fire reversed layout

### ISSUE THREAD

**Issue by ndee77** [git-moss/DrivenByMoss#339]
First, thanks for your great work! The Akai Fire with your script on Bitwig is a superb combination!

Mostly I have Bitwig in vertical session view (but in horizontal view I experience the same issue), but de layout of the pattern up/down buttons on the Akai Fire are, in my opinion, not working correct. When I click the arrow up on the Fire, it goes one clip down in Bitwig. On down it goes up. Is this as designed or could it be changed? 

Also there is nog velocity on the device in note or drum mode? With shift+step(accent) i can de- or activate the fixed velocity, but there is no difference. Also changing the 'fixed accent value' in the settings does not change anything.

Kind regards,
Nick

**Comment by git-moss** [comment]
Yeah, button orientation can always be discussed. But I have no plans to change it.

The velocity is a big drawback of the device. It is unusable (from my experience about 4 steps but even that is unreliable).
