### ISSUE TITLE
Feature request: ability to change the "page size" of tracks by OSC

### ISSUE THREAD

**Issue by seegwen** [git-moss/DrivenByMoss#34]
... Either by configuring it in the dialog, or by setting it via OSC ala
/page/size/set [page size]  and 
/page/size/get   to retrieve it.

My use case is that sometimes I want to get the whole session and handle the paging on the controller size, or more basically I would like to make the "current page" span my whole grid device which is 16 as of now.

What do you think ? You could still let the default page size to 8.

For now I can just call a page and the next and handle the data I get back from it on the controller side but it seems a bit hacky...

**Comment by git-moss** [comment]
Would be nice but page sizes cannot be changed during runtime.

**Comment by seegwen** [comment]
Allright, I see in the docs that "banks" are a Bitwig concept, and I understant that my use case does not match yours.
So, could there be an option, maybes at compile time, to increase the bank size in your scripts ?
