### ISSUE TITLE
Mute & Solo buttons, Master track, Komplete Kontrol S-series mkII

### ISSUE THREAD

**Issue by DomiKamu** [git-moss/DrivenByMoss#340]
Hello,

I'd like to report a missing visual feedback about Master track (Bitwig Studio v4.4.x, Windows 10) on my KOMPLETE KONTROL S-series mkII keyboard.

For any track type (instrument, audio, FX) the **Mute** (orange) button and **Solo** (blue) button may are illuminated (dim if disabled, bright if enabled, it's normal).

But, for Master track, when selected, both M and S buttons are never illuminated (despite Master track can be muted and soloed, M and/or S can be toggled on/off). I precise the buttons toggle Mute and/or Solo of Master track (as expected), but no visual return on the S-series mkII keyboard.

Hope my explanation is clear.

My rig:
- Windows 10 Pro x64 (22H2), French-localized.
- Bitwig Studio v4.4.6.
- KOMPLETE KONTROL S61 mkII controller.
- DrivenByMoss-18.5.0-Bitwig (same behavior concerning DrivenByMoss-18.3.0-Bitwig, previous I've used).

![image](https://user-images.githubusercontent.com/24851960/209126224-4f24ab07-d6f1-4028-8a8a-32079e351695.png)

Regards,

Dominique.

**Comment by git-moss** [comment]
Thanks for the info. This is a bug on NIs side. Will see if we can get a fix for that.

**Comment by DomiKamu** [comment]
You're welcome.
And be sure it's not a drama! ;)

**Comment by git-moss** [comment]
Needs to be fixed by NI.
