### ISSUE TITLE
[Launchkey SL MKIII] Option to add a deadzone or better sensitivity settings

### ISSUE THREAD

**Issue by abeforgit** [git-moss/DrivenByMoss#341]
It might be a defect on my unit, but the rotary knobs are so sensitive that they sometimes change their value (by a tiny amount). At first I thought it was a result of bumping them, but I've seen it happen without touching the device.
In normal use, it happens just often enough to be distracting, especially when browsing the library (where a slight change can have a big impact, like changing the tab).

I've tried lowering the sensitivity, but they don't seem to help much. Maybe I misunderstand the settings? Negative number is less sensitive right?

EDIT: confirmed lower number is less sensitive, but the setting seems to have no impact on the knob behavior in the file browser! It works as expected everywhere else.

In any case, ideally there would be some kind of deadzone setting, like you often see on videogame controller settings. Another option could be to add a way to disable the rotary knobs for the library browser only. It would make scrolling through samples a little less fun, and it wouldn't solve the twitchiness when not in the browser, but I'd be happy with that.

Thank you in any case for this fantastic piece of software. It makes ableton seem like amateur hour in comparison :)

**Comment by abeforgit** [comment]
I had a shot at this, but it was surprisingly more challenging than I expected. Do you have any docs about how the rotary values come in? Am I correct in deducing that they represent turning speed rather than position? I see what you're doing in the `TwosComplementValueChanger` but I'm struggling with turning the values into useful discrete steps...

For the time being, to solve my issues, I've just turned off the knobs in the `BrowserMode`, but it's not a great experience if you have a lot of samples.

**Comment by git-moss** [comment]
You cannot fix such an issue on the software side. I guess you already checked for the latest Firmware with the Components App?
If this does not solve the issue contact Novation support, they are pretty helpful in my experience.
