### ISSUE TITLE
Function for relative change of 8 remote control knobs

### ISSUE THREAD

**Issue by poedyatel** [git-moss/DrivenByMoss#342]
Is it possible to add a function that allows to use relative mode for 8 parameter knobs? This would be much more convenient than absolute, in which you need to regularly synchronize the knobs.

**Comment by git-moss** [comment]
Could you please give me some context which device you are talking about?

**Comment by poedyatel** [comment]
I mean Generic Flexi, I'm trying to make friends with M-vave SMK-25, it's a simple midi controller with no deep integration features, 25 keys, 8 pads and 8 knobs

**Comment by git-moss** [comment]
Look at "Knob mode" option:
![grafik](https://user-images.githubusercontent.com/3090132/215348502-22080668-2d20-4271-a833-f8cb04b2378b.png)

**Comment by poedyatel** [comment]
Yes, it's half way. At the next step, in the device list, where you can select the "Device: Set Parameter 1" function. Among these functions, we need one that will increment and decrement values by 1 when a signal comes from a relative knob

**Comment by git-moss** [comment]
No, that is automatically handled depending on the "Knob mode" setting. If it does not work make sure that you selected the correct Relative mode (there are 3).

**Comment by poedyatel** [comment]
I think that the mode is correct, because if I choose the Transport: Move Play Cursor, it will work well, if I change the modes, then there will just be a little lag and invert.
But the "Device: Set Parameter" function has another problem. According to the name it tries to set the value of the parameter to either 0 or 127, and this is ignored because any knob in the bitwig must be "hooked" before it changes value when the hard knob is rotated. Even if we manually make such a "hook", for example, by setting the parameter to the minimum or maximum with the mouse, it still will not work correctly, but will jump from min to the max when the physical knob is rotated

**Comment by git-moss** [comment]
I think there is a misunderstanding. "Set Parameter" controls the remote controls of each device. If you want to do specific mappings, use the USER functions ("User: Set Parameter").
I did a video some time ago about remote control parameters here: https://www.youtube.com/watch?v=UeK9cGfNDeo

**Comment by poedyatel** [comment]
That's right, we're talking about remote controls of each device and function "Set parameter". I'm not explaining well, sorry, I'll try to explain differently:
The relative knob always sends two identical messages containing the volume value 0 or 127. "Set parameter" sets the received value to the corresponding remote control, i.e. 
`executes parameter = 0`
or 
`execute parameter = 127`
We need a function that will not assign an absolute value, but add or subtract 1, that is, 
`execute parameter = parameter + 1 `
or 
`execute parameter = parameter - 1`

**Comment by poedyatel** [comment]
I think that the solution to my problem lies in expanding this list of functions, and perhaps I'm asking this in the wrong place. Did you develop these functions for flexi, or is it provided by Bitwig?
![function list](https://user-images.githubusercontent.com/114159416/215496990-1d8e93d0-4678-425d-be2c-5e28c533c64b.jpg)

**Comment by git-moss** [comment]
Again, it does all that. The MIDI CCs you showed above use the "Twos complement" relative encoding. If you select this option "Device: Set Parameter X" will handle it correctly. Just to be sure I tested with exact these values. These are the settings:

![grafik](https://user-images.githubusercontent.com/3090132/215538509-4c17112a-091e-4606-bffb-0ebef52a6f9e.png)

**Comment by poedyatel** [comment]
Damn! I must have made a mistake somewhere, I'm using linux and so many different things had to be molded together ... now I've destroyed everything and built it again and it works correctly! Sorry! Thank you!

**Comment by git-moss** [comment]
No worries.
