### ISSUE TITLE
Names for slots

### ISSUE THREAD

**Issue by poedyatel** [git-moss/DrivenByMoss#343]
It's not very convenient to search for slots when re-editing a flexi-controller, especially if a lot of time has passed since the first setup.
It would be convenient if the names were automatically generated when choosing an action, and were available for manual editing.
![изображение](https://user-images.githubusercontent.com/114159416/216614316-3f0fc69b-7747-422f-85af-72518235c861.png)
![изображение](https://user-images.githubusercontent.com/114159416/216614351-b441c951-a4ec-41b6-923f-1773bcf5376b.png)

**Comment by git-moss** [comment]
I fully agree with you but sadly this is the best I can come up with with respect to the possibilities of the Bitwig API. This API was designed for 'simple' settings and not to build a complex user interface.
