### ISSUE TITLE
Launchpad Add Device does not open Browser

### ISSUE THREAD

**Issue by Kazou22** [git-moss/DrivenByMoss#344]
Newest version of Launchpad X script for Bitwig does not open a browser window. I know that there is a dedicated button to open the browser window but it also does not work if there is no device present on the track.
Repro:
Create a new device track from Shift menu (First Green Button)
Observed:
A track is created with no device. The device browser window does not open. Pressing the last scene button does not open the browser window.
Expected:
Creating the device track should allow the browser window, either opening one or allowing the scene button to open one if one is not present.

That's it unless I am missing something else...  Thanks!

**Comment by git-moss** [comment]
Since 19.1 the browser is now opened with the last scene button in the device mode. Pressing the device button twice does now enter USER mode.
Also see https://www.youtube.com/watch?v=12Xd50Ohe1c

**Comment by Kazou22** [comment]
Sorry, but the last scene button does NOT open the browser if there is no device already on the track. I am using 19.1 and saw the video.

**Comment by git-moss** [comment]
And this got fixed in 19.2 :-)

**Comment by Kazou22** [comment]
So sorry that I missed the release.  Thank you so much for all the hard work you put into this.
