### ISSUE TITLE
Push Scale Request

### ISSUE THREAD

**Issue by 0b1kn00b** [git-moss/DrivenByMoss#345]
I'm doing something specific for an 8x8 grid and can't get notes in order without omissions or repeats ascending using the full width. I think I've tried everything but I can't see it. 12 chromatic notes, no repeats, and if you'd prefer it as a PR, I'll have a go.

**Comment by 0b1kn00b** [comment]
https://github.com/git-moss/DrivenByMoss/blob/bbc597706b6256afaea12cfc746fa73b4b2e9618/src/main/java/de/mossgrabers/framework/scale/Scale.java#L132

Feels like it's doable.

**Comment by 0b1kn00b** [comment]
Thank you.

**Comment by 0b1kn00b** [comment]
I can get around this with drum64 and a note grid, I think.

**Comment by git-moss** [comment]
You can also use "Sequent ^" scale layout in Play mode and enable "Chromatic".

**Comment by 0b1kn00b** [comment]
Are you sure it's in the Push 1?

**Comment by git-moss** [comment]
To select the Scale Layout press Scale to enter the scale selection. In that mode hold the Shift button to select the Scale Layout.
