### ISSUE TITLE
Note Repeat Octave selector not initialized properly

### ISSUE THREAD

**Issue by adamschabtach** [git-moss/DrivenByMoss#346]
Using the Launchpad Pro script in the 19.2.1 package, Bitwig Studio 4.4.8: the Octave selector in the Note Repeat section of the settings panel is initialized to zero, but the Note Repeat function itself operates as though the Octave selector is set to one. It's easy to hear if you press just one pad on the Launchpad. It's not a big problem but it has confused me on more than one occasion.

**Comment by git-moss** [comment]
Hmm, seems the settings are not firing on new projects. Will set it to 1 to match the Bitwig default.

**Comment by adamschabtach** [comment]
Thanks, and thanks so much for all of your work. A Launchpad Pro and your script have changed the way I make music.
