### ISSUE TITLE
Thanks so much! Can I...

### ISSUE THREAD

**Issue by eggsyntax** [git-moss/DrivenByMoss#349]
Hi Jurgen,

I just wanted to say thanks for this fantastic repo, and for making it available to everyone for free and GPLed. Is there a way to send you a bit of money, just in the interest of supporting your work on this project?

Thanks!

**Comment by git-moss** [comment]
There is a "Thanks" button under each video on my channel: https://www.youtube.com/channel/UCMgtq3iKqYamt9C-xbxwjTA
