### ISSUE TITLE
Add Note Grid Guitar Layout

### ISSUE THREAD

**Issue by bigggmoustache** [git-moss/DrivenByMoss#350]
I'm using an APC40 mk1 which has 5 row of buttons available for notes. Is it possible to add a setting for a guitar layout?

E.G. instead of from lowest to highest a chromatic root C being C, F, A#, D#, G# we could have C, F, A#, D#, G, lowering the top row one note to match a guitar layout? Generally speaking different guitar related layouts would be fantastic all around. Drop, open, etc.

**Comment by git-moss** [comment]
I have no plans for this. This would also require a completely different approach to how the scale layout is currently implemented.
