### ISSUE TITLE
[Novation launchpads Mk3] Custom mode with Novation Components

### ISSUE THREAD

**Issue by zozolapino** [git-moss/DrivenByMoss#355]
Hi!
Thanks for your extensive bitwig extension !

I can't find a way to jump to the Novation native Custom Mode pages using your extension with bitwig, with my launchpad X: the "custom" button only calls your settings. I'd like to recall the new "Novation Components" 8 custom/users pages which allow users to set a lot of custom functionnalities, including pads grouping and custom colors settings for each pad.

This custom driver for Launchpad X and Bitwig let me use them, it doesn't modify the "custom" button:
https://github.com/Jengamon/Launchpad-X-Bitwig-Script

Any workaround?

**Comment by git-moss** [comment]
Sorry, no. I need to use the programmers mode to implement this functionality.
