### ISSUE TITLE
Akai Fire - Feature Request: Possibilly of rotating the clip launcher / performance mode to utilize 16 buttons in order vs 4 when rotated

### ISSUE THREAD

**Issue by raygervais** [git-moss/DrivenByMoss#356]
Similar to Bitwig's session view with the scene laucnher present, is it possible at all to use all 16 pads on a single lane for clip launching (for easier visualization, say I were to rotate the Akai Fire 90 degrees)? 

Currently, we launch scenes in performance mode using the four buttons, but simply curious what the work effort would be (or, if it's even possible) if the option was there to leverage the launching in the other direction, thus allowing up to 16 clips to be launched per lane. 

![image](https://github.com/git-moss/DrivenByMoss/assets/14265337/6fae638a-4b44-4c7e-9e60-1cdf8405b615)

Thanks so much for the script, it's made working with Bitwig a blast

**Comment by git-moss** [comment]
I decided against it, since I think that the scenes should be there as well and then 1 scene + 3 clips is not that helpful. Maybe a scene only mode would be useful.

**Comment by raygervais** [comment]
But, to be clear @git-moss just so we're on the same page, I meant having a launcher view where all 16 clips per track are seen on the fire. What if we didn't have a scene in that view?
