### ISSUE TITLE
Extension doesn't work at all

### ISSUE THREAD

**Issue by spongbbx** [git-moss/DrivenByMoss#359]
I couldn't find a solution or a similiar problem so I'm posting it here.

I have the Launchpad Pro Mk3 with newest firmware, newest Bitwig Studio update and newest DrivenByMoss release. No matter how many times I try to install it to the Extensions folder, it won't work. Bitwig doesn't detect my Launchpad and doesn't list it as a possible device to add. It does work with controller extensions but then it doesn't give me the Moss functionality.

I don't know if I'm doing something wrong or what, I just used the steps in the manual

**Comment by git-moss** [comment]
Are you using already Bitwig 5 or 4? For 4 use DrivenByMoss 19!

Can you add it manually in Bitwig or is DrivenByMoss not showing up at all? If it is not showing up it is in the wrong directory. Meanwhile you can simply drag & drop the DrivenByMoss.bwextension file onto the Bitwig window and it will install it in the correct directory.

**Comment by spongbbx** [comment]
Ah, yes. I downloaded the wrong version. Sorry 😅
