### ISSUE TITLE
Gamepad Left and Right Joysticks. Joysticks -xy axis is equal to the +xy axis. 

### ISSUE THREAD

**Issue by HBreckenridge** [git-moss/DrivenByMoss#360]
Moving Both Joysticks both directions output 0-127 in CC values.
How can the joystick have a +- option like the other macros in bitwig?
It would be great if the joystick when in its dead zone output a cc value of 64. 
When the joystick moves all the way left or down it outputs cc value 0.
When the joystick moves all the way up or right it outputs cc value 127.
Anyways thank you for making this awesome plugin. I have been waiting for this and dreading building it myself since ive started to use gamepads for professional performances. :-D
Thanks!!

**Comment by git-moss** [comment]
It was already on my TODO list for quite some time. Will be in the next update :-)

**Comment by HBreckenridge** [comment]
Thank you so much for responding so fast. Also thank you for taking the time to do this. I cant tell you how awesome it is to be able to have the gamepad hooked up to a daw without the latency of having a program to translate and send it midi.
Great work!!
