### ISSUE TITLE
OSC bank/page/+- change selected track in BW5/dbm20.3

### ISSUE THREAD

**Issue by zozolapino** [git-moss/DrivenByMoss#362]
Already see this bug in previous versions (issue closed), regression ?

**Comment by git-moss** [comment]
PLease be a bit more specific. Which page? What happens?

**Comment by zozolapino** [comment]
Hi Jurgen!
I have created 9 tracks (Kontakt) on BW, then load your new Open Stage Template, select the first track on bitwig, then click on the next bank page on OSC, track 9 is selected now.

**Comment by git-moss** [comment]
That is how it is supposed to work.
