### ISSUE TITLE
Device Parameter Page indexing issue on Launchkey 37 MkIII

### ISSUE THREAD

**Issue by 0b1kn00b** [git-moss/DrivenByMoss#364]
Certain pages are not addressable from the pads, but that seems to change depending on the patch. Here's a patch which demonstrates it. The indexing issues are *inside* the NoteFx in a chain and there are 16 pages.
In v 21.1.0

[WetBack.zip](https://github.com/git-moss/DrivenByMoss/files/12376269/WetBack.zip)

**Comment by git-moss** [comment]
Thanks, will be fixed in the next update!

**Comment by 0b1kn00b** [comment]
thank u!
