### ISSUE TITLE
[Push 2] Clip accent jump -100% / 100%

### ISSUE THREAD

**Issue by centomila** [git-moss/DrivenByMoss#365]
When using the "Accent" functionality, which becomes available upon pressing the CLIP button, it does not scale as expected. Instead of a continuous or varied scaling, the value toggles between only two positions: -100% and 100%.

DrivenByMoss Version: 21.2.0
The problem was present also on earlier versions.

Bitwig version: 5.0.6

**Comment by git-moss** [comment]
Thanks! Will be fixed in the next update!
