### ISSUE TITLE
Unexpected behavior for Overdub and Delete

### ISSUE THREAD

**Issue by decurus** [git-moss/DrivenByMoss#367]
Hi there,
Thanks for this wonderful software. I have been using it with a Novation Launchpad MKII for quite some time, but after the recent update to Bitwig 5.0+ some of the behavior changed in a way I found quite unexpected (and apparently undocumented)

The first one being the Overdub in the shift menu. Upon pressing it, it creates a new clip (exactly like the "new clip" button does) instead of toggeling overdub mode. It also does not seem to indicate the current state of this setting, the sequencers, however, do (changing the color of the currently playing note between red and green)

The other thing that changed could also be a design decision, I am not certain. Previously, whenever you deleted a clip, that's all that happened, after the update, when you delete a clip and the current track is armed, it immediately starts recording again. I use the Software for live improv and liked the previous behavior a lot because whenever I messed up a take, upon quickly deleting it, it gave me time to rethink and especially wait for the loop to start over (instead of starting to record right in the middle). However, if this behavior was intended to be like this, I guess I just have to get used to it. If you disarm the track, the delete button works as I would expect (just deleting the clip), but of course, then you can't continue to play live.

Thanks again, Keep up the great work

**Comment by git-moss** [comment]
I think these are fixed by now. Please re-open if you still have issues.

**Comment by decurus** [comment]
Hi there, I just downloaded the latest version of your plugin (22.1). 
Deleting the clip works perfectly fine now, thank you very much.
Sadly the ovedubbing still does not work as it is described. I press the button that according to the manual enables/disables overdub and a new clip is created (and launched). Overdubbing via a shortcut on my keyboard however works normally (overdub is being enabled, no new clips are being created).
Is there anything I can do to help you find the problem?

**Comment by git-moss** [comment]
Ah, now I see. That is actually a feature. You can configure what happens for "Record" and "Shift+Record" in the settings.

**Comment by decurus** [comment]
oh all right, I completely missed that, thank you so much, that's actually a really cool feature. All problems solved.
