### ISSUE TITLE
Allow using LaunchControl XL knobs for first 3 track remote controls 

### ISSUE THREAD

**Issue by haszari** [git-moss/DrivenByMoss#368]
Since Bitwig 5.0, tracks now support remote controls (just like instruments, devices etc). These can be mapped to anything, e.g. traditional sends / pan, or instrument, effect, synthesis parameters. https://www.bitwig.com/userguide/latest/midi_controllers/

The Novation LaunchControl XL is a great match for track remote controls because it has 3x knobs for each of 8 channels. This means the user can live-tweak 3x custom synthesis or effects params across 8x instruments! 🎛️🥳

As I understand it these knobs are currently mapped to Send 1, Send 2 and Pan for each of 8 tracks in DrivenByMoss. I would love it if there was an option to map the knobs to the first three track remote controls. Personally I use remote controls (filters, envelope params, modulators etc) a lot more for performing than say panorama (though of course track remotes would allow control of pan or sends too).

This same approach might be useful in other multi-channel controllers with knobs/CCs on each channel. I've been [prototyping this approach with a Kontrol F1](https://github.com/haszari/wide-bitwig-controller-extensions/blob/main/TraktorKontrolF1/src/main/java/com/cartoonbeats/TraktorKontrolF1Extension.java#L50-L74) (4x channels with a knob and a fader). 

I'm happy to help with this by contributing a patch if you're open to that – @git-moss let me know what you think.

**Comment by haszari** [comment]
Started exploring this in a fork here: https://github.com/haszari/DrivenByMoss/tree/try/issue-368-track-remote-controls

### current status
I haven't got far, just baby steps. 

- Added a new [`TRACK_REMOTE_CONTROLS` mode](https://github.com/haszari/DrivenByMoss/commit/4438e9beb374c977023823f094a52be26f2af4f9#diff-92991a6b6fdfdca99ba6ff25735ebe1a0efbeab06694a2e98688f963a677d014).

- Added a [`XLTrackRemotesMode` class](https://github.com/haszari/DrivenByMoss/blob/4438e9beb374c977023823f094a52be26f2af4f9/src/main/java/de/mossgrabers/controller/novation/launchcontrol/mode/main/XLTrackRemotesMode.java) - currently a duplicate of `XLTrackMixMode`.

- [Register `XLTrackRemotesMode`](https://github.com/haszari/DrivenByMoss/blob/4438e9beb374c977023823f094a52be26f2af4f9/src/main/java/de/mossgrabers/controller/novation/launchcontrol/LaunchControlXLControllerSetup.java#L164) and [associate with factory template 1](https://github.com/haszari/DrivenByMoss/blob/4438e9beb374c977023823f094a52be26f2af4f9/src/main/java/de/mossgrabers/controller/novation/launchcontrol/LaunchControlXLControllerSetup.java#L451-L454).

### next steps
To get this working, I think I'll need to add support for track-level remote controls in infrastructure classes…

1. Add interfaces for track remote controls in `IChannel`.
2. Implement these interfaces in `ChannelImpl` to expose remote controls to clients of channels. 
3. Add a `TrackRemoteControlParameterProvider` and use that in `XLTrackRemotesMode` to bind remote controls to the XL knobs.

Interested to hear thoughts on this approach or suggestions for how to implement a track remote controls mode.

**Comment by git-moss** [comment]
Thanks for the hint. Seems I somehow skipped the LaunchControl XL when I added project/track remote controls to all other devices. I want to look into the XL soon since several wishes have piled up.

**Comment by haszari** [comment]
Awesome, thanks @git-moss ! Let me know if I can help with this :)
