### ISSUE TITLE
Tempo fine adjust broken on Electra ONE controller

### ISSUE THREAD

**Issue by blackeyedpony** [git-moss/DrivenByMoss#371]
The shortcut Knob 1-2-7 does not work for fine adjusment of the tempo knob on the Electra One controller Transport page.
Also on the Transport page, the "<<" and ">>" BPM buttons do nothing. I assume they are supposed to +/- 1 the tempo, right ?

**Comment by git-moss** [comment]
Thanks for reporting! The tempo changes will be improved in the next update!

The "<<" and ">>" are for navigating the marker pages. The will become functional when you have more than 8 markers in a project.
