### ISSUE TITLE
DrivenByMoss-21.5.1-Bitwig + Maschine Mikro Mk3

### ISSUE THREAD

**Issue by jrdnyquist** [git-moss/DrivenByMoss#375]
This issue is with DrivenByMoss-21.5.1-Bitwig running in Windows 11 with Bitwig v5.1 using the Maschine Mikro Mk3 device. Firmware is the latest version (0.5.2).  

Loaded bitwig extension by placing in C:\Users\Studio\Documents\Bitwig\Studio\Extensions\DrivenByMoss.bwextension. Loaded C:\Users\Studio\Downloads\DrivenByMoss-21.5.1-Bitwig\resources\Maschine Mikro Mk3\DrivenByMoss.ncmm3 into the Native Instruments Controller Editor (version 2.8.2) and saved. Everting looks good in Bitwig under Settings -> Controllers.

The issue is when pad mode is selected it works as expected. However it reverts to "keyboard mode" randomly w/o any actions taken. You can switch to pad mode again and usually within a few minutes  (sometimes more sometime less) it reverts back to keyboard mode. I noticed "Play" pops up briefly in a little box box in the middle of the screen when this happens but the transport does not start playing. Not sure if this is a bitwig or moss driver issue.

Thanks!

**Comment by git-moss** [comment]
That sounds like the keyboard key triggers randomly. I had similar reports where some dirt was stuck in/around the key. Did you check this? E.g. you could connect it to a MIDI monitor and see if random messages appear.

**Comment by jrdnyquist** [comment]
This ended up being an issue with Windows drivers. I cobbled together some powershell (be sire to launch ad administrator) scripts to reset drivers based on this article: https://www.kvraudio.com/forum/viewtopic.php?t=577541

Disable NI services
Stop-Service -Name "NIHardwareService"
Set-Service -Name "NIHardwareService" -StartupType Disabled
Stop-Service -Name "NIHostIntegrationAgent"
Set-Service -Name "NIHostIntegrationAgent" -StartupType Disabled

Disable device KOMPLETE KONTOL M32 MIDI
Disable-PnpDevice -InstanceId (Get-PnpDevice -FriendlyName "KOMPLETE KONTROL M32 MIDI").InstanceId -Confirm:$false

Rename all folders with a X- prefix
Get-ChildItem -Path "C:\Users\Jody\AppData\Local\Native Instruments" -Directory | Rename-Item -NewName { "X-" + $_.Name }

Rename two folders with a X- prefix
Rename-Item "C:\ProgramData\Native Instruments\Controller Editor" -NewName "X-Controller Editor"
Rename-Item "C:\ProgramData\Native Instruments\Komplete Kontrol" -NewName "X-Komplete Kontrol"

Enable things
Enable device KOMPLETE KONTOL M32 MIDI
Enable-PnpDevice -InstanceId (Get-PnpDevice -FriendlyName "KOMPLETE KONTROL M32 MIDI").InstanceId -Confirm:$false

Enable NI services
Set-Service -Name "NIHardwareService" -StartupType Automatic
Start-Service -Name "NIHardwareService"
Set-Service -Name "NIHostIntegrationAgent" -StartupType Automatic
Start-Service -Name "NIHostIntegrationAgent"

Rename all folders removing the X- prefix
Get-ChildItem -Path "C:\Users\Jody\AppData\Local\Native Instruments" -Directory | ForEach-Object { Rename-Item -Path $.FullName -NewName ($.Name -replace '^X-', '') }

Rename two folders removing X- prefix
Don't do this! Leave the new directories. Open the controller editor and either load the backup or reload the moss template!

Rename-Item "C:\ProgramData\Native Instruments\X-Controller Editor" -NewName "Controller Editor"
Rename-Item "C:\ProgramData\Native Instruments\X-Komplete Kontrol" -NewName "Komplete Kontrol"
