### ISSUE TITLE
[Push 2] Record a clip without overdub

### ISSUE THREAD

**Issue by cgestes** [git-moss/DrivenByMoss#376]
Hi,

thank you for this awesome project. I am wondering if it is possible de record a clip without overdubbing once the recorded pattern has recorded for the intended time?

It seems possible to click on a clip in the session view, I would like sometime more direct. 
If it is not there, would you mind giving me some direction to get me started implementing it?  (If this is a desirable feature). 

My usecase: record clips in live and play them, like with a looper.

**Comment by git-moss** [comment]
There is a kind of looper on the foot pedal options for the Push. You can give this a shot. But I did not fully understand what the workflow is you are looking for.

**Comment by cgestes** [comment]
Foot pedal option? I’ll give it a look. 

My workflow:
-> press record with a fixed clip size defined
-> wait for the recording to be active (start of next bar usually)
-> play for the duration of the clip
-> expect the recording to go inactive after the length of the clip
-> play one or two extra notes at the beginning of the next bar that should have not been there without messing up the recording. (Especially when recording at fast tempos)

from what I understand currently we do: next clip + overdub to record. I would like the same behaviour as clicking an empty armed clip without overdub assigned to an easy accessible button. (New or record without shift).

I hope this is clearer.

**Comment by git-moss** [comment]
Thanks. Yes, that's the "classic" looper functionality. As I said, check out the footswitch looper option to see if this fits your needs.

**Comment by cgestes** [comment]
Does it do anything without a footswitch controller? It doesn't seem to have any effect.

**Comment by git-moss** [comment]
Does your footswitch work with any of the other functions?

**Comment by cgestes** [comment]
I don’t have a foot switch. I would like to use the push 2, exactly like I
would do in Ableton live.
