### ISSUE TITLE
Beatstep: Parameters are moving too fast

### ISSUE THREAD

**Issue by mismosmi** [git-moss/DrivenByMoss#377]
Hi,
I just got a bitwig license and a beatstep because I've been kind of excited about this controller script making the beatstep a _very_ useful controller for bitwig.

Now I've hooked it up, both with the latest version, loaded the midi setup with midi control center and installed the driven by moss extension. Everything is recognized correctly in bitwig but parameters are moving by about 56% per click which makes all the parameter controls pretty much useless, see attached video.

Is there maybe something I can do about this myself? Is there some config value to adjust this?

Also the lights are pretty messed up in most modes but I don't care too much about them, there was already a disclaimer in the docs that they can be tricky...

https://github.com/git-moss/DrivenByMoss/assets/26325283/24b6100a-43db-4861-a377-60a1bae47153

**Comment by mismosmi** [comment]
Okay, I figured this out on my own.

The values do not arrive in a twos complement format anymore for some reason, they're just offsets from 64 so the ValueChanger's `decode` method must be just `control - 64` and then it works.

**Comment by mismosmi** [comment]
I can come up with a Pull Request if that's appreciated around here :)

**Comment by mismosmi** [comment]
Just noticed I just need to use the `OffsetBinaryValueChanger`, probably not worth the effort of opening and reviewing a PR at that point.

**Comment by git-moss** [comment]
Thanks for reporting, will be fixed in the next update!
