### ISSUE TITLE
Bug: SN30 Pro gamepad B-button not working with PS4 gamepad setup

### ISSUE THREAD

**Issue by madskjeldgaard** [git-moss/DrivenByMoss#378]
Hi! 

Thanks again for your amazing work here. It is incredible! 

I just tried the gamepad integration and it is _very_ cool. I've got a 8bitdo Sn30Pro with me here and it works somewhat with the PS4 setup included, but not fully. I suspect there are some mismatches in HID info. It would be awesome if you could support this controller as well. I am not sure what info you need, but I traced out all the buttons and sticks using SuperCollider and included the page, id and usage numbers for each element. Let me know if you need anything else to do this, and if at all you're interested. Thanks again for your amazing work :) 

**Ordered as Page, ID, Usage**

```
Left stick X: 1, 14, 48 
Left stick Y: 1, 15, 49 
Left stick button: 9, 10, 11

Right stick X: 1, 16, 50
Right stick Y: 1, 17, 53
Right stick button: 9, 11, 12

Select: 9, 8, 9
Start: 9, 9, 10

L1: 9, 4, 5
L2: 1, 19, 51

R1: 9, 5, 6
R2: 1, 20, 52

Home button: 9, 12, 13
```

Link to controller's manual: 
https://download.8bitdo.com/Manual/Controller/SN30pro+SF30pro/SN30pro+SF30pro_Manual.pdf

**Comment by madskjeldgaard** [comment]
And here is the HID info for the sn30pro gamepad retrieved via SC:

```
Usage name and page: 	GamePad, 	GenericDesktop
	Vendor name: 	
	Product name: 	Wireless Controller
	Vendor and product ID: 	1356, 1476
	Path: 	Bluetooth_054c_05c4_4a4ab5d8
	Serial Number: 	E4:17:D8:B5:4A:4A
	Releasenumber and interfaceNumber: 	256, -1
```

In case it's any use :)

**Comment by madskjeldgaard** [comment]
Actually, on further testing, everything seems to work fine with the PS4 setup, except for the B button on the Sn30pro, this has no effect with the PS4 setup.

**Comment by git-moss** [comment]
I use the Jamepad library for this: https://github.com/libgdx/Jamepad
And they user following gamepad database: https://github.com/gabomdq/SDL_GameControllerDB
I guess the database might be the right place to report this.
