### ISSUE TITLE
Device control can get stuck on changing tracks in Reaper

### ISSUE THREAD

**Issue by mortfell** [git-moss/DrivenByMoss#380]
Not sure if this is a bug or just a usability quirk from the difference between reaper and bitwig, but it would really help my workflow on the using the Push 1 with Reaper (which is otherwise really nice) if this could be resolved in some way. I also imagine this effects other controllers as well, but this is just the only one I have with a screen!

When in "Device" mode if you have an effect selected on one track and then move to another track. If the new track does not have an effect in the "slot" that was currently selected on the previous track. The push will give the message "Select a device or press 'add Effect'..."  this message will persist regardless of cycling through modes "device", "track", "volume" **until one of two things happens:**
- you move to another track that has an effect in the last accessed slot and select a lower slot which is available on the track you'd like to move to
- add enough effects to the track you'd like to move to that that it reaches to the slot that was previously selected on another track.

**To make sure I'm explaining this correctly here is an example of me using the push in a simple project:**
- i have a project with two tracks, 
- track one has one eq effect.
- track two has an eq, a compressor and a reverb
- If I'm on track two in device mode, I'm controlling the reverb in the 3rd slot and then I click on or move to track one, the push will not give me an option of selecting the eq but will have the message "Select a device or press 'Add Effect'... and I can not reach a screen that allows me to focus the 1st effect slot while on this track
- in order to edit the eq on track one I would have to, return to track two, select slot 1 on that track (the other eq) and then move back to track one and now the first slot will be focused.

**So suggestions for how to fix this if possible would be:**
- default to last available effect when changing to a new track that doesn't have as many effect slots active as the previous track?

**Comment by git-moss** [comment]
Thanks for reporting!

Will be improved in the next update:
If there are less plugins on the newly select track the first plugin will be selected. If there is no plugin on the track the index of the selected plugin is remembered until a track with at least 1 plugin is selected again.

**Comment by mortfell** [comment]
Awesome! Thanks
