### ISSUE TITLE
Reaper automation quirks with DrivenByMoss

### ISSUE THREAD

**Issue by mortfell** [git-moss/DrivenByMoss#382]
There are a few bugs or quirks I've noticed using automation with DrivenByMoss with a Push 1 in REAPER
Test with v22.2.0 and Reaper v7.08, but I've noticed these issues for a while just haven't had a chance to report.

I believe these would effect other control surfaces using driven by moss as well?? but I'm not sure as I can't really check.
The Push has really nice touch sensitive faders so could be excellent for automation in REAPER if some of this was adjusted :)

I think most of these are down to the differences in the way Reaper handles automation vs Bitwig and some of them may in fact be Reaper bugs.... as such I'm not sure how doable it'd be to change, but I'll document them here just in case it's possible. If there ARE things that are in fact down to REAPER to improve I can then make bug reports for them.
I've done my best to try and explain this clearly and give examples but let me know if something I said is unclear.

### Volume/Pan/Send values jumping when writing automation.
I think this stuff all comes down to DrivenByMoss not taking into account the way Reaper handles "trim" automation for track controls. In Reaper, automation of Volume/pan/sends is always written to a "trim" lane. (I'm not aware of a way to use width with driven by moss but if it is possible, i'm sure it'd react in the same way)

So as an example, once you start writing volume automation, the current level of the fader is transferred to the trim lane and the "main" fader will reset. This happens with Pan, Send and Width as well. Once you write automation and go back to read mode, the automation will go to it's own lane and operate relative to whatever you set the fader or pan knob. When you re-enable automation writing it will write back to the already written lanes. The "main" track controls that appear when "not" writing automation are a separate master level, automation envelopes are relative to that.

**The current behaviour in driven by moss:**

**When in latch mode:**
When you write volume/pan/send automation for the first time using latch mode the automation will start from the correct value and write accurately. If you let go of the knob, automation will continue writing from the value where you stopped. (all good so far)

If you grab the knob again or disable and re-enable latch automation, the value will not continue from where you left it (which is the expected behaviour for latch) but always get it's start point from the "main" volume/pan/send amount and jump to that value. For instance, if the main volume fader is set to -6, every time you grab the volume knob while writing latch automation the automation will jump to -6 regardless of the level of the automation envelope. 

![latch](https://github.com/git-moss/DrivenByMoss/assets/4732794/2ed8b121-af37-49de-a62d-37bb55dc91ad)

**When in write mode:**
pretty much the same as latch, volume and pan values will continue writing from where you left them but jump to the setting of the main controls when touching the knobs again.

**When in touch mode:**
In touch mode, starting automation works the same as with latch and releasing the knob will cause automation to stop writing and return to the automation envelope. (expected behaviour so far) 

Once touching the control again the value will (instead of starting from where the volume/pan/send envelope currently is) jump to the last "touched" value and then if you move the control, jump to the main control value (as with latch and write mode).

![touch](https://github.com/git-moss/DrivenByMoss/assets/4732794/f18eeb6d-4d27-4171-81cc-5019fdc2f1e1)

**The volume and pan readouts on the display always show the main level of the controls and never the level of the volume/pan/send automation envelopes.**
The numerical readouts only show the "main" volume and pan levels, never the automation level. The rectangular indicators under the numerical value will show the currently writing level while touching the controller but revert to the main level once releasing the knob.

**Proposed solution:**
It would appear that in all these cases Driven By Moss isn't aware of the value of the trim envelopes. 
1.) If there was a way for the script to be aware of the trim envelopes and receive feedback from the envelopes when in automation modes I think that would fix the issues??

2.) Not "essential" but If the value readouts for volume and pan showed the "main" volume when in read or read/trim mode but switched over to current automation envelope values when automation modes were enabled, that would help with usability during automation writing.

### Device parameters don't release in touch mode

Automation works totally fine with devices, there is no trim automation for those so, everything works as expected.
However, when in "touch" automation mode, device automation reacts the same as latch mode. Releasing the knobs doesn't stop automation from being written.

Not sure if this is a Reaper issue... I know Reaper still has some quirks of it's own with automation and it's possible fx parameters aren't able to work properly in touch mode. I don't have any other touch sensitive controls to try, but might be worth a look.

### Testing in Bitwig
All of this stuff works flawlessly and as expected in Bitwig, touch and latch both work correctly with all volume, pan, sends and device controls, so I'm sure it's just down to the way things are being translated for Reaper.

**Comment by git-moss** [comment]
I am afraid I have no idea how to improve this. It has nothing to do with Bitwig.
Basically I only tell Reaper to do automation. But I had to implement some tricks to prevent jumps due to fader feedback.

**Comment by mortfell** [comment]
Thanks for your response! Ah sorry if my post was confusing I'll try and explain more simply.
This "should" be possible to remedy because other control surfaces interface with this aspect of Reaper and everyone is using the same open API to build controller support AFAIK?

Based on your response, my question would be:
is it possible the tricks you've implemented are preventing DrivenByMoss from updating the volume/pan/send levels when writing automation? This could explain the issues I'm experiencing. 

In Reaper. When _writing_ automation for track specific controls (volume/pan/send/width),  separate trim automation values are used, these are created when writing automation and activate or deactivate based on the automation status of the track. This CAN sometimes result in jumps for controls when activating and deactivating automation.... which is the intended behaviour but is confusing if you aren't used to it.

Here is a simple video demonstrating using touch automation in Reaper with a moving fader controller that works as intended:
https://github.com/git-moss/DrivenByMoss/assets/4732794/bed65276-c2e9-426d-9119-fc2519006cb0

I referenced Bitwig because this is not at all how Bitwig works and I know DrivenByMoss was created with Bitwig in mind. If you are trying to match the behaviour it's easy to see how the the Reaper way could seem unintuitive or like a bug if you aren't expecting it. 

thanks!

**Comment by git-moss** [comment]
For the basic automation there are specific CSurf_SetSurface* functions (e.g. volume) but they do exist only partially, e.g. not for parameters. This explains the difference between different automations.
Regarding the "tricks" I mentioned, this means only with regard to when moving the fader to not get a feedback loop. This is quite tricky since I have these 2 levels of C++/Java code and this might cause some little delays.
Therefore, I am afraid that I currently have no idea what to improve in this area.
