### ISSUE TITLE
Playing scenes on Push3

### ISSUE THREAD

**Issue by voronizer** [git-moss/DrivenByMoss#384]
While pushing scene button (1/32t,1/32, etc.) on Push3 it expands track group.

In scenario when group contains a lot of tracks it makes other track clips unreachable via pads and has to be scrolled thru right/left arrows. It obstructs workflow a little bit. It will be better if track groups stay closed when play scene.

**Comment by git-moss** [comment]
I agree but this is controlled by Bitwig. Please report to support.
