### ISSUE TITLE
Electra One: channel labels on mixer page do not redraw correctly when switching banks

### ISSUE THREAD

**Issue by adamschabtach** [git-moss/DrivenByMoss#385]
Cosmetic issue: when switching between banks of channels in the mixer page, the channel labels at the top of the LCD do not redraw correctly if the label on the previous bank has more characters than the label in the current bank. For example, suppose the label for the first channel is "1: Bass" and the label for the sixth channel is "6: Trombone".  "1: Bass" is initially drawn correctly. Switch to the second bank and "6: Trombone" will replace it correctly. Then switch back to the first bank and the label will be something like "6: Tr1: Bassne". (That's a made-up example; the exact result for those two strings might be different.)

**Comment by git-moss** [comment]
Looks like a drawing issue to me. Will report it to Electra One team.
