### ISSUE TITLE
Komplete Kontrol MK2 flip track but does not select the instrument on the keyboard

### ISSUE THREAD

**Issue by nicolasbadia** [git-moss/DrivenByMoss#386]
When I select a track in Bitwig, my Komplete Kontrol S88 MK2 does not update the screen and the light guide accordingly to the Komplete Kontrol instrument related to the Track:

<img width="514" alt="image" src="https://github.com/git-moss/DrivenByMoss/assets/477089/901fcf7f-d4d7-4f94-9cff-ad468ba3baf7">

Here is my configuration :

<img width="596" alt="Capture d’écran 2024-03-02 à 15 27 35" src="https://github.com/git-moss/DrivenByMoss/assets/477089/a6feac86-5b43-41bc-9467-730db185002f">

I'm just wondering if it's a bug, a configuration mistake or if it is just not supposed to work...
I'm pretty sure it was working with Bitwig 4 and the build-in controller.

I'm using Bitwig Studio 5.1.3 on Mac M3 with macOS 14.3.1

**Comment by git-moss** [comment]
What is your plugin isolation setting?

**Comment by nicolasbadia** [comment]
In Bitwig

<img width="605" alt="image" src="https://github.com/git-moss/DrivenByMoss/assets/477089/cdc6a7e9-9864-47a2-abc2-c22f8ee208fd">

**Comment by git-moss** [comment]
It seems to only to become active if PLUG-IN is selected.

**Comment by nicolasbadia** [comment]
I just tried it, but still the same problem 😞

**Comment by git-moss** [comment]
Hmm, sorry no real idea, works fine for me. I will release an update soon with Mk3 support. Maybe this changes something but do not think so.

**Comment by git-moss** [comment]
The NI hardware layer identifies the instance via the name of the 1st parameter (horrible idea).
The first device should "NIKB00", the second "NIKB01" and so on. Is this the case?
![grafik](https://github.com/git-moss/DrivenByMoss/assets/3090132/af621f47-88a3-4ab0-8654-9b78dd6e1ab8)

**Comment by nicolasbadia** [comment]
I guess you found the problem, they are all named "NIKB00".  But I can't find out how to change it... Any idea?

**Comment by git-moss** [comment]
The only reason I know is plugin isolation because then they cannot "talk to each other".
Even if "Within Bitwig" should work fine, try e.g. "Together".

**Comment by nicolasbadia** [comment]
I tried all isolation mode, it always creates the instrument with NIKB00 even on the same track...
I guess it's a Bitwig issue. I will contact them...
Thanks a lot for identifying the problem.

**Comment by git-moss** [comment]
Out of curiosity I tried on my test Mac Mini which is Bitwig Studio 5.1.5 on Mac M1 with macOS 14.3.1 and Komplete 3.1.2.
Works fine.
