### ISSUE TITLE
Akai APC 40 MKII - overlay text is offset by 1 when pushing the 'sends' button

### ISSUE THREAD

**Issue by fdellavedova** [git-moss/DrivenByMoss#389]
Hello!

when I click the 'SENDS' button on the APC40, the overlay shows 'Send 1: Pan' instead of the first send effect. Pushing the button again show the name of the previous FX send in the overlay.
This can be reproduced also by pushing the 'PAN' button and then again the 'SENDS' button. Likewise, when pushing the 'USER' button and then the 'SENDS' button, the overlay shows 'Sends 1: -' and then the name of the send, again offset by one.

**Comment by git-moss** [comment]
Thanks for reporting! Will be fixed in the next update.
