### ISSUE TITLE
Cant access to your download site

### ISSUE THREAD

**Issue by Vocllum** [git-moss/DrivenByMoss#390]
I am from China and unable to access your site using a VPN, and neither can my friend. 
Thank you for your excellent work but it is unfortunate that we are unable to use it. 
I hope you can provide a way to download the tool without accessing your site. 
Thank you again.

**Comment by RichNts** [comment]
Yeah, the site seems to be down.

**Comment by git-moss** [comment]
Seems my DNS provider is down (they created a swimming pool in their computing centre).
For the time being you can reach the server directly: https://92.205.106.63/ (you have to ignore the SSL warning).

**Comment by Vocllum** [comment]
Thank you very much! That's very kind of you.

**Comment by Saber540** [comment]
Yes, down since last week.   Any other place to get Bitwig 5.0.4 extension?
