### ISSUE TITLE
Feature Request - Generic Flexi - additional clickable "Helpfile" / Function Overview

### ISSUE THREAD

**Issue by hoergen** [git-moss/DrivenByMoss#391]
In the overview of the controllers, there is the functino to click on the question mark, to open the Driven By Moss manual. Is it possible to add another icon or replace the link to the manual to another file?

![01_temp](https://github.com/git-moss/DrivenByMoss/assets/24474762/320c10f3-db39-48fb-88e3-3002788edd48)

So you could open an functions overview you created especially for your controller with the Generic Flexi, instead opening the DrivenByMoss manual. The operating System then needs to handle which application has to open the file.

The additional Helpfile or Function Overview should have the same name like the Generic Flexi FILENAME(.properties) and has to be in the same directory.

For example this would just open a image viewer

![02_temp](https://github.com/git-moss/DrivenByMoss/assets/24474762/789f9a02-ed9e-4996-8a0c-e432001d1f36)

LG Odo

**Comment by git-moss** [comment]
(from memory) this needs to be a PDF which is inside of the extension JAR. So no.
