### ISSUE TITLE
Launchkey Mk3 "..." function isn't working...

### ISSUE THREAD

**Issue by VonAntesberg** [git-moss/DrivenByMoss#394]
I've gone through the manual and restarted Bitwig, but I'm still having this issue: I hit the "..." button to pull up the browser, but instead the LCD just cycles through "Program 0-127". I'm not sure what's going on with this particular issue. I'm running Bitwig 5.1.8

Any help would be wonderful. Thank you so much for all your work on this extension. I've been enjoying thus far but for this one little issue.

**Comment by git-moss** [comment]
Just tested and it works fine for me. Did you install the latest Firmware? Are you sure you are running DrivenByMoss and not the Bitwig implementation? What is your OS?

**Comment by VonAntesberg** [comment]
Yes. When I plugged in the launchkey Butwig gave the option to select their implementation or yours and I selected yours. Everything is up to date. And I’m running the current version of macOS.

**Comment by git-moss** [comment]
Just to be sure, I tried on macOS and it works well. Also tried the Bitwig script which shows the cursor keys as well.
No idea, why this button would send Program Changes. Can you maybe do a video?
