### ISSUE TITLE
2 Issues: 1. Generic Flexi 2. APC40mk2

### ISSUE THREAD

**Issue by konkrete** [git-moss/DrivenByMoss#397]
2 Issues:
1. Generic Flexi with MIDI Fighter Twister [FX track: FX track selected: Set send 1] and [Track: Track Selected: Set send 1] both options don't work on FX tracks,
however does work on regular tracks.
2. APC40mk2 by Moss [action for pressing rec armed empty clip: Create new clip] turns ON overdubbing, that contradicts the mission of that function, because there is "start recording" option for it.
Mac OS 12.7.2
Bitwig Studio 5.1.9
Here is the video:
https://youtu.be/hHo5iUibVMY

**Comment by git-moss** [comment]
1. Works fine for me. Note that to make "FX track: FX track selected: Set send 1" work an FX track needs to be selected. To make "Track: Track Selected: Set send 1" work you need to have toggled to the FX track bank with "Track: Toggle Trackbank".
2. No. The difference is that "start recording" starts recording and you ahave to press it again to stop recording. "Create new clip" creates a new clip of a specified length and turns on overdub, so you can record into it.
