### ISSUE TITLE
Push (1) browser issues with Auto-select drum settings: channel

### ISSUE THREAD

**Issue by jasalt** [git-moss/DrivenByMoss#399]
- Version: DrivenByMoss-23.2.2
- Controller: Push 1
- Bitwig 5.1.9 (at least, and up to latest 5.2b7)

There seems to be some inconsistency between note modes "Drum64" and "Drum" when browsing drum machine presets while previewing them by playing pads if "Auto-select drum settings:" is set to "channel".

On "Drum64" note mode, after selecting a new preset in browser and pressing 2 different keys on Push, the browser exits while giving focus to the specific drum machine channel on the Push screen. This seems to happen on all operating systems I tested including Windows 11, when in addition it often crashes Bitwig on Linux (Debian/Ubuntu) and MacOS.

On "Drum" note mode, after selecting a new preset in browser and pressing 2 different keys on Push, it keeps the browser open, allowing to preview multiple presets normally by pressing 2 or more pads.

Issue is not present when the "Auto-select drum settings:" is set to default "Off", as expected.

Also there seems to be another issue with all operating systems with browser crashing at times after it has eg. reseted to global context (browsing all devices instead of drum machine presets) when exiting the browser with ESC key, but I didn't quite understand yet if it's related to the controller script.

There seems to be some related controller API bugs causing these crashes, and I've send some bug reports to Bitwig about it and linked this issue also.

**Comment by git-moss** [comment]
Thanks for the info but I am afraid that Bitwig needs to address this. Since you did report to them as well, all good. :-)
