### ISSUE TITLE
APC 40 MKii 'user' controls

### ISSUE THREAD

**Issue by RobinFen** [git-moss/DrivenByMoss#4]
Hi Moss. Thanks so much for all your work on the new Java controller scripts. 

I really like the way grouped tracks can be collapsed/expanded.

Has the 'user' controls functionality been removed? When I press the USER button it selects send2. Is this a bug or a feature?

Also in the previous version of the script I was able to map the device controls, whereas now if I map those, they behave a bit randomly. Sometimes they work correctly, sometimes the value is locked to 0, and sometimes the value jumps back to 0 after a certain amount of time.

**Comment by git-moss** [comment]
> When I press the USER button it selects send2.

Yes, that is how it works now. Did forget to document that.

> Sometimes they work correctly, sometimes the value is locked ...

Can you give a specific example? I know that there are some bugs with some specific parameters, e.g. with the Arp device: https://github.com/teotigraphix/Framework4Bitwig/issues/105

**Comment by RobinFen** [comment]
HI Moss, thanks for replying. For me it's a shame the user controls have been removed as I use them a lot, and there are other ways to select send 2, but OK, understood.

Tonight I will try and get you a more reproducible bug for the device controls.

All the best,
Robin
