### ISSUE TITLE
Quantizing with Shift + Pad 5,6 (Machine MK3) in BItwig arranger

### ISSUE THREAD

**Issue by gitopandi** [git-moss/DrivenByMoss#402]
I use the Machine MK3 with Bitwig 5.2 Beta 8.
In the Clip Launcher I'm able to use Shift +  Pad 1, 2, 5, 6, 9, 13, 14, 15, 16 within the Piano Role.
In The Arranger I have only Pad 1,2 available and cannot quantize midi notes with the pads.

It seems not a limitation in Bitwig? Do you have any suggestions?

Thanks and best regards
Andreas

**Comment by git-moss** [comment]
You cannot access clips in the arranger via the API. This is broken since Bitwig 2(!). Complain to Bitwig...
