### ISSUE TITLE
Electra-One: Enhancement - ignore E1 pot touches after switching to a different device E1 preset

### ISSUE THREAD

**Issue by rjsmith** [git-moss/DrivenByMoss#403]
Hi,
I am developing an Electra-One preset and associated [VCVRack plugin](https://github.com/rjsmith/rsbatech-modules) to control VCVRack patches from the Electra-One. Inspired by your E-1 Bitwig preset, I have implemented similar multi - pot touch combos for triggering additional actions, which work as nicely as they do on the DbM E-1 preset.

I am now testing my E-1 preset controlling VCVRackPro VST plugin devices in Bitwig (Bitwig 5.2 beta 8) alongside the DbM E-1 controller preset (v23.2.1).  My E-1 preset is called "VCV Rack 2", so the DbM controller script automatically loads my E1 "VCV Rack 2" preset when I switch to the device page (which is great!).

The problem is that the E1 pot touches are still being fed back and processed by the DbM E1 controller script, even though my E1 is no longer running the DbM preset. For example, I have a specific combo of pots 7,8,9 in my E-1 preset that switches to page 12 of my preset (in my preset lua code). But when I press pots 7,8,9, the DbM script sends a signal back to my E1 to change to page 5. 

**Would it be possible for the DbM E1 controller script to ignore / skip processing E1 pot touches if the controller script has switched to a different E1 preset ?**  Or maybe make that an option (if it works OK for other less complex E1 device presets) ? 

I think it is triggered at this line of code:

https://github.com/git-moss/DrivenByMoss/blob/02b580a0784f63efd386900faff5bebcc53c3dfd/src/main/java/de/mossgrabers/controller/electra/one/controller/ElectraOneControlSurface.java#L759

Thanks!

**Comment by git-moss** [comment]
They need to be active to listen to the combination to be able to return to the DBM template.

**Comment by rjsmith** [comment]
OK thanks, I think I understand the problem.  I will have a think how DrivenByMoss + other VST - specific E1 presets can co-exist in this way. I understand the next E1 firmware version may allow access to the hardware buttons which may give more options. Maybe some special button +pot touch combo could be used to switch the DrivenByMoss preset back to active mode again.
