### ISSUE TITLE
Performance when controlling multiple parameters continuously

### ISSUE THREAD

**Issue by WolfgangBorchertTechnik** [git-moss/DrivenByMoss#405]
Hey  everyone,
i noticed a sharp rise in cpu load when controlling multiple parameters at once.
I testet controlling the first 8 track volumes continuously via an external programm and the cpu load jumped from around 15 % to around 50%.
I tried mitigating this problem by lowering the value resolution, but it didn't help much.
The pc i'm running doesn't have the best spec, but considering that i tried the same thing with Ableton OSC and the cpu load only jumped by around 2% i was wondering what the reason for this might be.
Maybe my setup is just wrong or it is an bitwig internal thing and doesn't have anything to do with the extension.
I'm using bitwig on windows and controlled it via OSC

**Comment by git-moss** [comment]
Unless it causes you issues I would simply ignore it. What are the specs of your PC?

**Comment by WolfgangBorchertTechnik** [comment]
Spec:
Windows 10 (22H2)
i5-7400
8 GB Ram

I would ignore it but i'm concerned that if i add more processing and devices I'll overload the cpu and then sound triggers will be dropped or the processing gets all glitchy.

**Comment by git-moss** [comment]
Would be worth testing because the processor load is not always that trustworthy. Sometimes it increases a lot and that only a little afterwards.

**Comment by git-moss** [comment]
If this still causes you issues, please address this to the Bitwig support.
