### ISSUE TITLE
Save/Load projects from Push2/OSC

### ISSUE THREAD

**Issue by thomasgirault** [git-moss/DrivenByMoss#406]
Hi, 
First of all, thank you for your project. 
I'm learning Bitwig and using a Push 2 controller that I want to connect to a Mini PC.
I feel more creative without a screen, so, I would like to load and save projects from the Push 2.

I saw in your documentation that Push 3 already has specific "File" and "Save" commands enabled. 
Would it be possible to adapt it to Push 2? Could you suggest relevant parts of your code that I could adapt? 

Alternatively, I already managed to save the current project with the OSC [/project/save] command. Ideally, it would be nice to also have commands like [/project/save path] and [/project/load path],  so, I could manage my projects from my phone.

**Comment by git-moss** [comment]
Since the Push 2 has no dedicated buttons for these functions, were do you suggest to put them?

**Comment by thomasgirault** [comment]
It is not ideal but would it makes sense to access to these function from the User or Browse button ?

**Comment by thomasgirault** [comment]
I don't know how you implemented that with the Push 3 but a default file name based on curent datetime could be autogenerated. 
It would avoid to implement a full QWERTY keyboard for file name edition.

**Comment by git-moss** [comment]
Push load/save will be in the next update.
OSC: Triggering load/save with a path is not possible. The "normal" load/save commands can already be triggered via actions.
