### ISSUE TITLE
Feature Request for Push 1 (If that's ok)

### ISSUE THREAD

**Issue by 0b1kn00b** [git-moss/DrivenByMoss#408]
I'd like to have on/off switches for individual effects but the sustain pedal doesn't feed back into the lights of the controller.
There's no way to leave a visual record of what effect is on or off. 
Toggle notes with persistent lights in sequent formation would give much more flexibility than program changes with immediate feedback.
tap pad for note on, light comes on, tap again for off, and Note Grid can do the rest.
Is it doable?

**Comment by git-moss** [comment]
You could try to use Clips which contain automation data to turn on/off devices.

**Comment by 0b1kn00b** [comment]
This way of approaching it gets pretty ugly pretty quickly because of combinatorial explosion (5*4*3*2)
