### ISSUE TITLE
TouchOSC on IPad Cant find Bitwig OSC server over Wlan, but receives messages from Bitwig

### ISSUE THREAD

**Issue by jderiz** [git-moss/DrivenByMoss#409]
Hi, 
great Work, thanks for this elaborate framework.  
I am running into problems when trying to receive OSC messages from my Ipad in Bitwig. 
This starts with TouchOSC on the Ipad not finding the Bitwig OscServer through zeroconf(not sure if thats implemented on the bitwig api side of thing?). I can however find the Protokol Server running on the same machine on a different port through zeroconf on the Ipad. 
Furthermore, Sending messages from Bitwig to the Ipad works without Problems. So when i Hit play in the DAW the Ipad TouchOSC view updates accordingly. 
The server seems to be created correctly and the extension reports its listening on the right port. I can reach it through touchOSC running on the same machine on 127.0.0.1 on the port setup in the extensions configuration. 

I am sure theres a major human error on my side, but ive been trying to debug this for two nights now... Any hint is greatly appreciated. I can attach the OSC monitor output if needed but it pretty much states what ive just tried to explain, I am also happy to add any further logging in the source recompile and report back.

**Comment by git-moss** [comment]
I hope you could fix your issue. Sadly, I cannot help with network issues.
