### ISSUE TITLE
highlight selected device

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#41]
I noticed when we open the device panel with osc and go through the devices (/device/+ and /device/-), the bitwig gui does not give a 'selected device' notification for that.

Is there something we could do about that?

**Comment by git-moss** [comment]
No, the highlight focus is only ment for mouse interaction.

**Comment by kdejaeger** [comment]
Then why does this sometimes work, and sometimes not?

**Comment by git-moss** [comment]
No idea. Maybe when you change a track?

**Comment by kdejaeger** [comment]
I think so, then it get's focused by bitwig and then the ../-  ../+ OSC commands also change the focus to the next device.
