### ISSUE TITLE
OXI One Latency

### ISSUE THREAD

**Issue by thorinside** [git-moss/DrivenByMoss#411]
Thanks so much for the OXI One support, I've been playing with it all evening. One thing I notice right away is how much latency there seems to be when tapping pads in Drum 128 mode. The sound doesn't get to me until sometime after my finger finishes travelling back up off the pad. I would make a guess that it is almost 100ms of latency.

Is there any way to reduce this? Maybe something like more infrequent updates to the display? Something?

**Comment by git-moss** [comment]
I cannot reproduce that. Did you check your audio latency settings? What is your OS?

**Comment by thorinside** [comment]
Audio latency was 256 samples at 48k. MacOS. M1 Pro. I'll see if I can
figure out what I was doing wrong, otherwise will close the ticket.

**Comment by git-moss** [comment]
In my opinion 256 is too high for playing drums. Try 64.

**Comment by thorinside** [comment]
Sounds good will do.
