### ISSUE TITLE
Oxi One: Unable to distinguish between playing and queued clips

### ISSUE THREAD

**Issue by thorinside** [git-moss/DrivenByMoss#412]
In the Clip Launching playback when a clip is queued it blinks green, just the same as the playing clip. Perhaps a playing clip should be solid green, and a queued clip flashing green?

This is easy to repro if you make two clips and set one of the play random clip on stop modes. I often do this when making ambient stuff, where a clip will play, but the next will be queued up.

**Comment by git-moss** [comment]
I agree. Will be changed in the next update.
