### ISSUE TITLE
Oxi One: Keyboard Modes very bright

### ISSUE THREAD

**Issue by thorinside** [git-moss/DrivenByMoss#413]
In the keyboard modes, the lights are very bright so often it is hard to distinguish the lit root notes. Perhaps half this brightness level would be much better?

**Comment by git-moss** [comment]
I checked back with OXI and it is not possible to set the brightness. I already tried to keep it down but the number of colors is pretty limited. Only thing I could do is to add an option to turn off the non-root notes.

**Comment by thorinside** [comment]
I see, fair. I wonder if shades of grey work? But otherwise, no worries.
Thanks.

**Comment by git-moss** [comment]
Thefre is exactly 1 shade of grey :-)

Just added that you can switch off the in-scale notes in the next update.

**Comment by thorinside** [comment]
Well, then that will have to do. Thanks.
