### ISSUE TITLE
Akai Fire pad leds in Drum 64 mode misplaced

### ISSUE THREAD

**Issue by pthex7** [git-moss/DrivenByMoss#414]
Hi. I've been using Driven by Moss since bitwig 4.2 with my Akai Fire without any problem (thank you for your work), but I just installed bitwig 5.2 as well as this latest version of DrivenbyMoss extension, and there is a misplacement of pad leds inside the drum 64 mode. They are lit 3 octaves above, meaning C1 is on C4, but it can be still played in the same place. It just doesn't correspond the pad led to the midi note.

**Comment by pthex7** [comment]
I just checked it gets corrected after creating a new drum machine. It only happens when opening a project that already has a drum machine in a track.

**Comment by git-moss** [comment]
Thanks for the update, I was just about to look into that!
