### ISSUE TITLE
Question: Push 3 and 'Reaper Playtime 2' support? Playtime is Abletons/Bitwigs session view. 

### ISSUE THREAD

**Issue by godfatherjohn** [git-moss/DrivenByMoss#415]
The Playtime -- now Playtime 2 ([here](https://www.helgoboss.org/projects/playtime)) -- extension enables session view in Reaper, which is very reminiscent of Ableton's and Bitwig's session views. Would it be possible to get this supported in Push 3?

**Comment by git-moss** [comment]
Sorry, no. I looked in this a bit and I am in touch with the author as well but this would be huge task since the concept is completely different.

**Comment by godfatherjohn** [comment]
Okay, thanks for getting back that quickly. BTW, your work/project is nuts (the positive nuts). You should at least have a 'donate' button somewhere.

**Comment by git-moss** [comment]
There is a THANKS button below each of my videos :-)

**Comment by godfatherjohn** [comment]
Hi again. I haven't used the software yet ..haven't even bought any gear etc. but it will be Reaper and probably either LinnStrument or Push 3. ... I will def. donate to your project (those £ ~10 won't kill me) , no matter whether I will use it or not. One more question on my part, would it be possible to integrate Playtime 2 by a joint community effort? I have not looked into any of this. I have just been doing some "research" in my very limited spare time.
