### ISSUE TITLE
Control parameters (e.g.) "Use faders like editing knobs" from different OSC

### ISSUE THREAD

**Issue by SmutjeHannes** [git-moss/DrivenByMoss#416]
Hey Jürgen,

first of all, thanks a lot for your amazing work!

One question though:
I am using your plugin to control an QConProG2 which works fine. Now I got a stream deck and want to use it for its amazing visibility to control Reaper via OSC. 
Do you think it's possible to send a command from the streamdeck  via OSC(or midi) to enable something like "Use faders like editing knobs" on my QConProG2? 

It would be such a charm to select a track in reaper, on my streamdeck update all the plugins on that track on the buttons and when I select button 2, which selects FX Nr.2 and opens the GUI for FX 2 then my QConProG2 would turn into flip mode and select device plugin parameters. 

Right now I only get till "opens the GUI for FX 2"... so, is there a way to hack into the communication of my MCU?

Many thanks in advance,
Hannes

**Comment by git-moss** [comment]
You can create a virtual MIDI port (don't ask how to do this on Linux but should not be too hard) and merge either the QCon input or the output with the MIDI output of your steamdeck. Then you can send the respective MCU command for toggling the knobs.
