### ISSUE TITLE
Launchpad Pro MK3 hard crash in clip loop edit view

### ISSUE THREAD

**Issue by eljeff** [git-moss/DrivenByMoss#417]
Howdy - thank you for such an awesome extension.
I hit a hard crash while trying to edit the clip loop points using Launchpad Pro MK3 and latest DrivenByMoss version 24.2.0
1) select any clip
2) press 'custom' to get to the loop editing page
3) press the (unlit) down arrow

Launchpad will crash with this error:
`Missing cursor key down handling for view`
Clicking 'restart' brings everything back up as normal.

I stumbled on it organically, trying to finely edit a loop point point in the highest-resolution view to something higher than bar 5.
Thank you again - just thought you would want to know about this crash.

**Comment by git-moss** [comment]
Thanks! Will be fixed in the next update!
