### ISSUE TITLE
when any controller is active using driven by moss, all notes played from clips are displayed in screen and push display

### ISSUE THREAD

**Issue by henning** [git-moss/DrivenByMoss#419]
I noticed recently(I think that didn't occur a few weeks or months ago - very coarse, as I'm not a super regular user) that, as soon as any controller or keyboard that uses driven by Moss is active, all notes being played from running clips are shown in the middle of the computer monitor, and also in the display of the Push2 that i'm using.

I find that quite confusing to have things constantly flickering on my screen, and also dont have an idea of what i could use it for. Therefore to me, this feels more like a bug than a feature.

It seems to be specific to driven by moss controllers, as It doesn't happen when I turn all these off but keep one controller on that I use with the bitwig drivers.

It seems also not to be driver specific, as i get the effect as soon as any controller is active using driven by moss (I tried Launchpad pro mk2, Push 2, Launchkey mini mk3).

Is there any way to turn this off?

I tried to find any setting that could be used to turn it off, but I dont see which one could be it.
Turning off "Visualize controller interactions on screen" - even though showing notes played from clips isn't really a controller interaction - didn't help.

**Comment by git-moss** [comment]
Yes, look for "Notify played chords".

**Comment by henning** [comment]
Well, I searched again and found that the setting is "notify played chords" .

I still think it's not correct to show notes played from clips instead of just notes played in the controller.
