### ISSUE TITLE
OSC: drum names

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#42]
I'd like have a OSC url to fetch the name of a drum/pad, if not too much work.

**Comment by git-moss** [comment]
Should be already in /device/layer/{1-8}/name

**Comment by kdejaeger** [comment]
Why is it not from 1-16 since there are 4x4 drum buttons?

**Comment by git-moss** [comment]
Will be in the next version.

**Comment by kdejaeger** [comment]
I see there's a /device/drumpad/x/name now.
However the check "if (cd.hasDrumPads ())" is not always true when selecting a track that has a drumrack.

First when bitwig is started and you select the track for the first time, it send it out /device/drumpad/x/name. After a few track changes it does not send it out anymore.
