### ISSUE TITLE
Push 1 Drum 4, 8 & XoX not paging through clip

### ISSUE THREAD

**Issue by 0b1kn00b** [git-moss/DrivenByMoss#422]
I understand Drum uses the lower right quadrant of the 8x8, but the d-pad l/r should handle Drum 4, Drum 8 and Xox if I'm reading the documentation right.

**Comment by git-moss** [comment]
Not sure if I understood your question but to change pages on the Push 1, use the Page Left/Right buttons (on the bottom right side)

**Comment by 0b1kn00b** [comment]
That's right, I call it a DPad because there are the Up/Down buttons weaved in. 
Here's a demonstration.

https://github.com/user-attachments/assets/0fbd802f-4438-4994-bed0-91ff29719f7d

**Comment by 0b1kn00b** [comment]
That's been baffling me, thank you.
