### ISSUE TITLE
Add support for Novation Launchkey Mk4

### ISSUE THREAD

**Issue by syabro** [git-moss/DrivenByMoss#423]

**Comment by Cybolic** [comment]
This time, there's [an actual manual](https://fael-downloads-prod.focusrite.com/customer/prod/downloads/launchkey_mk4_programmer_s_reference_guide_v2_en.pdf) provided by Novation/Focusrite, so hopefully porting over the Mk3 support is doable even without owning the device.
My Mk4 Mini 37 is in the mail, but I'd be happy to help test support in the future.
