### ISSUE TITLE
Support for Launchpad Mini MK1

### ISSUE THREAD

**Issue by rrrnld** [git-moss/DrivenByMoss#425]
Hi there,

I saw this extension and was pretty stoked how feature-packed it is. I was hoping I'd be able to use a Launchpad Mini MK1 that a friend gave me after he didn't need it any more when seeing that DrivenByMoss brings support for the Mini MK3.

I opened Bitwig Studio 5 and it seems like there is some rudimentary support out of the box, allowing me to record some drums and trigger stuff in session mode, but it looks like the midi sequences are slightly off? The drum locations are not mapped one-to-one, there are some jumps and some things are mixed up. Similarly the session view is not mapped cleanly, but it appears rotated by 90° and mirrored horizontally (if I understand it correctly).

I'm quite comfortable with Java. If there's any way I could fork this and extend it myself I'd be happy to do it (and publish it, or send a pull request if that's useful), but in order to do that I would need some pointers where to start and how to find the different byte sequences that are part of the controller definitions (e.g. here: https://github.com/git-moss/DrivenByMoss/blob/50c70d5475419f4bcc1dcb22dbcc61bd44b7342c/src/main/java/de/mossgrabers/controller/novation/launchpad/definition/LaunchpadMiniMkIIIControllerDefinition.java#L23) and what they mean.

Thanks again for this extension, would be great if I could use it to bring some new life into my trusty old controller.

**Comment by git-moss** [comment]
I am not sure if the Launchpad Mini Mk1 has enough processing power for the task. The Launchpad 1 clearly hasn't.

If you are familiar with Java it shouldn't be too hard to find your way around to add the support. But please understand that I cannot support people in such tasks.
