### ISSUE TITLE
Push device not controlling reaper when green dot in drivenbymoss configuration

### ISSUE THREAD

**Issue by morandalex** [git-moss/DrivenByMoss#426]
I have an issue with my push

I installed reaper, latest version, on a ubuntu 20 workstation, with JACK installed via cadence toolbox, so I can use Catia to plug the routing outside the daw.

My audio sound card is a focusrite 18i8 2nd generation.

I installed driven by moss

I can see my connected device in drivenbymoss configuration plugin 

The dot is green.

BUT the push on the screen show only the word "PUSH" but it does not show what it should show.

So for the plugin the connection , all seems ok, but I cannot control reaper because on Push  the buttons seem not working at all.

any suggestions?

**Comment by git-moss** [comment]
Did you deactivate the MIDI ports in Reaper itself?

**Comment by morandalex** [comment]
I dont know If I understood correctly.
I mean, I deactivated ports as you can see in the  following scripts

are there other way to deactivate midi ports?

![image](https://github.com/user-attachments/assets/17b6ccb1-d947-46f7-9cb9-088178ca14bf)
![image](https://github.com/user-attachments/assets/780d2326-a607-413e-a3c7-472d43523eff)

**Comment by git-moss** [comment]
Yes, that is correct. But it seems they are all showing as "<not present>" which means that Push 2 is not detected by Reaper at all?!
