### ISSUE TITLE
[Novation LaunchControl XL] Enabling top 2 knob ros to control more parameter pages (device mode)

### ISSUE THREAD

**Issue by deescuderoo** [git-moss/DrivenByMoss#427]
For the LaunchControl XL, when in device mode, only the bottom row of knobs is active to control the current page of 8 macros on the current device. When there are multiple pages, I have to switch pages to be able to control them. The other top two rows of knobs are inactive. Is there a way to set the top 2 knob rows so that they control also other parameter pages? That way I can have 8*3 = 12 parameters at the same time. Thanks again!

**Comment by git-moss** [comment]
Bitwig has sadly still the limitation of 8 parameters per page.

**Comment by deescuderoo** [comment]
> Bitwig has sadly still the limitation of 8 parameters per page.

Thanks. This is indeed unfortunate. But what I meant was not so much to add more than 8 parameters to one page, but to map (say) the first 8-knob row to the first page, the second 8-knob row to the second page, and the third 8-knob row to the third page. 

I can *manually* assign knobs from the top rows to other inactive pages, so I can control multiple pages without switching to them, which makes me hopeful. However, the useful thing would be to have the script handle this to avoid assigning manually global mappings.

Thanks
