### ISSUE TITLE
NI Maschine Jam - Step sequencer resolution options limited by number of channels

### ISSUE THREAD

**Issue by hhalmet** [git-moss/DrivenByMoss#428]
When holding down Grid button in step sequencer mode, the group/channel buttons A-H should reflect the resolution options available  for the sequencer. However the number of options is mistakenly coupled with the number of channels in the Bitwig project. With 2 channels in the project, I can only choose between 1/4 and 1/4t. After adding another channel, 1/8 is made available and so on.

See #429

**Comment by git-moss** [comment]
Thanks!
