### ISSUE TITLE
osc: Punchin PunchOut changes

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#43]
Is there no way to just make a pull request for the following changes?: https://github.com/git-moss/DrivenByMoss/commit/70084c7cdf77a1edab72ef7ffcb937e99f7ff9d0

**Comment by git-moss** [comment]
No idea.

**Comment by kdejaeger** [comment]
Do I always have to commit in a new branch in order for you to automatically have a pull request?
Or can you somehow still cherry pick this changes?

**Comment by git-moss** [comment]
Since these are smaller changes, it would be easer for me if you just write a featrue request here.

**Comment by kdejaeger** [comment]
Will check out my commit.

It's just some extra code so that /punchIn/{0,1} and /punchOut/{0,1} works. Just like /repeat/{0,1}

**Comment by git-moss** [comment]
Will be in next version.
