### ISSUE TITLE
Add a way yo enter "per step" automation.

### ISSUE THREAD

**Issue by duarteoctavio** [git-moss/DrivenByMoss#433]
Hello! I'm moving back into Bitwing from my Elektron boxes and I can't find a way to enter data similar to their famous *"parameter locks"*.  

  A way to do it exists in the Ableton/Push combination called *step automation*, but I can't find it (or anything similar) in the totally awesome DrivenByMoss implementation for Bitwig. This video shows the [Live implemention](https://youtu.be/DdJabGICtzM?t=112).

  The intention is to be able to touch a note in the step sequencer and assign an automation value to it's step, which allows to be more precise when writing automation than live recording, which can be hard to do under some circumstances.

  If I can contribute in any way to develop the feature, please let me know. I'm a developer, but I don't have experience with JAVA, that's why I'm not attaching a commit, but I've already considered several times leaning into JAVA to be able to contribute to this controller.

**Comment by git-moss** [comment]
Sadly, step automation is not available in the Bitwig API. As a workaround you can at least use Timbre and Pressure which are available as note parameters (via note editing). Use the MIDI device "Expressions" and assign TIMB and PRES to whatever paramerter you like.

**Comment by duarteoctavio** [comment]
Thanks for answering!
  Do you know if I can ask Bitwig about this feature anywhere?
  I have faint memories of an official forum, but it seems to be gone now.

**Comment by git-moss** [comment]
Simply email to their support.
