### ISSUE TITLE
Creating a clip from OSC from a file path

### ISSUE THREAD

**Issue by 0x0f0f0f** [git-moss/DrivenByMoss#434]
Heya! I'm having fun with the OSC controller script and https://github.com/fundamental/OpenSoundControl.jl to make a live coding interface for Bitwig in Julia. As I see from the latest docs, `/track/{1-8}/clip/{1-8}/create` will **Create new clip, activate overdub and start it. Beats is the length of the clip in quarter notes.**.

What I'm trying to achieve is rather simple. I would like to insert an empty clip, or a clip from a file.
 
- I generate MIDI clips in-memory from [MIDI.jl](https://github.com/JuliaMusic/MIDI.jl) which should end up in some (temp) directory, let's say (`~/Bitwig Studio/Library/Clips/Julia`).
- Create a new clip via an OSC command, loading the clip into the track, for example sending `/track/1/clip/1/insert` with parameter `"~/Bitwig Studio/Library/Clips/Julia/temp.mid"`

Is this possible? How hard would it be to file a PR to achieve this? It's the missing keystone to complete my library!

**Comment by 0x0f0f0f** [comment]
If possible, I would like to avoid a tedious process of sending many browser commands to locate the clip, or to "live send" the notes. My library does not have a core MIDI clock, and should not need one :)

**Comment by 0x0f0f0f** [comment]
Ah, I see from the API docs that there is:

```
insertFile

void insertFile([String](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/String.html) path)

Inserts the supplied file at this insertion point. If it's not possible to do so then this does nothing.
```

And there is also

**Comment by git-moss** [comment]
AFAIK insertFile can only insert files which are a resource in a Java JAR file.

**Comment by 0x0f0f0f** [comment]
> AFAIK insertFile can only insert files which are a resource in a Java JAR file.

@git-moss not really! I've managed to add a method to `ISlot` and it works like a charm

```
julia> send(sock1, ip"127.0.0.1", 8000, OpenSoundControl.message("/track/1/clip/2/insertFile", "s", "~/Bitwig Studio/Samples/MIDI/skytnt-midi-composer/output1.mid").data)
```

**Comment by 0x0f0f0f** [comment]
I'll file a PR, can we reopen the issue and link it to the PR?

**Comment by 0x0f0f0f** [comment]
See https://github.com/git-moss/DrivenByMoss/pull/435
