### ISSUE TITLE
Novation Launchpad Pro with Bitwig issues triggering other clips

### ISSUE THREAD

**Issue by jvanbunnik** [git-moss/DrivenByMoss#436]
I have been using the latest Drivenbymoss with Launchpad Pro mk3 and Bitwig for a number of years. Couple of days ago I looked at the custom mode which I can't find much in the tutorial by the way. But the issue I have is when I trigger a clip on one track now for some strange reason it triggers another clip on another track and it even opens up a recording on new clip.

I think is has to do with the me pushing some buttons on the custom mode.

Any advise would be appreciated.

thanks
Joost

**Comment by git-moss** [comment]
Custom mode is not supported with DrivenByMoss.

**Comment by jvanbunnik** [comment]
> Custom mode is not supported with DrivenByMoss.

Ok understand. Do you have an explanation why it triggers other clips automatically?

**Comment by git-moss** [comment]
I guess the MIDI notes which are sent from you custom page are the ones used for the pads in the programming mode.
