### ISSUE TITLE
Ports in configuration have no effect

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#44]
I changed the default ports but this has no effect. Bitwig still registers ports 8000 and 9000, whatever I set it to in the settings.

**Comment by git-moss** [comment]
Have you restarted the script (which is necessary)?

**Comment by kdejaeger** [comment]
I restarted Bitwig itself.

**Comment by git-moss** [comment]
You are right. Seems I cannot fix this since new OSC reader/writer interface can only be called during init. Will ask the Bitwig people about it.

**Comment by git-moss** [comment]
Receive port will work again in DrivenByMoss 8.50. Fix for output port (and server name) still pending.

**Comment by git-moss** [comment]
Open issue is documented here: https://github.com/teotigraphix/Framework4Bitwig/issues/245
Will close this.
