### ISSUE TITLE
OSC messages missing when muting/soloing etc ... in drumpad

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#47]
When I click on the solo/mute buttons on a layer in a drumpad, no OSC messages are being send out.

**Comment by git-moss** [comment]
Works fine here.

![drumosc](https://user-images.githubusercontent.com/3090132/37244949-c3d7cf44-2488-11e8-8ff9-8fcde5e5f40f.png)

**Comment by kdejaeger** [comment]
Thanks for verifying. I'll check again tomorrow.
