### ISSUE TITLE
OSC: /device/layer/x/volume /device/layer/x/vu missing

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#48]
When I play a part of a drum, I don't get the volume/vu. I do get /master/vu and /track/selected/vu . According to the source code, these should get flushed, I don't understand.

**Comment by git-moss** [comment]
Hmm, seems to be a Bitwig bug. When I click on the drum pad in Bitwig it starts sending the VU.

**Comment by kdejaeger** [comment]
I'm using the demo song "In Cycles", track "Dusty Drops". The first device is a drum rack. Indeed I only receive these parameters once, when the drumrack is selected. /vu of the drumrack layer I sometimes get, sometimes not. The OSC /drumrack I receive sometimes, sometimes not, mostly not. I think it has to do maybe with some if (tests) before sending out the /drumrack url's.

**Comment by git-moss** [comment]
but the layer VUs are also not sent (which are always triggered)

**Comment by git-moss** [comment]
Seems to work in 3.1.
