### ISSUE TITLE
Add /device/page/selected/name or similar

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#49]
Presets can be switched with /device/param/+ and /device/param/- .
Can you please send out the name of the chosen preset as well when this change happens?

**Comment by git-moss** [comment]
Have you looked at the template how it is implemented there? Don't you think that is sufficient?

**Comment by kdejaeger** [comment]
Well if I don't change my implementation, I need it. Because I'm making a template for phone/tablet usage, similar to the touch osc template. So I am using just 2 buttons to navigate through the presets.

I had never limited my thinking in parts of 8, so I am not using the banks up and down buttons yet. If there would not be the concept of banks, then in theory, I could replace the /device/param/++ and -- with a switch dropdown when I could fetch more than 8 values.

**Comment by git-moss** [comment]
/device/page/selected/name {name} will be in next update.
