### ISSUE TITLE
Strange layouts for some scales in Bitwig chromatic mode on Push

### ISSUE THREAD

**Issue by agrover** [git-moss/DrivenByMoss#5]
Hi, I'm using a Push 1 with Bitwig 2.1.3 on Windows 10 64bit.

I'm seeing weird layouts for some scales when in chromatic mode, specifically Locrian, diminished, whole tone, minor blues, minor pentatonic, major pentatonic, super locrian, Hungarian minor, Hirojoshi, in-sen, iwato, kumoi, and pelog. Based on what Ableton does at least, these should all keep the standard chromatic layout (each higher octave is two over, two up) and just change which white keys are lit.

Also, I think there should be another half note scale degree in the whole-half scale. Both chromatic and in-key modes are affected.

Much thanks -- Andy

**Comment by git-moss** [comment]
Thanks for reporting! Seems are bugs in the scales you mentioned and also my drawing code seems to be a bit different. I need some time to wrap my head around this but it should be fixed in the next version.

**Comment by git-moss** [comment]
I fixed the drawing code and also fixed a bug in Locrian. For Hirojoshi and Pelog I had different variants which I adapted as well.
I am not sure about the Spanish scale. From what I read on the internet the Ableton layout seems to be wrong to me. Could you have a look? E.g. http://www.howmusicworks.org/409/Scales-and-Melody/Spanish-Scale

**Comment by agrover** [comment]
Thanks for fixing that, works great now!

I agree the Ableton Spanish scale is not correct.

**Comment by agrover** [comment]
issue fixed in latest version, closing.
