### ISSUE TITLE
OSC: /preroll mixed types

### ISSUE THREAD

**Issue by jamols** [git-moss/DrivenByMoss#51]
/preroll : receives an integer, but sends a string

Perhaps it should send + receive only integers, or only strings

When an integer is sent, the client display (ex. OpenStageControl dropdown or switch, which should reflect current integer-based state) is wiped by immediate feedback as string

```
OSC sent: { address: '/preroll', args: [ { type: 'i', value: 1 } ] } To : 127.0.0.1:8000
OSC received: { address: '/preroll', args: 'one_bar' } From : 127.0.0.1:59956
```

**Comment by git-moss** [comment]
Good catch! Will only send integers in next update.
