### ISSUE TITLE
OSC: add hasParent

### ISSUE THREAD

**Issue by kdejaeger** [git-moss/DrivenByMoss#53]
I would like to have a /track/selected/hasParent so I can conditionality show a /track/parent button.

**Comment by git-moss** [comment]
Only if you tell me how you do that :-)

**Comment by kdejaeger** [comment]
Ok :). Check out my [template](https://raw.githubusercontent.com/kdejaeger/open-stage-control-bitwig/master/open_stage_control_bitwig.json). The navigation section has an invisible text widget for /track/hasparent. The widgets output (0 or 1) is then consumed in the dynamic css property.

**Comment by kdejaeger** [comment]
The whole trick I use with invisible buttons will be replaced by this new feature I think: https://github.com/jean-emmanuel/open-stage-control/issues/191 that was just pushed. I don't have time to check it out but looking from the comments we could do something like this now as the value of a css field:

#{
    hasParent = OSC{"/track/selected/hasParent", 0}
    hasParent == 0 ? "visibility:hidden" : ""
}

**Comment by git-moss** [comment]
Thanks, will add hasParent in the next update.

**Comment by git-moss** [comment]
Just tried to implement this but it turns out it is currently not possible. I also checked back with Bitwig to be sure and it is now on the (long) wishlist. Sorry.

**Comment by abique** [comment]
The Track interface has a position, you should check but I believe that only the root track group has the position 0.

**Comment by git-moss** [comment]
Good idea, I could check if the position is 0 and if it is a group. Will five it a try.

**Comment by abique** [comment]
Maybe checking that the position is 0 is enough.

**Comment by git-moss** [comment]
Actually, that is not going to work. Imagine you have 20 tracks on the top
level, they all have different positions but no parent. Same is inside of a
group, whicj jas a parent.

Alexandre Bique <notifications@github.com> schrieb am Mi., 22. Mai 2019,
17:23:

**Comment by abique** [comment]
Every tracks always have a parent, only the root track group does not have one.

**Comment by abique** [comment]
Maybe you're interested in the depth of the track?

**Comment by git-moss** [comment]
Yes, but that info does not help. I cannot check for the root track ...

Alexandre Bique <notifications@github.com> schrieb am Mi., 22. Mai 2019,
18:12:

**Comment by abique** [comment]
Track Track.createParentTrack()

I think that would do the job. You can then call parentTrack.exists(), move the cursor to the parent track and so on...

Would it work for you?

**Comment by git-moss** [comment]
I guess.

Alexandre Bique <notifications@github.com> schrieb am Mi., 22. Mai 2019,
18:23:

**Comment by git-moss** [comment]
There is also the wish to access the whole path from tje root to the
cirrent track. Can we solve that somehow in one go?

Jürgen Moßgraber <juergen.mossgraber@googlemail.com> schrieb am Mi., 22.
Mai 2019, 18:24:

**Comment by abique** [comment]
What is the whole path supposed to look like?

**Comment by git-moss** [comment]
e.g. Drums -> Toms -> Floor Tom

Alexandre Bique <notifications@github.com> schrieb am Mi., 22. Mai 2019,
18:46:

**Comment by git-moss** [comment]
So you can quicker mobe up a group tree.

Jürgen Moßgraber <juergen.mossgraber@googlemail.com> schrieb am Mi., 22.
Mai 2019, 18:48:

**Comment by abique** [comment]
Yes that is useful, I'll discuss with Nick how we want to do that.

**Comment by teotigraphix** [comment]
Breadcrumbs. :)

**Comment by git-moss** [comment]
Exactly 😁

Michael Schmalle <notifications@github.com> schrieb am Mi., 22. Mai 2019,
18:57:

**Comment by abique** [comment]
That might be useful if push 3 has a touch screen.
Did any of you guys put your hands on the AKAI force?

**Comment by teotigraphix** [comment]
@abique Yeas I have the Force, don't get me started on Akai, like Native Instruments and the Maschine Studio bug,  hehe. I got it for my guitar recording and such.

I'll really like it when I Akai finally finishes it's implementation. Seems like they released it when it was still alpha. :) 

Also, I don't think they are allowing USB MIDI, yes you heard it right, no USB MIDI, let's just say I and others were not happy on their site. Akai stonewalled, I left the forum and now I am talking to you about it. :)

I am doing Touch4Bitwig right now, so this is funny.

**Comment by git-moss** [comment]
/track/hasParent {0,1} will be added to DrivenByMoss 8.50.

**Comment by kdejaeger** [comment]
Hi, I tested this today and noticed that /track/selected/hasParent does not work yet. (bitwig 3.1). Can you verify/propagate hasParent also for the /selected url? Just like /track/selected/isGroup works as well?

**Comment by git-moss** [comment]
That is not necessary since there is only one parent, so you can simply use /track/hasParent.
