### ISSUE TITLE
Osc: openstage vu meters do not react to live audio

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#54]
Hey,let me know if there is a format you prefer here and I’ll make sure to use that as I find issues. 

Vu meters don’t react to live audio being recorded

Arm track with live input of voice or guitar and Vu meters are dead

**Comment by git-moss** [comment]
Will test.

**Comment by git-moss** [comment]
Seems to be a Bitwig bug. Strangely, the VU is updated for the Master track.

**Comment by Sebastian-blu** [comment]
also noticed most of the vu feedback is bad when on the edit screen

**Comment by Sebastian-blu** [comment]
Actually I lose basic button function when I’m the edit window as well. Solo mute don’t seem to respond

**Comment by git-moss** [comment]
Seems to work in 3.1.
