### ISSUE TITLE
Osc: automation mode touch not functional 

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#56]
Automation control set to touch doesn’t really work with tablet. When I release the fader it doesn’t go back to where it started. It also just continues to write automation at the level I let go of it. Is this your experience Moss? 

Also it doesn’t really function well in Bitwig Studio on the computer. If you move the fader there the automation line moves back to original position when released but the fader on screen stays put.

**Comment by jamols** [comment]
Likely requires adding an additional touch address for each parameter? Otherwise Bitwig has no way of knowing when you are and aren't touching the fader. 

ex. /track/1/volume/touched
http://osc.ammd.net/widgets/widgets/#touchaddress

**Comment by git-moss** [comment]
Need to test.

**Comment by git-moss** [comment]
Yes, Jamols is right. The following commands will be available in the next update:
* New: Receives /track/{1-8}/volume/touched {0,1}
* New: Receives /track/{1-8}/pan/touched {0,1}
* New: Receives /track/{1-8}/send/{1-8}/touched {0,1}
* New: Receives /device/layer/{1-8}/volume/touched {0,1}
* New: Receives /device/layer/{1-8}/pan/touched {0,1}
* New: Receives /device/layer/{1-8}/send/{1-8}/volume/touched {0,1}
* New: Receives /device/param/{1-8}/touched {0,1}
