### ISSUE TITLE
device/layer/{+-} seems backwards

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#59]
I had an up arrow mapped with plus and and it moved the selected position down. minus goes up. 

 I think its because each layer is named plus one going down as you add them

no big deal I just swapped it but might be good to switch on your end to match bitwig?

**Comment by git-moss** [comment]
+ increases in the order of the layers. On the Bitwig UI it is the other way round but you should not compare a programming interface with a UI :-)
