### ISSUE TITLE
/device/layer/SELECTED/volume

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#61]
hey I was trying to implement a single fader for device layer volumes like this

<img width="242" alt="screenshot_2018-03-16 18 27 30_ut6kix" src="https://user-images.githubusercontent.com/28813706/37550296-04de27cc-2948-11e8-8fb8-ec7d8ced1449.png">

but it doesn't seem to work, maybe its not possible?

I could do a modal with the faders in there too

**Comment by git-moss** [comment]
That is currently not implemented but I added it for the next version.
