### ISSUE TITLE
/layout/{arrange,mix,edit} not working

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#62]
/layout/{arrange,mix,edit}

I just added these can't get them to function

**Comment by git-moss** [comment]
Look at the template that comes with DrivenByMoss.

**Comment by Sebastian-blu** [comment]
ok a switch!!! hadn't tried that yet. thanks for your help man you should grab my launcher if you want 

[barryCleanBitwigControlViewcopy.json.txt](https://github.com/git-moss/DrivenByMoss/files/1822299/barryCleanBitwigControlViewcopy.json.txt)
