### ISSUE TITLE
How does record supposed to work for KK Mk2?

### ISSUE THREAD

**Issue by tombburnell** [git-moss/DrivenByMoss#67]
The transport and mixer seem to work ok but pressing the record button in arrangement view, whilst it makes the light go red, seems to have no effect in terms of allowing to record into the. It seems to work for overdubbing an existing session clip though.

Also I've been getting plugin crashes with NullPointerExceptions

![image](https://user-images.githubusercontent.com/426754/39388385-8d28aa6c-4a77-11e8-8749-e2bb3c9f9acc.png)

**Comment by git-moss** [comment]
I guess you have not updated to the latest release.
