### ISSUE TITLE
openStage osc template missing original mix fader that the clones are built from .32.4

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#73]
hey I was just checking back in to see if the new version of open stage control fixed the problem I recently reported. And its not throwing any errors now but you still are missing the main fader. I was just wanting to see how the touch awareness was implemented but on the latest version this is what I see. all the clones for the faders are there but there is no original strip. 

![screenshot_2018-06-09 16 49 13_y9hfss](https://user-images.githubusercontent.com/28813706/41197030-161d8316-6c05-11e8-936d-837c3c669c1f.png)

**Comment by git-moss** [comment]
Please report Open Stage Control bugs here: https://github.com/jean-emmanuel/open-stage-control/issues

**Comment by Sebastian-blu** [comment]
I usually do but this seems more like a problem with your file maybe something was deleted by mistake before u uploaded? everything else functions as normal and so do all my templates? really I just want to know how to implement the touched parameters for controlling touch automation of faders.

**Comment by git-moss** [comment]
Just test on Windows 10 with 32.4. Everything seems to work fine.
Maybe a Mac bug?

**Comment by git-moss** [comment]
Ah, I guess I know what your problem is: If you just load the file and press on edit there is no channel! You first have to receive at least 1 channel. If you then click on edit works.
Not, sure if this is a fixable Open Sound Control bug since the hidden track is intentional.

**Comment by Sebastian-blu** [comment]
yep that was what it. I didnt realize there was a way to hide unnecessary parts of the layout. Thats pretty cool I just spent the morning adding that to my layout. much cleaner now.
