### ISSUE TITLE
what does this mean in your template?

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#74]
"Added touch indication to sliders (parameters, volume, pan and sends)"

I see the above in your documentation and I see it the fader field but I don't see what it does in bitwig?

/track/@{parent.variables.n}/pan/indicate

**Comment by git-moss** [comment]
I shouldnt have used the word "indication" in the above sentence. The "indication" commands enable the coloring e.g. of 8 volume faders in Bitwig. The "touch" commands instead tell Bitwig that you touched a knob or fader e.g. for automation touch mode.
