### ISSUE TITLE
question: will "Receives /track/{1-8}/volume/touched {0,1}" make touch mode in automation work?

### ISSUE THREAD

**Issue by Sebastian-blu** [git-moss/DrivenByMoss#75]
New: Receives /track/{1-8}/volume/touched {0,1}

I am wondering if implementing this somehow will help make the touch automation mode work as desired. write automation while touched and go back to old automation when not. But where would I put this in my osc layout?

thanks for any help and for all the other work you have done this thing is really awesome now

**Comment by git-moss** [comment]
Yes, it is for touch automation. You need a client, which supports this. E.g. Open Stage Control has a field to set a command to send "on touch".
