### ISSUE TITLE
Track: Scroll Tracks Command in Flexi

### ISSUE THREAD

**Issue by everydayempath** [git-moss/DrivenByMoss#77]
Hi, 
Thank you for making this script! 

1) I'm having an issue when I set a button to 'scroll tracks' it will only scroll from the furthest right track to the furthest left track, but it will not loop around to the end again. 

2) I also wanted to ask if there is a way to use my -/+ buttons on my Roli loop block to control parameters relative to the selection of other buttons, much like how it is used in the Noise app? An example would be having them control which clip I'm on when selecting record, or controlling the volumes of the selected track?

**Comment by git-moss** [comment]
1) Wrapping round at the end is more a bug than a feature. With the normal bank API you can scroll up and down but this does not wrap around. I implemented the scrolling with selection and it seems when a non existing index at the end is selected it select the very first one.
2) Maybe I do not understand your questio but there are already function for selected items, e.g. "Track selected: Set Volume Track".
