### ISSUE TITLE
FR: Add a midi channel selector to the LP Pro settings

### ISSUE THREAD

**Issue by rhofour** [git-moss/DrivenByMoss#79]
I had my Launchpad Pro set to MIDI channel 3 and it took me a while to figure out why it wasn't working. It seems this only works on channel 1. If MIDI channel was selectable in the preferences I could have figured it out much more easily.

Alternatively, this could simply ignore MIDI channel. That would make it easier for people to use, but I think it could be more limiting.

**Comment by git-moss** [comment]
I added a comment to the Installation description in the Wiki.
