### ISSUE TITLE
Using DrivenByMoss as famework - Extension not visible in Bitwig

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/DrivenByMoss#85]
Hey Moss,

I am trying to plug into the framework part of this. I have created all stubs exactly mirroring your OSC extension implementation.

Everything compiles fine but my extension is not recognized in Bitwig.

I created a simple hellow world and compiled in Eclipse, works fine but with your framework I can't get it to register.

I also noticed that your compiled extension is about 1MB, my compiled is 2MB. I have virtually no code just your framework is getting added even the extensions you are maintaining.

Do you have any idea what I am not doing to get Bitwig to see this extension using the framework?

**Comment by teotigraphix** [comment]
Ok, after a couple hours I figured out what I was missing and it was that bootstrap service file that declares the name of the definition.

**Comment by git-moss** [comment]
Just wanted to write that. But it's great if problems solve themselves :-)

**Comment by teotigraphix** [comment]
Through the journey I also figured out how to make DrivenByMoss project a dependency of my project which made it better. Maven is not my forte. :)
