### ISSUE TITLE
OSC - transport.play () used where should be transport.stop()

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/DrivenByMoss#86]
https://github.com/git-moss/DrivenByMoss/blob/39c0892eb1305dd80bc9f482698551035e157dab/src/main/java/de/mossgrabers/controller/osc/protocol/OSCParser.java#L324

Is this for a reason or an oversight?

**Comment by git-moss** [comment]
It's intentional. It also stops playback but if I remember correctly it deals differently with the play cursor (woudl need to test).

**Comment by teotigraphix** [comment]
Ah, hmm well it stops the transport because the toggle but then plays it again obviously if you press stop again.

I am writing my Android app finally and I guess I am copy/pasting everything from OSC into my own abstract class (parser/writer) to deal with this kind of stuff and added commands.

Thanks.
