### ISSUE TITLE
OSC: Missing documentation

### ISSUE THREAD

**Issue by metakeule** [git-moss/DrivenByMoss#89]
I used to use OSC4Bitwig and have created custom programs based on it.
Sadly it doesn't work any more with bitwig 2.4 and I had to switch to DrivenByMoss/osc
which is neither compatible nor has any documentation.

So it is really sad to have to dig through some weird OpenStageControl4Bitwig.json and try to extract
the paths and values for the OSC messages for dozens of messages just because there is no documentation at all. So please add docs. Anyway thanks for your work!

**Comment by git-moss** [comment]
You mean like this? https://github.com/git-moss/DrivenByMoss/wiki/Open-Sound-Control-(OSC)

**Comment by metakeule** [comment]
yes, was hidden in the side bar, thanks!
