### ISSUE TITLE
Delete + select track to delete that track, problems focusing the track sometimes

### ISSUE THREAD

**Issue by lehtiniemi** [git-moss/DrivenByMoss#91]
edited below

**Comment by lehtiniemi** [comment]
Oh, I see this already exists, but it seems it only works when the track header is focused in Bitwig and I'm having unconsistent results focusing the track header by pressing the track name button in mix mode. I'll try to reproduce better...

**Comment by git-moss** [comment]
That's currently not possible. See https://github.com/teotigraphix/Framework4Bitwig/issues/180
If you use the Delete button without a combination (e.g. plus a pad), it simply sends a Delete button press, therefore it depends on what you have selected.

**Comment by lehtiniemi** [comment]
I also tried to press Delete+Track button (the one with track name), but this didn't seem to work. Maybe this would be a way to delete track then?
-select mix mode
-hold delete + track name button
