### ISSUE TITLE
OSC: increase track limit

### ISSUE THREAD

**Issue by creativecontrol** [git-moss/DrivenByMoss#94]
Is it possible to increase the track limit past 8 ?  I am currently working on an audio installation in which I plan to use Bitwig. I need to switch between compositions which are organized in groups. Control and note data is being generated algorithmically by external software and passed to Bitwig using MIDI. I need to be able to put more than 8 tracks in monitor mode via Python as I switch between compositions. I am happy to make the adjustments to the extension myself but I cannot locate where the track number limitation is imposed.

Thanks for your help.

**Comment by git-moss** [comment]
Sadly, currently bank page sizes cannot be changed after startup of the script. If you want to change the code you need to add a call to 
ms.setNumMarkers (YOUR_PAGE_SIZE_HERE); 
in class de.mossgrabers.controller.osc.OSCControllerSetup
after line 75.
