### ISSUE TITLE
OSC: Track record arming issues (Bitwig 2.4)

### ISSUE THREAD

**Issue by metakeule** [git-moss/DrivenByMoss#95]
1. Track arming with a fixed value (= no toggle) does not work at all. Sometimes it disables monitoring (?!).

2. When the sequencer is playing, `track arming toggle` does does reliably generate feedback from bitwig. Sometimes it does, sometimes not. When not playing, it is reliable.

**Comment by git-moss** [comment]
Sorry, but I cannot reproduce any of those problems. Again: what client are you using? Maybe it sends wrong values?

**Comment by metakeule** [comment]
Ok, I checked it with different clients, and it seems, my client or my app does something strange.
Have to check, closing for know.
